### ISSUE TITLE
cryptography_vectors is missing from `test` extra

### ISSUE THREAD

**Issue by mtelka** [pyca/cryptography#10242]
There is missing `cryptography_vectors` in the `test` extra in `pyproject.toml` so when tests are run from sdist with the `test` extra installed then testing fails and `cryptography_vectors` needs to be installed manually to make tests passing.

**Comment by alex** [comment]
Yes, the vectors need to be installed manually.

This is because there is no way to specify in `pyproject.toml` that we want to use the in-tree vectors when developing cryptography, and to depend on a released version of the vectors otherwise.

**Comment by mtelka** [comment]
Maybe it is possible to somehow automatically add `cryptography_vectors` to `pyproject.toml` during the sdist tarball creation.  Or, OTOH, what harm it would cause if there is `cryptography_vectors` always in `pyproject.toml`?  During development you could satisfy that requirement easily: just install any version of `cryptography_vectors`; the actual tests would use the in-tree one.

Just ideas...

**Comment by alex** [comment]
If you just specify `cryptography_vectors` sans version constraint, than you can get mis-matched versions. If you specify a version, then we're back to the problem discussed previously -- there's no way to specify the version that's correct for in-tree usage.

**Comment by mtelka** [comment]
You do not need to specify the correct version for in-tree usage because you'll be using the in-tree version that is always correct.

**Comment by alex** [comment]
What's the actual use case for any of this?

**Comment by mtelka** [comment]
I'm packaging `cryptography` for OpenIndiana and I need to run tests to make sure the package is okay.  Since the `cryptography_vectors` is missing in the `test` extras some additional care is needed to make sure it is installed into the test environment.  This is not a big deal because it is scriptable, but it would be great if the `cryptography` testing works out of the box and we can do the `cryptography` packaging fully automatic, simple and straightforward.

Thank you.

**Comment by alex** [comment]
Ok, so if we were going to do this, I guess the move would be:

- In general on `main`, there's no bound on `cryptography_vectors` -- if you use code from main it's your responsibility to ensure the right version of the vectors is installed.
- When we do a version bump for a release we add an `=={version}` bound to the dependency. This works in CI because the local vectors has the right version, and works in release because it's the right version
- When we re-open main after a release, we remove the bound

Does that match what you were describing?

**Comment by mtelka** [comment]
Yes it does.
