### ISSUE TITLE
Trying to build Docker image with python cryptogrophy library fails.

### ISSUE THREAD

**Issue by gegoxaren** [pyca/cryptography#10441]
I'm trying to build [matrix-rss-bridge](https://gitlab.com/imbev/matrix-rss-bridge) via docker, as the none-docker build fails miserably.

But the docker build fails in a very different way! Below are logs from the build (I have added extra information in at the top about the system).

https://gegoxaren.v0x.eu/misc/matrix-rss-bringe-docker-compose-build.txt  \
alt.\
https://pastebin.com/sd5XWQvZ

As you can see the build complains that `This package requires Rust >=1.63.0`, but it is installed (the standard in Debian Bookworm).

Does anyone have any idea on how to fix this?

Thank you in advance,\
Gustav.

**Comment by reaperhulk** [comment]
Your sample appears to shows that you have rustc installed on your host. Do you have it installed in the docker container? `python:3.9.15-slim` would not include it by default.

**Comment by gegoxaren** [comment]
I don't even know what you are talking about...

I will always assume that it'll use what is installed on the system.

**Comment by reaperhulk** [comment]
Docker is a full isolation layer and does not interact with the host system. The docker image must have rust installed separately from the host.

**Comment by gegoxaren** [comment]
And..?

**Comment by reaperhulk** [comment]
You asked a question about missing rust. I've answered it with a question about the environment you're attempting to build it in. If you don't know the answer or don't know how to get that answer then I'd suggest looking into how Docker, container isolation, and Dockerfiles work so that you can troubleshoot your issue more effectively. As is, this does not appear to be an issue with this project so this is as much assistance as we can provide.
