### ISSUE TITLE
Cryptography 44.0.0 error with GlibC 2.33 on Azure function

### ISSUE THREAD

**Issue by benni-richter** [pyca/cryptography#12064]
Error: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.33' not found (required by /home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/bindings/_rust.abi3.so), Cannot find module.

Version 43.0.3 works fine.

Tested on Python 3.11, cryptography 44.0.0, cffi 1.16.0, pip 24.0, setuptools 65.5.1
Installed cryptography as dependency of pyjwt (pyjwt[crypto])

**Comment by blueelvis** [comment]
+1 . Facing this exact same issue on Azure Functions Python 3.10. On our end, the environment is being built using `python -m build -w`

**Comment by alex** [comment]
What platform are you building the environments on?

**Comment by reaperhulk** [comment]
As @alex noted, we need to know the env/distribution you're building in (if you're not using the wheel) and what wheel you're downloading otherwise.

When you construct an environment on a Linux host `pip` will prioritize the highest libc version that's compatible with the underlying distribution of the host. Previously, for glibc-based distributions we shipped 2.17 (aka manylinux2014) and 2.28 compatible wheels, but with 44 we now ship 2.34 as well. It's possible you are incorrectly downloading that new wheel, which is compatible with your host but not your target in Azure Functions. Generally the advice for services like Lamdba and Azure Functions is to download the oldest glibc wheel as those services tend to have very old glibc as part of their runtime.

**Comment by blueelvis** [comment]
@alex - My bad for not specifying this earlier. We are using the Microsoft Hosted agent ubuntu-22.04 which has the following packages - https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

@reaperhulk - I see that `libc6-dev` is `2.35` but when I checked the runtime environment inside Azure Functions after the function is deployed, `ldd --version` is showing as `2.31`. I guess that's why the issue is happening where the build environment is picking up the latest package because it has the updated version of glibc. Thanks for pointing out towards this!

This issue has been raised in the Azure Identity repo has well because it has a very loose dependency on Cryptography because of which our deployments started failing - https://github.com/Azure/azure-sdk-for-python/issues/38721

We have pinned our version to `43.0.3` as a workaround for this issue. I guess till Microsoft doesn't update their runtime image for Azure Functions, this would have to be the fix.

**Comment by reaperhulk** [comment]
If you deliberately install the 2_24 or 2_17 cryptography wheel it should also work, although I'm not sure how you force that in your build env. If you can control pip invocations then something like `pip install --platform manylinux_2_17_x86_64 cryptography`, although that will also require `--target` to specify the location to install it to (so you'll need to determine where your packages are being installed when you normally build and pass that path to `--target`).

**Comment by blueelvis** [comment]
Yeah, we are installing the packages at a specific directory for it to be packaged and executed in Azure Functions. We fixed it by just pinning the Cryptography version to `43.0.3` in our `requirements.txt` file.

**Comment by munizig** [comment]
For me, it began yesterday and stopped executions completely after a new deployment. The function is blob-triggered. As an inherited dependency it was not defined into `requirements.txt`. Adding a specific version `43.0.3` solved the issue.

**Comment by himanshu-ram-punjabi** [comment]
Thank you, @blueelvis. Specifying 43.0.3 in requirmeents.txt worked for me too, even though it is a temporary solution.

**Comment by alex** [comment]
I would encourage people to read @reaperhulk's write up on https://github.com/Azure/azure-sdk-for-python/issues/38725#issuecomment-2508305334. This is a problem of how Azure environments are built, pinning to an old cryptography version isn't the proper fix.

**Comment by phlax** [comment]
fwiw we just got hit by this in github - we use bazel/rules_python to install and run the relevant ci in a (ubuntu) container

**Comment by Shuvo31** [comment]
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/site/wwwroot/antenv/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)

I was using python 3.11.10 version in ubuntu 22.04.
Specifying 43.0.3 in requirements.txt worked for me too, even though it is a temporary solution.

**Comment by spencweaver** [comment]
I was missing this dependency that resolved the problem for me: `pip install setuptools_rust`

**Comment by chris-griffin** [comment]
We are running into this issue when running on the GitHub Action`ubuntu-24.04` image  but **not** the `ubuntu-22.04` image.

```
   File "/home/runner/work/banking/banking/lib/pem_key.py", line 1, in <module>
    from cryptography.exceptions import UnsupportedAlgorithm
  File "/home/runner/.local/share/virtualenvs/banking-venv/lib/python3.11/site-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/runner/.local/share/virtualenvs/banking-venv/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
```

We also confirmed that Cryptography version 43.0.3 works on the GitHub Action`ubuntu-24.04` image.

The `ubuntu-24.04` image did remove a decent amount of dependencies: https://github.com/actions/runner-images/issues/9848

This issue mentions that glibc was removed from the image: https://github.com/actions/runner-images/issues/11666
