### ISSUE TITLE
Using Fernet with user-generated key

### ISSUE THREAD

**Issue by maebert** [pyca/cryptography#1333]
I'm trying to figure out what the best practice is for using Fernet with a password or passphrase chose by the user. I'm aware of #1149, but haven't found a sane working example yet. Basically the challenge is converting the passphrase to 32 bytes before passing them on to Fernet. Naively, you could do:

``` python
import base64, hashlib
from cryptography.fernet import Fernet

my_password = 'swordfish'
key = hashlib.md5(my_password).hexdigest()
key_64 = base64.urlsafe_b64encode(key)
cipher = Fernet(key_64).encrypt("My dirty secrets")
```

I know that Fernet will make a SHA256-HMAC of that key before encrypting, but ideally I'd like to use PBKDF2 to salt the key etc. What's the safe, sane way to use Fernet with a user-generated password?

**Comment by reaperhulk** [comment]
We've had some mailing list traffic around this and blog posts (http://incolumitas.com/2014/10/19/using-the-python-cryptography-module-with-custom-passwords/) have started cropping up that are recommending very dangerous solutions. It might be time to revisit this and decide whether we want to implement this.

If we do choose to implement it we'll need to decide whether it's just going to be something we provide or if we want to try to merge it into the spec upstream.

**Comment by Ayrx** [comment]
@reaperhulk One large problem with a KDF recipe we identified previously is iteration count.

**Comment by whit537** [comment]
> blog posts (http://incolumitas.com/2014/10/19/using-the-python-cryptography-module-with-custom-passwords/) have started cropping up that are recommending very dangerous solutions

Noted in the comments over there. :)

**Comment by whit537** [comment]
> Noted in the comments over there. :)

(Though my comment is pending.)

> We've had some mailing list traffic around this 

FTR, here's the [mailing list post](https://mail.python.org/pipermail/cryptography-dev/2015-January/000366.html), and @reaperhulk's [response](https://mail.python.org/pipermail/cryptography-dev/2015-January/000367.html):

> I'd strongly recommend against using that construction as it is just doing a single SHA256 hash of your password and then base64 encoding it. While a password is definitely lower entropy than 32 bytes of random you can still derive a key suitable for encryption from a password by using a KDF (key derivation function). KDFs are useful in this context because they raise the cost of computing the key so that an attacker can't easily brute force the password. Consider replacing the get_key function with something using [PBKDF2HMAC](https://cryptography.io/en/latest/hazmat/primitives/key-derivation-functions/#cryptography.hazmat.primitives.kdf.pbkdf2.PBKDF2HMAC). An even better KDF would be something like scrypt, but unfortunately we don't support that in pyca/cryptography yet.
>
This definitely is showing a need for an official password-based encryption key derivation for Fernet...

**Comment by himanshu219** [comment]
> I'm trying to figure out what the best practice is for using Fernet with a password or passphrase chose by the user. I'm aware of #1149, but haven't found a sane working example yet. Basically the challenge is converting the passphrase to 32 bytes before passing them on to Fernet. Naively, you could do:
> 
> ```python
> import base64, hashlib
> from cryptography.fernet import Fernet
> 
> my_password = 'swordfish'
> key = hashlib.md5(my_password).hexdigest()
> key_64 = base64.urlsafe_b64encode(key)
> cipher = Fernet(key_64).encrypt("My dirty secrets")
> ```
> 
> I know that Fernet will make a SHA256-HMAC of that key before encrypting, but ideally I'd like to use PBKDF2 to salt the key etc. What's the safe, sane way to use Fernet with a user-generated password?

What are the disadvantages of using this approach is it vulnerable to rainbow tables?

**Comment by reaperhulk** [comment]
This is not a good approach because when deriving a cryptographic key from a user password you want guesses to be computationally expensive. User passwords are generally low entropy and relatively easily guessable, so we use a password-based key derivation function (PBKDF) to disadvantage an attacker. At the simplest form this can be repeated hashes, but modern best practice uses "memory hard" functions like scrypt or argon2id where possible. These functions make building custom hardware to accelerate much more difficult.

To answer your exact question, yes rainbow tables would work against your approach, but generally with the speed of modern hashes you don't even need to generate rainbow tables and can instead try trillions of potential keys per second looking for a match. Take a look at the documentation for scrypt to see how to use it: https://cryptography.io/en/latest/hazmat/primitives/key-derivation-functions/#cryptography.hazmat.primitives.kdf.scrypt.Scrypt

**Comment by himanshu219** [comment]
Thanks! Good to know.

**Comment by reaperhulk** [comment]
https://cryptography.io/en/latest/fernet/#using-passwords-with-fernet documents the way to derive a key from a user password using a PBKDF (like scrypt, bcrypt, or PBKDF2). Since PBKDF best practices shift over time as computers get faster we're not going to expose a simpler API for this at this point.
