### ISSUE TITLE
Stop using dictionaries for test data in our vector loaders

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#1440]
Right now some use dictionaries and others use named tuples, they should all use the namedtuple style -- it's easier to read, more maintainable, and probably faster to boot!

**Comment by eeshangarg** [comment]
Hi!

I was working on this at the PyCon sprints, but while working on it, I found that using namedtuples would not make sense, because considering the number of test cases, we would need more than a dozen different namedtuples to accomplish this; not to mention that various vector loader functions have multiple if conditions according to which they append key/value pairs to their test_data dictionaries, which won't be possible with nametuples. This implies that we would basically have to instantiate multiple namedtuples in the same vector loader function for all the different cases and if conditions.

Thanks to @reaperhulk for his guidance!

Regards,
Eeshan Garg

**Comment by reaperhulk** [comment]
Based on Eeshan's investigation I'm closing this as a won't fix. If anyone disagrees we can reopen and discuss.
