### ISSUE TITLE
Where should our backends live?

### ISSUE THREAD

**Issue by Ayrx** [pyca/cryptography#1522]
There have been discussions in IRC about whether our optional backends (ala my scrypt PR in #1456) should live in the primary cryptography git repository or if it should be in a separate repository. Rather than have the discussion be lost in IRC chat logs, let's document our thoughts in a more visible place.

I know @dstufft has strong opinions on this matter so rather than paraphrasing what he said on IRC, I'll leave it to him to argue his stand. :) Anyone with opinions on this matter should voice them out as well as I think it will be a major pain to change later.

**Comment by dstufft** [comment]
Ok, so I want to bring this discussion back around.

Thinking about this more, I think the only sane way to really handle this is to split out each backend into their own wholly independent package. This would mean that we'd have the following packages:

* cryptography
* cryptography-openssl
* cryptography-commoncrypto
* cryptography-vectors

Doing this would require moving each of the backends to their own import names, probably with some backwards compatibility shims in the cryptography project so that people using the bindings directly don't break (but ideally with a deprecation warning telling people to switch to using the appropriate binding project directly).

This will immediately simplify the logic around under what cases a particular backend is built (always) and we'd be able to rely directly on the packaging toolchains support for non-optional inclusion of things like a commoncrypto backend (or perhaps a Windows crypto backend).

If I recall the last time we had this discussion there was some talk about how Django's database backends work by having a few included within Django itself and then third parties can register their own. I believe that this analogy is flawed because these backends are not like the Django database backends, but are more akin to the database drivers that those backends use (like psycopg2). This is because there is practically no cost incurred to have the PostgreSQL backend installed in Django (other than minor amounts of disk space) since it is pure Python, relies on nothing in the environment unless you actually use it, and doesn't affect the output of building Django. On the other hand, the OpenSSL or CommonCrypto or Scrypt or any other backend in cryptography does not have similar properties. Installing the CommonCrypto backend requires that CommonCrypto be available and the output of the build process (which defines what cryptography "is") changes based on what the answer to that question is. In other words, it would be more like trying to include psycopg2 into Django itself.

Each of these projects needs to be, as far as packaging is concerned, completely independent. That means that they cannot share any files or resources at the filesystem level (such as the ``README.rst`` issue that @Ayrx had above). This includes things like each project having it's own tox file (because tox does not really have any means of installing multiple local packages).

As part of this, I think that we need to split each individual project out into it's own repository or not. I know that @alex was against this, however I believe that, like it or not, the repository is the standard unit for how you group the files for one independent "thing". If we don't split things, then I think we'll have the following problems:

* It becomes difficult to know which tox we need to execute in order to test things within CI, do we need to inspect the diff and look at which file paths are being modified or do we just run all tox runs ever across each project?
* Similar to above, it becomes dificult to know which tests we need to actually execute. There is no reason to run tests against OpenSSL on Windows or Linux if the only thing that changed was CommonCrypto for instance.
* Releases become a lot more confusing, with separate projects it should be entirely possible (and reasonable!) to release them independently. For instance, there's no reason to trigger a release of cryptography, cryptography-commoncrypto, and cryptography-vectors, just because of a bug in cryptography-openssl (or even because we just need to release a new one built against a new OpenSSL). However there is only one namespace for tag versions in git.
* It will become impossible to install anything from the repository with a pip < 1.5, or without using an editable installation. This is because pip only supports having a ``setup.py`` in a subdirectory when installing as an editable and only in pip 1.5+.

There was previously some question about how do we handle running tests against the cryptography "core" if there are no backends in tree. For this, I don't think it's unreasonable to have a set of "official" backends which any change to the core library runs the tests against all of those backends (installing from the latest HEAD of master). This would give us similar test coverage to what we have now, but in addition each individual backend could run a subset of the cryptography test suite that actually matters for that particular binding.

The main reason *not* to split them into separate repositories is the overhead it would introduce while trying to review changes. However I think that it might not actually be as bad as it might appear on the surface. Splitting the PRs apart necessitates that people make smaller, easier to review PRs. It also means that adding an API to cryptography can be viewed as it's own "unit" separate from how openssl or commoncrypto or whatever actually implements such a thing. It would of course make it more difficult to land changes in both repositories, but given that the line between a binding and a backend is public API, looking at them separately from each other can aid in making sure that the APIs separately make sense instead of just looking at the combined result.

There are more questions when it comes to making things optional, however a required first step of that (IMO) is splitting things apart, and before we do that we need to decide if we want to split things apart (I think we should) and if we want to use separate repositories (I think we should). I've started to try and implement splitting them apart in a single repository and I found the tox issue kind of disappointing and confusing.

**Comment by Ayrx** [comment]
Thanks Donald for the write up. I'm convinced that this is the right path
forward. I also believe that with GitHub's support for cross-repository
linking, separate repositories won't prove to be that much of an issue when
it comes to code review for new features.

A strong +1 from me for splitting things up into separate repositories.

**Comment by alex** [comment]
Can someone walk me through how we'd have developed #2045 with a seperated
repo story? Particularly I'd like to understand how testing would happen,
and how we'd use feedback from implementing an interface in evolving the
interface itself.

On Thu, Jun 25, 2015 at 8:49 PM, Terry Chia <notifications@github.com>
wrote:

> Thanks Donald for the write up. I'm convinced that this is the right path
> forward. I also believe that with GitHub's support for cross-repository
> linking, separate repositories won't prove to be that much of an issue when
> it comes to code review for new features.
>
> A strong +1 from me for splitting things up into separate repositories.
> On Fri, 26 Jun 2015 at 3:27 am Donald Stufft <notifications@github.com>
> wrote:
>
> > Ok, so I want to bring this discussion back around.
> >
> > Thinking about this more, I think the only sane way to really handle this
> > is to split out each backend into their own wholly independent package.
> > This would mean that we'd have the following packages:
> >
> > - cryptography
> > - cryptography-openssl
> > - cryptography-commoncrypto
> > - cryptography-vectors
>
> >
> > Doing this would require moving each of the backends to their own import
> > names, probably with some backwards compatibility shims in the
> cryptography
> > project so that people using the bindings directly don't break (but
> ideally
> > with a deprecation warning telling people to switch to using the
> > appropriate binding project directly).
> >
> > This will immediately simplify the logic around under what cases a
> > particular backend is built (always) and we'd be able to rely directly on
> > the packaging toolchains support for non-optional inclusion of things
> like
> > a commoncrypto backend (or perhaps a Windows crypto backend).
> >
> > If I recall the last time we had this discussion there was some talk
> about
> > how Django's database backends work by having a few included within
> Django
> > itself and then third parties can register their own. I believe that this
> > analogy is flawed because these backends are not like the Django database
> > backends, but are more akin to the database drivers that those backends
> use
> > (like psycopg2). This is because there is practically no cost incurred to
> > have the PostgreSQL backend installed in Django (other than minor amounts
> > of disk space) since it is pure Python, relies on nothing in the
> > environment unless you actually use it, and doesn't affect the output of
> > building Django. On the other hand, the OpenSSL or CommonCrypto or Scrypt
> > or any other backend in cryptography does not have similar properties.
> > Installing the CommonCrypto backend requires that CommonCrypto be
> available
> > and the output of the build process (which defines what cryptography
> "is")
> > changes based on what the answer to tha t question is. In other words, it
> > would be more like trying to include psycopg2 into Django itself.
> >
> > Each of these projects needs to be, as far as packaging is concerned,
> > completely independent. That means that they cannot share any files or
> > resources at the filesystem level (such as the README.rst issue that
> @Ayrx
> > <https://github.com/Ayrx> had above). This includes things like each
> > project having it's own tox file (because tox does not really have any
> > means of installing multiple local packages).
> >
> > As part of this, I think that we need to split each individual project
> out
> > into it's own repository or not. I know that @alex
> > <https://github.com/alex> was against this, however I believe that, like
> > it or not, the repository is the standard unit for how you group the
> files
> > for one independent "thing". If we don't split things, then I think we'll
> > have the following problems:
> >
> > - It becomes difficult to know which tox we need to execute in order
> > to test things within CI, do we need to inspect the diff and look at
> which
> > file paths are being modified or do we just run all tox runs ever across
> > each project?
> > - Similar to above, it becomes dificult to know which tests we need to
> > actually execute. There is no reason to run tests against OpenSSL on
> > Windows or Linux if the only thing that changed was CommonCrypto for
> > instance.
> > - Releases become a lot more confusing, with separate projects it
> > should be entirely possible (and reasonable!) to release them
> > independently. For instance, there's no reason to trigger a release of
> > cryptography, cryptography-commoncrypto, and cryptography-vectors, just
> > because of a bug in cryptography-openssl (or even because we just need to
> > release a new one built against a new OpenSSL). However there is only one
> > namespace for tag versions in git.
> > - It will become impossible to install anything from the repository
> > with a pip < 1.5, or without using an editable installation. This is
> > because pip only supports having a setup.py in a subdirectory when
> > installing as an editable and only in pip 1.5+.
> >
> > There was previously some question about how do we handle running tests
> > against the cryptography "core" if there are no backends in tree. For
> this,
> > I don't think it's unreasonable to have a set of "official" backends
> which
> > any change to the core library runs the tests against all of those
> backends
> > (installing from the latest HEAD of master). This would give us similar
> > test coverage to what we have now, but in addition each individual
> backend
> > could run a subset of the cryptography test suite that actually matters
> for
> > that particular binding.
> >
> > The main reason *not* to split them into separate repositories is the
> > overhead it would introduce while trying to review changes. However I
> think
> > that it might not actually be as bad as it might appear on the surface.
> > Splitting the PRs apart necessitates that people make smaller, easier to
> > review PRs. It also means that adding an API to cryptography can be
> viewed
> > as it's own "unit" separate from how openssl or commoncrypto or whatever
> > actually implements such a thing. It would of course make it more
> difficult
> > to land changes in both repositories, but given that the line between a
> > binding and a backend is public API, looking at them separately from each
> > other can aid in making sure that the APIs separately make sense instead
> of
> > just looking at the combined result.
> >
> > There are more questions when it comes to making things optional, however
> > a required first step of that (IMO) is splitting things apart, and before
> > we do that we need to decide if we want to split things apart (I think we
> > should) and if we want to use separate repositories (I think we should).
> > I've started to try and implement splitting them apart in a single
> > repository and I found the tox issue kind of disappointing and confusing.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pyca/cryptography/issues/1522#issuecomment-115370078
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/1522#issuecomment-115448021>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dstufft** [comment]
I've been thinking about this on and off and then #2729 brought it into the foreground again for me. I think I'd like to actually get this solved now.

I still think that splitting each backend into it's own package on PyPI is the right way forward (and I don't think that there was any disagreement with that). I also think that splitting these into different repositories is the right way forward (and there was some disagreement here). I don't think it really works well to have multiple, independently released, things living in the same repository.

A big question though, was if we split things into multiple repositories, how does testing and such actually work. I've done some thinking on this, and here's what I think should happen:

* Everything not in a bindings or backend layer should move to ``cryptography-core`` package which will be importable using ``import cryptography``.
* Each backend/binding will be moved to a ``cryptography-foo`` package which will be importable using ``import cryptography_foo`` and discoverable using entry points.
* A top level meta package called ``cryptography`` should be created which just depends on ``cryptography-core`` and our default backends for wahtever OS we're on.
* We keep the ``cryptography_vectors`` package which contains just the vector files themselves.
* Move the tests into ``crytography.tests`` and add extras to make it so you can do ``pip install cryptography[tests]`` to be able to run tests against the installed cryptography.
* Move the bindings/backend specific tests (like ``tests/hazmat/backends/test_commoncrypto.py``) into their respective ``cryptography-foo`` package.
* Ensure that all of the cryptography tests can run against any installed backend.

This splits up all of our packages into single units. Then for testing, we can set this up so that a change to the ``cryptography-core`` package runs the ``tox.ini`` from ``cryptography-core``. This will install all of our "official" backends (openssl, commoncrypto, crypt32, whatever) and then run all of the tests against that, including the tests specific to those backends. This means that for changes to the core package, we get all of the same testing as we do now. Then for changes to a package like ``cryptography-openssl``, we pull in ``cryptography-core``, but not any of the other backends and run the tests for that backend. This means for backend/binding specific changes, we get faster results because we're not needlessly running the openssl tests for a change to commoncrypto.

Now, one thing I glossed over above, is how we'd handle dependent pull requests, particularly when you want to make a PR to add a new interface to ``cryptography-core`` and implement that in ``cryptography-openssl`` and make sure it all actually works sanely before merging them. For this, I would have the ``tox.ini`` default to installing these packages from the ``master`` branches of each repository (or perhaps from PyPI?) and then I'd use the environment variable substitution support in ``tox.ini`` to allow an environment variable to force override where we install from for each dependency. Thus something like ``CRYPTOGRAPHY_CI_OPENSSL=git+https://github.com/dstufft/cryptography-openssl.git@mybranch#egg=cryptography-openssl tox -e py35`` would, in the ``cryptography-core`` repository, test it against that repo/branch.

The final bit of automation that would make this all work, is to use something similar to the bit where Github lets you link issues using something like ``closes #123`` in a PR body, by allowing people to say something like ``tests against pyca/cryptography-openssl#123`` in a PR, which our CI would then automatically set the ``CRYPTOGRAPHY_CI_OPENSSL`` variable to the branch/repository pointed to by the given PR.

**Comment by alex** [comment]
I think there a bunch of strong functional reasons to split up packages,
but the multiple repos one is largely aesthetic IMO. While I agree with
that aesthetic, it seems like we could capture a decent portion of the
value by doing multiple projects in one repo first, and seeing how that
goes from a release management perspective before we split repos (which I
think we all acknolwedge is much more complex)

On Wed, Feb 24, 2016 at 8:09 AM, Donald Stufft <notifications@github.com>
wrote:

> I've been thinking about this on and off and then #2729
> <https://github.com/pyca/cryptography/pull/2729> brought it into the
> foreground again for me. I think I'd like to actually get this solved now.
>
> I still think that splitting each backend into it's own package on PyPI is
> the right way forward (and I don't think that there was any disagreement
> with that). I also think that splitting these into different repositories
> is the right way forward (and there was some disagreement here). I don't
> think it really works well to have multiple, independently released, things
> living in the same repository.
>
> A big question though, was if we split things into multiple repositories,
> how does testing and such actually work. I've done some thinking on this,
> and here's what I think should happen:
>
>    - Everything not in a bindings or backend layer should move to
>    cryptography-core package which will be importable using import
>    cryptography.
>    - Each backend/binding will be moved to a cryptography-foo package
>    which will be importable using import cryptography_foo and
>    discoverable using entry points.
>    - A top level meta package called cryptography should be created which
>    just depends on cryptography-core and our default backends for
>    wahtever OS we're on.
>    - We keep the cryptography_vectors package which contains just the
>    vector files themselves.
>    - Move the tests into crytography.tests and add extras to make it so
>    you can do pip install cryptography[tests] to be able to run tests
>    against the installed cryptography.
>    - Move the bindings/backend specific tests (like
>    tests/hazmat/backends/test_commoncrypto.py) into their respective
>    cryptography-foo package.
>    - Ensure that all of the cryptography tests can run against any
>    installed backend.
>
> This splits up all of our packages into single units. Then for testing, we
> can set this up so that a change to the cryptography-core package runs
> the tox.ini from cryptography-core. This will install all of our
> "official" backends (openssl, commoncrypto, crypt32, whatever) and then run
> all of the tests against that, including the tests specific to those
> backends. This means that for changes to the core package, we get all of
> the same testing as we do now. Then for changes to a package like
> cryptography-openssl, we pull in cryptography-core, but not any of the
> other backends and run the tests for that backend. This means for
> backend/binding specific changes, we get faster results because we're not
> needlessly running the openssl tests for a change to commoncrypto.
>
> Now, one thing I glossed over above, is how we'd handle dependent pull
> requests, particularly when you want to make a PR to add a new interface to
> cryptography-core and implement that in cryptography-openssl and make
> sure it all actually works sanely before merging them. For this, I would
> have the tox.ini default to installing these packages from the master
> branches of each repository (or perhaps from PyPI?) and then I'd use the
> environment variable substitution support in tox.ini to allow an
> environment variable to force override where we install from for each
> dependency. Thus something like CRYPTOGRAPHY_CI_OPENSSL=git+
> https://github.com/dstufft/cryptography-openssl.git@mybranch#egg=cryptography-openssl
> tox -e py35 would, in the cryptography-core repository, test it against
> that repo/branch.
>
> The final bit of automation that would make this all work, is to use
> something similar to the bit where Github lets you link issues using
> something like closes #123 in a PR body, by allowing people to say
> something like tests against pyca/cryptography-openssl#123 in a PR, which
> our CI would then automatically set the CRYPTOGRAPHY_CI_OPENSSL variable
> to the branch/repository pointed to by the given PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/1522#issuecomment-188249756>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dstufft** [comment]
> multiple repos one is largely aesthetic IMO

How will we handle tagging releases? Options I can think of:

1. A release of any of the packages trigger a release of all of the packages, even if there is no code changes. We continue to tag releases as ``X.Y.Z``.
2. We allow separate releases, we now have to tag everything using something like... ``cryptography-core/X.Y.Z`` etc to retrofit a namespace onto the tags (since git assumes the repository is your namespace).

**Comment by alex** [comment]
Without substantial changes, I think it's unrealistic to expect these
packages to be independently releasable.

On Wed, Feb 24, 2016 at 8:36 AM, Donald Stufft <notifications@github.com>
wrote:

> multiple repos one is largely aesthetic IMO
>
> How will we handle tagging releases? Options I can think of:
>
>    1. A release of any of the packages trigger a release of all of the
>    packages, even if there is no code changes. We continue to tag releases as
>    X.Y.Z.
>    2. We allow separate releases, we now have to tag everything using
>    something like... cryptography-core/X.Y.Z etc to retrofit a namespace
>    onto the tags (since git assumes the repository is your namespace).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/1522#issuecomment-188257636>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
The first option is how we do it now. cryptography-vectors doesn't change in point releases but we release it anyway. Being able to do independent releases seems like a problem for the future.

I agree with @alex that we should split them in-repo first and go from there. That's all the user-visible work anyway.

If we're actually going to tackle this then `crypt32` might make sense as a package out of tree since we can use it as a test case for what it'd be like moving commoncrypto and openssl out. My gut feeling is that `commoncrypto` (and `crypt32`) wont drive new interfaces so having them out of tree won't be particularly painful, but `openssl` is a different story.

**Comment by reaperhulk** [comment]
Our current position has evolved into "backends were probably a mistake" so where they should live is "there should be only one".
