### ISSUE TITLE
Feature request: ECDH

### ISSUE THREAD

**Issue by dmbasso** [pyca/cryptography#1647]
The only primitive missing for ECIES is ECDH, and [it is easy to be implemented](https://gist.github.com/dmbasso/70f40041c40b003aca7c). Should it be a method of `EllipticCurvePrivateKey`?

**Comment by public** [comment]
Im working on this :-) Hopefully we'll have DH in 0.9 maybe with ECDH too 
or shortly after.

**Comment by dmbasso** [comment]
Great! Amazing work guys, thank you very much.

**Comment by simo5** [comment]
Any news on this ?
I'd like to have ECDH-ES support too for JSON Web Encryption (used by JWT)

**Comment by public** [comment]
Given the ridiculously slow progress I'm making on DH someone else might want to help. I'm happy to collaborate on aligning the APIs.

**Comment by bradmw** [comment]
Building off of #1957, Let's Encrypt now needs support for ECDH given recent changes to the ACME protocol (see [ACME Key Agreement](https://letsencrypt.github.io/acme-spec/#rfc.section.5.6)). Any more updates on the progress of this?

**Comment by simo5** [comment]
See #1882

**Comment by reaperhulk** [comment]
I'm going to tag this issue and @simo5's PR to the eleventh release milestone for now.

**Comment by bradmw** [comment]
Great! Thanks for the help!

I apologize, but when I commented earlier I forgot to mention the use of a key derivation function which also seems unsupported. I opened #2203 as that seemed more appropriate than tacking it on here.

**Comment by bmw** [comment]
Per @reaperhulk's request, dropping a comment on here to check the status of this issue. This is a feature that Let's Encrypt needs supported for our launch the week of November 16th.

**Comment by ronf** [comment]
I'm also planning to integrate this support into AsyncSSH as soon as it is available. I have my own pure Python implementation of EC for now that I was using for ECDH and ECDSA, but I recently added a shim in AsyncSSH to use PyCA"s OpenSSL ECDSA support instead while still using my implementation for ECDH, but it's broken up such that I should be able to easily switch to PyCA's ECDH just as soon as there are calls to create a keypair, export the public key, and compute a shared key from the local private & remote public key.

**Comment by simo5** [comment]
@ronf can you check out #1882 ?
I just rebased on top of current master, hopefully it still works.

**Comment by ronf** [comment]
@simo5 I grabbed this branch tonight and gave it a try, and I was able to both get the example in the docs to work and even interoperate with my own pure-Python implementation of ECDH.

The one thing that's missing from it right now is a way to encode the public key as an EC point byte string. That would look something like the byte 0x04 followed by an int.to_bytes() of the x & y values, but where each one is encoded using a byte length associated with the curve type. So, for instance, for SECP521R1, the x & y length would be 66 bytes each, as that's how many bytes it takes to hold a 521-bit number, making the overall encoded key string 133 bytes. I need that string representation for sending the public key around in SSH. I also need the reverse of this, taking in a curve and an encoded string in this format and turning it into an EllipticCurvePublicNumbers or public key value.

The other thing I need is the ability to get the final shared key from the agree() function as an integer value rather than a byte string. It look like if I use ECDHnoKDF, I can just call int.from_bytes() to get that, but I'm not sure if there's a better way.

**Comment by simo5** [comment]
Hi @ronf, although I see the usefulness of the conversions they belong to #1882, it seem you want to open an issue against the EC key feature to ask for those convenience conversions.

**Comment by ronf** [comment]
You're right -- the ability to create an EllipticCurvePublicNumbers from a point value encoded this way, or serialize it as a point value is useful for both ECDH and ECDSA. I'll file a separate issue about that.

In terms of the API for this, it was a bit non-intuitive to me to call exchange() and pass in the KDF and _then_ call agree() on that. I think it would flow better if you constructed an ECDH object out of your private key and the other side's public key first and then had methods that either returned the raw shared key or that took a KDF and returned an object that can be used to generate a key stream. This would eliminate the need for ECDHnoKDF.

I also think it would be useful to try and have a common (or at least similar) API that would work for both DH and ECDH. I'm still trying to figure out how to make DH work, though -- how do I do the equivalent of ec.generate_private_key() for DH? There's a generate_private_key() function on DHParameters, but that's an abstract class and I don't see anything in DHParameterNumbers to convert that into something concrete without passing in my own public and private numbers. I also don't see anything like the exchange() or agree() methods there to do the key exchange itself.

**Comment by ronf** [comment]
I just went back and did a search and I had added a comment about encoding/decoding from point strings in #1750 back in July, but the issue was already closed at that point and hasn't been re-opened. Should I post it again as a new issue?

**Comment by simo5** [comment]
Yes please open a new issue for the conversion stuff.
as for the ECDH API, it was agreed here to do it that way, you would have to ask @reaperhulk if he wants to reopen debate on the API.

**Comment by ronf** [comment]
@reaperhulk For what it's worth, here's the ECDH API I ended up writing:

```python
class ECDH:
    def __init__(self, curve):
        """Construct an ECDH private key"""

    def get_public(self):
        """Return the ECDH public key to send in the handshake"""

    def get_shared(self, public):
        """Return the shared key given the peer's public key"""
```

In my case, the return value of get_public() was a serialized EC point value byte string, and that same format was used to pass the public key into get_shared(). The return value of get_shared() was an integer (the x value of the point constructed by multiplying our private value with the peer's public point value).

Since we already have classes in PyCA for creating EC private & public keys, I can see the reason to just build on those once they have some way to serialize to/from an EC point byte string, as those keys can then be used for both ECDH & ECDSA. Having a simple method to construct a shared key from a private & public key still seem useful to me, though, and I'm not sure we even need to build the KDF in. That could be constructed separately once you have the shared key.

**Comment by kuba** [comment]
Friendly ping from Let's Encrypt team: any updates on this? :)

**Comment by reaperhulk** [comment]
@kuba https://github.com/pyca/cryptography/pull/2398 is in progress :)

**Comment by reaperhulk** [comment]
(If that PR doesn't do what you need let us know as soon as you can!)

**Comment by simo5** [comment]
#2398 superseded by #2420

**Comment by reaperhulk** [comment]
Done! #2427 (finally).
