### ISSUE TITLE
DSAParameter/EllipticCurve serialization

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#1750]
Do these have a PEM/DER representation? Do we care?

What just an EllipticCurve?

**Comment by reaperhulk** [comment]
I think the answer is that we don't care about this until/unless someone requests it. (An elliptic curve's serialized representation would be its generator G I suppose?)

**Comment by ronf** [comment]
With my asyncssh tool, I have a need for extracting parameters from keys like this, but not in DER or PEM format. For DSA, the raw integer values are needed (and available via DSAParameterNumbers/DSAPrivateNumbers/DSAPublicNumbers). I haven't tried to use the EC implementation in PyCA yet, but what I'd need there is a "point" value encoded as an octet string. Typically, this would not be the G value, but rather Q which is d times G, where d is the private key and Q is the public key.

The encoding of the point values into octet strings is described in http://www.secg.org/sec1-v2.pdf in section 2.3.3. This encoding is used by PKCS#1/PKCS#8 DER and PEM encoding of EC keys, as well as by SSH (with its own encoding of strings and integers replacing DER/PEM).

There is one case where G itself is also encoded in this "point" form, and that's when the EC domain parameters are encoded directly rather than by curve name in a PKCS#1/PKCS#8 key.
