### ISSUE TITLE
InvalidToken exception appears twice

### ISSUE THREAD

**Issue by Xof** [pyca/cryptography#1818]
The InvalidToken exception is defined twice: in fernet.py and in exceptions.py. Just following the docs, it's very easy to catch the wrong one, and it's not clear there's any utility in having both of them.

**Comment by reaperhulk** [comment]
This is definitely a bug, thanks for the report.

**Comment by reaperhulk** [comment]
The `cryptography.exceptions.InvalidToken` is meant for HOTP/TOTP, but since it's the same class name as `cryptography.fernet.InvalidToken` this is super confusing. We've mostly stopped adding things to `cryptography.exceptions` in favor of moving exceptions to live in the same modules that raise them, so maybe we need to move this (and consider renaming it?) and deprecate the old location.

**Comment by Xof** [comment]
As a  workaround, would it make sense for `exceptions.py` to import 'cryptography.fernet.InvalidToken` instead of defining its own? Backwards-compatible, and it makes them the same class.

**Comment by sbuss** [comment]
Note that #1842 was replaced by #1848, and this ticket has been resolved.

**Comment by lindhe** [comment]
May I suggest for future improvements, to migrate away from having exceptions both in `cryptography.exceptions` and `cryptography.fernet`? This took me some time to figure out...
