### ISSUE TITLE
Compiling against different OpenSSL more complicated than in our docs

### ISSUE THREAD

**Issue by hynek** [pyca/cryptography#2006]
Since version 7, pip auto-wheels stuff caches it somewhere.  That usually *awesome*.

But it brings problems too.  So I’ve spent an hour yesterday trying desperately to recompile cryptography against my homebrew’s OpenSSL and I’ve failed.  In the end I `pip install`ed my git checkout.

I kept deleting stuff from my wheel house, tried to find caches but nothing.  It always pulled it out of nowhere and `-v` didn’t help either.  I’m gonna claim that if I’m too asinine to get this done, other people are likely too.

This morning I found it out with the help of dtruss (concretely with it complaining, that I don’t own `/Users/hynek/Library/Caches/pip/http` b/c dtruss runs as root.  So I killed all wheels there and got finally my juicy 1.0.2a.

We need to update our docs in this regard, this is madness.  Does pip have some `--force-recompile` option I’ve missed?  If not, that should be filed there too…

cc @dstufft

**Comment by dstufft** [comment]
There is no ``--force-recompile`` option, but there should be.

**Comment by Commod0re** [comment]
I had an issue with this the other day too, that started as a new feature in Tox which requires explicitly listing any environment variables you don't want to be scrubbed.

pip has a `--no-cache-dir` option that seems to work (this was causing an exception to be raised with the version of pip that I had installed when I tested it the other day, but I tried it again just now and it looks to be working)

**Comment by glyph** [comment]
@hynek - one trick you can use in the future is, in one terminal, `bash -c 'echo $$; read; exec <program>`, in another terminal, `dtruss -p <pid>`, then hit enter in the first terminal again.

**Comment by dracos** [comment]
Just to add key words that might help someone in future as this bit me also today – if you get something like "Symbol not found: _CRYPTO_malloc_debug_init" when trying to use cryptography, because you forgot to use the [magic incantations](https://cryptography.io/en/latest/installation/#using-your-own-openssl-on-os-x) when pip installing (or in my case, running tox) and using MacPorts, then as above you need to clear the wheel from your cache (in my case Library/Caches/pip/wheels/.../*cryptography* otherwise you keep on getting the broken wheel no matter what you think you've deleted elsewhere...
