### ISSUE TITLE
Not possible to create 256 bit padding

### ISSUE THREAD

**Issue by sirex** [pyca/cryptography#2159]
Currently [Fernet requires](https://cryptography.io/en/latest/fernet/#cryptography.fernet.Fernet) 32-byte key. In may case, the key is generated from user provided password.

In order to create 32-byte key I use [PKCS7 padding](https://cryptography.io/en/latest/hazmat/primitives/padding/#cryptography.hazmat.primitives.padding.PKCS7), but max block size is 31-bytes.

I guess this is an error, and [following code](https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/primitives/padding.py#L33):

```python         
if not (0 <= block_size < 256):
```

Should be replaced to:

```python         
if not (0 <= block_size <= 256):
```

Isn't it?

**Comment by wbond** [comment]
From https://github.com/fernet/spec/blob/master/Spec.md it appears Fernet uses AES 128, which means it has a 128 bit block size. 128bits of the key is used for encryption and 128 bits for HMAC. Source: https://github.com/fernet/spec/blob/master/Spec.md#generating

**Comment by schlenk** [comment]
Does not sound like a smart idea to pad a key with trivially guessable data.

If you have user input and need a longer key, use a KDF to get one.

PKCS#7 spec (in RFC 2315) has this wording in 10.3 Note 2:

     This padding method is well-defined if and only if k < 256;
     methods for larger k are an open issue for further study.

So this is probably as designed and not a bug.

**Comment by sirex** [comment]
Currently I use this.

```python
def password_to_fernet_key(password: str) -> bytes:
    if len(password.encode('utf-8')) > 30:
        key = hashlib.sha256(password.encode('utf-8')).digest()
    else:
        # Since PKCS7 does not accept 256 block size, I had to use 248 and
        # zfill(32) as a workaround.
        # See: https://github.com/pyca/cryptography/issues/2159
        padder = padding.PKCS7(248).padder()
        key = (padder.update(password.encode('utf-8')) + padder.finalize()).zfill(32)
    return base64.urlsafe_b64encode(key)
```

I guess, there is no need to use padding at all, just sha256 should be enough.

But still, it looks strange, that max block size for PKCS7 padding is 248 but not 256.

**Comment by sirex** [comment]
@saschpe ok, since `k < 256` is specified in RFC, then probably this is not a bug. Thanks, and I'm closing this issue.

**Comment by wbond** [comment]
@sirex I missed the part where you said you were trying to pad a password to turn it into a key!

As @schlenk mentioned, don't use a padding function to generate a key. PKCS#7 is designed to pad plaintext being fed to a block cipher to make sure the plaintext fills the whole block. It uses a set pattern so that the padding can be reliably removed once the ciphertext has been decrypted. This is not a property you want in your Fernet key. It will likely cause the HMAC key (second half of the 256 bits) to be one of a small set of values, thus effectively removing the authentication portion of the Fernet scheme.

To take user input and turn it into a key, you should be using a key derivation function such as HKDF, scrypt, bcrypt or (last choice) pbkdf2. See chapter 13 of [Crypto 101](https://www.crypto101.io/) for some more info.

**Comment by sirex** [comment]
@wbond thanks, I changed that to pbkdf2 (from Python's hashlib module).
