### ISSUE TITLE
Please add a password encrypt and salt algorithm.

### ISSUE THREAD

**Issue by futursolo** [pyca/cryptography#2224]
A secure password encrypt and salt algorithm is needed for this crypto library.

**Comment by reaperhulk** [comment]
@futursolo at the moment we support PBKDF2 for password hashing purposes, but we do recommend people use `scrypt` or `bcrypt` (not provided by us) if they can. We may eventually have support for other password hashing primitives but since OpenSSL is our primary backend at the moment we're limited to supporting what it supports.
