### ISSUE TITLE
pip install fails on OS X when using macports

### ISSUE THREAD

**Issue by kimvais** [pyca/cryptography#2284]
`env ARCHFLAGS="-arch x86_64" LDFLAGS="-L/opt/local/lib" CFLAGS="-I/opt/local/include" pip wheel .` results to a wheel that works, but `env ARCHFLAGS="-arch x86_64" LDFLAGS="-L/opt/local/lib" CFLAGS="-I/opt/local/include" pip install cryptography` uses a wheel from PyPy that does not work

**Comment by tdsmith** [comment]
OS X wheels for cryptography aren't published to PyPI but as of pip 7, pip builds, caches, and attempts to reuse wheels of prior builds, which is probably what you're seeing: https://pip.pypa.io/en/latest/reference/pip_install.html#wheel-cache

**Comment by reaperhulk** [comment]
This bug is triggered by the following:

* User using pip 7 attempts to install cryptography 1.0 on PyPy < 2.6. This creates a wheel that believes it is valid for all py2 installs due to a variety of unexpected interactions.
* User attempts to install cryptography on CPython 2.6/2.7 and pip uses the wheel cache to install the broken wheel.

The fix is to delete your wheel cache or use `--no-use-wheel` during the install. The former is obviously preferable. We are tracking the underlying issue that causes this in #2283.
