### ISSUE TITLE
constant_time fails to import in pypy

### ISSUE THREAD

**Issue by viraptor** [pyca/cryptography#2286]
I've got an environment with pypy 2.5.0 and cryptography 1.0.

After installation I'm trying:

    import cryptography.hazmat.primitives.constant_time
    ...
    ImportError: No module named cryptography.hazmat.bindings._constant_time

**Comment by viraptor** [comment]
Just noticed that compared to installation on cpython, I don't get the lines saying:

    generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'

**Comment by reaperhulk** [comment]
This issue is fixed in master (dupe of #2283, fixed in #2285). PyPy 2.6 is required, but prior to #2285 we didn't raise an error if you tried to use the older version. [This comment](https://github.com/pyca/cryptography/issues/2284#issuecomment-133038098) has some more detail about exactly what is going on.
