### ISSUE TITLE
Building on windows assumes MSVC

### ISSUE THREAD

**Issue by Naddiseo** [pyca/cryptography#2339]
The result of issue #2021 causes `/NXCOMPAT /DYNAMICBASE` to be appended when building on windows, even if using mingw, resulting in a failed build.

**Comment by reaperhulk** [comment]
Do you know of a way to detect which compiler is in use via distutils?

**Comment by Naddiseo** [comment]
Not sure if this is the best way of getting the compiler to be used:

```python

from distutils.ccompiler import new_compiler
from distutils.dist import Distribution

dist = Distribution()
dist.parse_config_files()
cmd = dist.get_command_obj('build')
cmd.ensure_finalized()
compiler = new_compiler(compiler = cmd.compiler)
if compiler.compiler_type == 'msvc':
	return ['/NXCOMPAT', '/DYNAMICBASE']
```

**Comment by dstufft** [comment]
I don't think there's going to be a better way than that... and I'm pretty sure that isn't a defined API so it may or may not change in the future (but probably won't because everything depends on random implementation details of distutils so it gets changed very infrequently).

**Comment by schlenk** [comment]
In theory mingw supports --dynamicbase as a linker option too, in practice it seems to be somewhat broken in various versions of binutils as far as the echo on the net goes.

**Comment by reaperhulk** [comment]
@schlenk would dropping these flags if we didn't detect msvc be problematic in any way? I'd like to allow mingw to work as long as it is easy (although we will continue to build and test exclusively with MSVC).

**Comment by schlenk** [comment]
@reaperhulk No, simply drop them if it is not MSVC. 

In fact, you can patch in those flags after building via editbin.exe, so even if mingw gcc or some other toolchain doesn't set it, those can be enabled later.

Just use something like this:

        subprocess.check_call([EDITBIN, "/DYNAMICBASE",  "/NXCOMPAT", filename])

to add it after building (which would also be an option, but i do not know the right tool to call instead of editbin for mingw).

It is just nicer to have the flags set right away.
