### ISSUE TITLE
SIGILL with static wheels on OS X

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2359]
@hawkowl reports an issue where using one of our static wheels results in a SIGILL. This appears to be due to arch targets (the machine it is crashing on is a Mac Mini running a Core 2 Duo -- predating AES-NI).

@tdsmith, do you happen to know offhand how the OpenSSL bottles are built for homebrew? I know they support AESNI, but it looks like they also properly support older CPUs? The wheels built against the bottled OpenSSL work properly while the universal build I did (`brew reinstall openssl --universal`) fails on older CPUs right now.

I have removed the two offending wheels from PyPI so users won't run into this problem, but it does mean when we resolve it we'll need to do a 1.0.2 to be able to upload wheels again.

Edit: I have also removed the python 3.5 wheel for OS X. It was built against the OpenSSL that was compiled for native arch as well, so users on core2duo would have gotten a SIGILL with it as well.

**Comment by tdsmith** [comment]
Homebrew normally optimizes for the build architecture with `-march=native` when packages are built from source. To build a library that should run on all Intel Macs, pass `--build-bottle` to install, which adds `-march=core2` to compiler invocations in superenv.

This doesn't influence the AESNI instructions since those appear in assembly code and not C but openssl seems to be smart enough to decide if it should use that code branch or not.

(You could do a 1.0.1.post1 release if you preferred!)

**Comment by reaperhulk** [comment]
Yep, `--build-bottle` fixes it as expected (and AESNI is indeed intact on platforms that support it, hooray). I've rebuilt it on our Yosemite builder and we can now safely build the proper wheels. I'll leave this issue open to remind me tomorrow that I should update our release docs to describe how we handle OpenSSL on Windows and OS X (and to document the `--build-bottle` requirement).

**Comment by reaperhulk** [comment]
Documented this in #2361
