### ISSUE TITLE
ffi.callback() causes SELinux execmem violation

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#2477]
The ffi.callback() wrapper uses libffi's closure API. Closures are build by generating and executing dynamic code at runtime. This is problematic because libffi creates memory mapped pages that are both writeable and executable at the same time. SELinux's memory protection prevents mmap() with PROT_WRITE | PROT_EXEC in order to mitigate buffer overflows and similar attack vectors.

The problem didn't show up earlier because cryptography hasn't used ffi.callback() much. In the past only the password callback made use of ffi.callback(). But recent versions of cryptography use ffi.callback() for CRYPTO thread locks and os.urandom engine. Now cryptography causes SELinux denials at import time. This causes trouble for applications like FreeIPA and OpenStack.
https://bugzilla.redhat.com/show_bug.cgi?id=1277224 https://bugzilla.redhat.com/show_bug.cgi?id=1249685

libffi has a new API that makes closures compatible with SELinux. The new API uses the same technologie as http://www.akkadia.org/drepper/selinux-mem.html with two file-backed MAP_SHARED memory mappings. Armin pointed out that the approach is problematic because MAP_SHARED mappings are also shared between parent process and all its forks. https://bitbucket.org/cffi/cffi/issues/231/writeable-memory-execution-execmem-with https://bitbucket.org/cffi/cffi/branch/ffi_closure_alloc

Armin and @glyph came up with a better solution https://bitbucket.org/cffi/cffi/issues/232/static-callbacks (WIP) The new solution is also faster. I will work on a PR when a version of cffi with the fix is available.

**Comment by glyph** [comment]
Just for the record, while I understand the situation here, I think we should have an eye towards the fact that this just enables a "security" configuration that prohibits JITing.  One of the major advantages of using CFFI is that Cryptography JITs nicely with PyPy, and I think ecosystem-wise we should be pushing people to use PyPy as much as possible so that when they publish benchmarks of "python" they are looking at the fast one.

What does someone do in these environments if someone wants to run a node.js application, for example, where no pure-interpreter runtime is available?
