### ISSUE TITLE
ARC4 should permit keys in range 40-2048 bits

### ISSUE THREAD

**Issue by eakret** [pyca/cryptography#2494]
ARC4 in this library is currently too restrictive on the key size. It should allow any key 5 to 256 bytes in length.

**Comment by reaperhulk** [comment]
This restriction was put in place because [RFC 6229](https://tools.ietf.org/html/rfc6229) only specifies vectors for 40, 56, 64, 80, 128, 192, and 256 bit keys. It is a project policy not to expose support for things we can't confirm are working properly via test vectors. There are two ways we can expand this:

* Find a pre-existing test vector set and use it
* Build one based on code that demonstrates multiple implementations agreeing on output. Examples of this can be seen in our docs (https://cryptography.io/en/latest/development/test-vectors/#custom-symmetric-vectors).

Is there a specific use case you have that requires key lengths outside the currently supported set?

**Comment by eakret** [comment]
I was replacing some preexisting code that was using PyCrypto with a 160-bit ARC4 key length.

I don't see any test vectors obvious in the PyCrypto codebase but it could be used to generate some and compared against golang then added to the ARC4 vectors in this library. Golang has a few test vectors (https://github.com/golang/go/blob/master/src/crypto/rc4/rc4_test.go) but nowhere near exhaustive of the possible key lengths.

**Comment by reaperhulk** [comment]
It looks like the simplest solution for this case is to avoid boiling the ocean and just generate some 160-bit test vectors (although the vector creation scripts could be structured to generate vectors for arbitrary key sizes). If you'd like to submit a PR for that I'll be happy to review it and we can potentially have this in the next release.

**Comment by alex** [comment]
Not for nothing, but I'd _strongly_ recommend moving to remove RC4 from
your application, it has a myriad of known weaknesses at this point.

On Fri, Nov 27, 2015 at 9:23 PM, Paul Kehrer <notifications@github.com>
wrote:

> It looks like the simplest solution for this case is to avoid boiling the
> ocean and just generate some 160-bit test vectors (although the vector
> creation scripts could be structured to generate vectors for arbitrary key
> sizes). If you'd like to submit a PR for that I'll be happy to review it
> and we can potentially have this in the next release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2494#issuecomment-160241574>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
Definitely -- it's worth noting that our support of ARC4 in cryptography is intended for legacy conversions and that once that is accomplished time should be budgeted to migrate to a modern cipher construction if possible.

**Comment by eakret** [comment]
Yeah. The use of RC4 in my application is only for compatibility with an old protocol. It's being replaced.
