### ISSUE TITLE
Expose 'signature' and 'tbs_crs_bytes' on CertificateSigningRequest.

### ISSUE THREAD

**Issue by rowland-smith** [pyca/cryptography#2498]
These properties, just like the recent additions to Certificate, are necessary for verifying the signature on a CSR.

**Comment by reaperhulk** [comment]
I'll put in a PR for this tomorrow since we've already done it for Certificate and CertificateRevocationList

**Comment by reaperhulk** [comment]
I have a PR basically ready for this but there's a bit of a nomenclature problem. Specifically [RFC 4211](https://tools.ietf.org/html/rfc4211) talks about this as a proof of possession and the ASN.1 declarations don't call the payload `tbs`. It is instead just `CertRequest` and the full structure is `CertReqMsg` which has the optional proof of possession.

So, should we name it `tbs_certrequest_bytes` for consistency with our API anyway? Additionally, since signature is *not* a required field we'll need to handle that case. Should we return None or raise an exception "No signature"? /cc @alex

**Comment by rowland-smith** [comment]
Paul, 

I used the cryptography CSRBuilder and generated a CSR, wrote the DER encoding to disk and dumped it with dumpasn1. It looks to me like you are currently supporting the PKCS#10 format of a CSR, namely CertificationRequest, encapsulating CertificationRequestInfo, and NOT the PKIX CRMF.

	https://tools.ietf.org/html/rfc2986#section-5 <https://tools.ietf.org/html/rfc2986#section-5>

Is this correct?

**Comment by reaperhulk** [comment]
You are quite correct. As your link points out, `certificationRequestInfo` is the `tbs` payload. The RFC does note that an equivalent construction would be to call it `toBeSigned`, so I guess I'm okay with naming it `tbs_certrequest_bytes` unless someone has a better proposal?

**Comment by rowland-smith** [comment]
Thanks a bunch guys!
