### ISSUE TITLE
Verify signature created by cryptography using openssl shell?

### ISSUE THREAD

**Issue by chaos-git** [pyca/cryptography#2679]
We've been using cryptography and it turns out to be a great library. We were trying to create a signature on a 64bit linux instance then verify the signature on an ARM arch instance. Right now we're having difficulty getting cryptography to work on the ARM instance. I won't go in to details on that here, but we're working on it.

In the mean time, is it possible to verify a signature using openssl via shell? Would you know how to verify the signature using openssl if the signature were created like this:

```
def generateSignature(private_key, data):
   signer = private_key.signer(
     padding.PSS(
       mgf=padding.MGF1(hashes.SHA256()),
       salt_length=padding.PSS.MAX_LENGTH
     ),
     hashes.SHA256()
   )
   signer.update(data)
   return signer.finalize()
```
Any help would be appreciated.

**Comment by reaperhulk** [comment]
You'll probably be able to do it with something like:

```openssl pkeyutl -verify -pubin -inkey pubkey -sigfile sig -pkeyopt rsa_padding_mode:pss -pkeyopt rsa_pss_saltlen:-2 -in datasigned.txt```

You can find a bit more docs on this here: https://www.openssl.org/docs/manmaster/apps/pkeyutl.html

Note that since it's pulling in a file to verify the signature it may be hashing a trailing newline or something else weird so you may have to do something like add a `\n` to the payload being signed in cryptography.

I'm afraid this probably isn't much help, but good luck.

**Comment by alex** [comment]
This isn't really a cryptography bug so I'm going to close this issue.
