### ISSUE TITLE
Testing external backends

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2688]
While working on https://github.com/reaperhulk/cryptography-ring I ran into a problem with our current structure for out of tree backends. When testing an external backend you need cryptography, but you also need the tests that correspond to the version you install. We package those tests with the sdist, but we do not install them, so when a tool like pip/tox installs the dependency you can't use the tests. As a workaround you can clone our git repo and install from there, but that's pretty ugly.

One solution to this would be to move the tests into `cryptography.tests`. Another would be to create a `cryptography-backend-tests` package like `cryptography-vectors` and allow it to be installed separately.

cc @glyph @dstufft as I know they've got opinions on this.

**Comment by glyph** [comment]
I think we have opposite opinions :).

But: my take is that of course the tests should be part of your package.  Certainly you should never have tests in a package named "tests" because that precludes even the *possibility* of running them in the same process as another test package to test interactions.  The other option is to have a `cryptography_tests` package that can be separately installed.

Given the relative... intensity... of the Cryptography test suite, perhaps it would be best to have `tests/` as a directory similar to `src/` rather than a package, and then a `cryptography_tests` with its own `setup.py` so you can install it separately.

**Comment by dstufft** [comment]
I generally don't install tests because I don't see much utility in it. I suggested this to @reaperhulk earlier though because in this specific case I do see utility in it, particularly if we ever get to a point where all backends are external. I don't have a large preference for whether it should be ``cryptography.tests`` or ``cryptography_tests``.

**Comment by alex** [comment]
In retrospect, backends in their entirety may have been a bad idea, further literally no one has ever writen an external backend.
