### ISSUE TITLE
symmetric cipher ability to change/update key

### ISSUE THREAD

**Issue by sebastiandev** [pyca/cryptography#2878]
Having to set the key in advance for the algorithm is fine when dealing with manageable sizes, but if one needs to encrypt hundres or thousands of megabytes with OTP, then we need to be able to update the key while encrypting. 
If you see how [botan](http://botan.randombit.net/manual/lowlevel.html#symmetrically-keyed-algorithms) handles that, it lets you set the key that's is going to be used in the block encryption. Then one would update the key by chunks as it gets consumed, most probably feeding it from a file.

Would this be possible to implement for the current backends?

**Comment by reaperhulk** [comment]
You could relatively easily write some code that would call update until a predetermined limit was hit, close the existing context, and create a new cipher context and continue to process data. Since our cipher contexts return bytes you could buffer them/write to disk/write to a network socket as you saw fit.

I'm interested in why you want to do something like this though. Most modes of operation don't really need re-keying until 2**(n/2) blocks have been processed (caveat: assuming proper nonce/IV generation). Hundreds or thousands of megabytes is not a particularly large quantity. Even GCM is specified for 2**39 − 256 bits per (key, IV) (~64GB) with no stipulation for maximum encryption under a single key (although the 2**(n/2) rule of thumb is still relevant and IV reuse is catastrophic).

**Comment by sebastiandev** [comment]
Ok, so initially i could just use several contexts (ciphers at the cryptography level) one for each symmetric key chunk. That shouldn't be a problem.

I didn't know that you could use a 256 key for a 64gb file and still be secure.  I assume this is possible because of the iterations/permutations and stuff done on the key, but the approach of one data block - one key block would still be better, right? like a true OTP. Although that brings the issue of huge keys, of course.
I used to work on a cryptography app where each block was encrypted using AES with CBC mode updating the key on each block.

thanks

**Comment by alex** [comment]
I'm not sure I understand what the issue is here, can it be closed?

**Comment by reaperhulk** [comment]
Yep, I think so. (As always, reopen/comment if you feel this is in error)
