### ISSUE TITLE
default_backend() always fails on Alpine Linux

### ISSUE THREAD

**Issue by zet4** [pyca/cryptography#3060]
Hello, I have Jupyter instance running on Alpine Linux on one of my servers where I often test code before putting it into my  application as it resembles my deploy environment pretty close.
Today I wanted to try out cryptography.io in this very instance but sadly I ran into issue:

https://gist.github.com/ZetaHunter/38f238dcecf2fabaa5686f0e2d2cf6ae

I've reinstalled the library several times with no evident changes.

Edit:

I found that using openssl backend directly instead of default_backend() works just fine, it would still be nice if this could be resolved.

**Comment by reaperhulk** [comment]
Thanks for the report. Typically problems with resolving backends for multibackend are related to setuptools, but it appears from your logs that you have a new enough version. If you've still got an environment that replicates this behavior could you run this code for me and provide the output?

```python
import pkg_resources
print([ep.resolve() for ep in pkg_resources.iter_entry_points("cryptography.backends")])
```

On a working instance it should look something like:

```[<cryptography.hazmat.backends.openssl.backend.Backend object at 0x10ee804d0>]```

On a Mac you'd see 2 entries instead of one, but that shouldn't occur here obviously.

**Comment by ZetaHunter** [comment]
Yeah I just got an empty array and nothing else.
I did make another gist with updated notebook, though as its empty array idk if its any point.
https://gist.github.com/ZetaHunter/b2e8ba2b12ff46442673df7c980f93d8

**Comment by reaperhulk** [comment]
😞 @dstufft do you have any idea what could cause this?

**Comment by cemsbr** [comment]
default_backend() is not working for me, in ArchLinux. Should it be another issue? I'm using version 1.4 and reinstalling didn't work. @ZetaHunter , could you provide the code of the workaround you are using, please? I couldn't find it in the docs.

**Comment by ZetaHunter** [comment]
@cemsbr I simply manually imported openssl backend, and used `openssl.backend` 
```py
from cryptography.hazmat.backends import default_backend, openssl
BACKEND  = openssl.backend
```
However my project gained some specific needs that cryptography didn't satisfy (scrypt, friendly totp, jwt's) so I moved on since.

**Comment by reaperhulk** [comment]
I've just built an alpine 3.4 env in docker and everything appears to be working properly. For reference here's what I did:

```
apk update
apk add python
apk add python-dev
apk add openssl-dev
apk add libffi-dev
apk add gcc
apk add musl-dev
apk add py-pip
pip install ipython
pip install cryptography
```

At this point the code in https://github.com/pyca/cryptography/issues/3060#issuecomment-236110704 worked.

I'm going to go ahead and close this since it's working as expected in the latest alpine. If others run into this problem with a fully up-to-date release please open a new issue.
