### ISSUE TITLE
Add function to set random serial number to X509 certificate

### ISSUE THREAD

**Issue by socketpair** [pyca/cryptography#3077]
Good way -- is to use `random.randint(1, (159<<1) -1)` to set serial number. One question is bother me -- is it good to use undefined Python random implementation comparing to cryptographically strong random?

See https://en.wikipedia.org/wiki/Predictable_serial_number_attack
and http://www.win.tue.nl/hashclash/rogue-ca/

**Comment by reaperhulk** [comment]
It would not be safe to use random.randint because underneath the covers this uses a single shared instance of Mersenne Twister, which can be attacked to predict all future output values.

`int.from_bytes(os.urandom(16))` would be a reasonable way to generate it (serials are allowed to be up to 20 octets by RFC 5280, but the number must be positive and ASN.1 integer positive encoding requires a leading zero byte if the high bit is set, so the max bytes you can safely encode is 19).

**Comment by socketpair** [comment]
maybe `int.from_bytes(os.urandom(20)) >> 1` ?
