### ISSUE TITLE
Building 1.1.X with openssl 1.0.2g

### ISSUE THREAD

**Issue by tbreeds** [pyca/cryptography#3179]
Is there any chance we can get a 1.1.3 release with backport of the various build fixes for 1.0.2g?

We'd like to be able to use 1.0.2 but can't upgrade to the 1.2 branch

I can confirm the 1.1.2 + https://github.com/pyca/cryptography/pull/2755/commits/64c9d893c3748e962d01a935625c58610826f23c builds and passes tests:

`= 79000 passed, 978 skipped in 192.34 seconds =`

I'm happy to submit a pull request if that's acceptable

**Comment by reaperhulk** [comment]
What's preventing an upgrade to the latest version? We haven't historically done backports, but if there's a compelling reason we may be willing to issue an `sdist` only release?

**Comment by tbreeds** [comment]
Thanks for the reply.

This is in the context of OpenStack (specifically the liberty branch)  liberty is getting near the end of life and we're a reasonably risk adverse team so the impact of upgrading to 1.2 is considered a little risky.  There isn't anything specifically problematic that we can identify it's more taking nearly 250 commits.  At the same time we'd like to enable security sensitive consumers to use the newer OpenSSL.

I totally understand if your answer is "no" but I thought it was worth asking the question.

https://review.openstack.org/#/c/364249/

**Comment by reaperhulk** [comment]
I don't see a way to do this without backporting quite a few other patches to allow our CI to actually run and verify. Additionally, 1.1.x supports a few distributions (like CentOS 5) that we no longer have in our jenkins cluster at all. With those challenges I'm extremely reluctant to issue a release where we can't verify it works as expected for users who may have pinned `cryptography < 1.2` 😢. I think we're going to have to say no, sorry.

Just as a note, if your users want to patch it themselves, in addition to the one you specified on 1.0.2j there is another patch they'll need to apply: https://github.com/pyca/cryptography/commit/8b8d51b752729f7237bb51274ccf158cbb4cfce0 . Unfortunately that won't apply cleanly since we've made other changes since then. The relevant change is that https://github.com/pyca/cryptography/blob/1.1.x/src/_cffi_src/openssl/ssl.py#L631 needs to only be true if OpenSSL <= 1.0.2i when OPENSSL_NO_COMP is set (and it's not LibreSSL).

@alex if you disagree feel free to reopen.
