### ISSUE TITLE
Support for UniqueIdentifier (2.5.4.3) in Subject

### ISSUE THREAD

**Issue by jmcfcosta** [pyca/cryptography#3197]
Hi,
How could I add an UniqueIdentifier field to a subject? Correct me if I'm wrong (I've only started using your lib recently) but it doesn't seem to be supported - trying to fetch the subject in a certificate having it raises a "ValueError: Unsupported ASN1 string type. Type: 3".
NameAttributes only accept text values but in this case a unique ID will be encoded as a bitstring.
Could support for this be added in the future or at least someone give me directions for a (temporary) workaround?

Thanks.

**Comment by reaperhulk** [comment]
@jmcfcosta could you give us a sample certificate that contains a field like this?

**Comment by castillar** [comment]
I'm having a similar problem with trying to parse a certificate containing such an identifier and getting the same "ValueError: Unsupported ASN1 string type. Type: 3" error when asking for either subject or issuer (it's a self-signed root, so those should be the same value). Since the certificate is part of several public trust stores, I've attached it here for reference, in PEM format.

PyASN1 decodes the subject as 
"Name(componentType=NamedTypes(NamedType('', RDNSequence()))).setComponents(RDNSequence().setComponents(RelativeDistinguishedName().setComponents(AttributeTypeAndValue(componentType=NamedTypes(NamedType('type', AttributeType('<no value>')), NamedType('value', AttributeValue()))).setComponents(AttributeType('2.5.4.10'), AttributeValue(hexValue='1305436973636f'))), RelativeDistinguishedName().setComponents(AttributeTypeAndValue(componentType=NamedTypes(NamedType('type', AttributeType('<no value>')), NamedType('value', AttributeValue()))).setComponents(AttributeType('2.5.4.3'), AttributeValue(hexValue='131041435432204543432053554449204341')))))"
so it's decodable, and all of the other attributes (public_bytes, not_valid_before, not_valid_after), etc. are fine. It's just Issuer and Subject that seem to give it heartburn.

[7e206939cc5fa883635f64c750ebf5fda9aee653.txt](https://github.com/pyca/cryptography/files/558833/7e206939cc5fa883635f64c750ebf5fda9aee653.txt)

**Comment by reaperhulk** [comment]
Okay, let's talk a bit about expanding the API to support this. Bit strings are obviously not text (although in the example @castillar provided the bit string is actually the ASCII text "SEC-830101-9V9", but that is definitely not a requirement). We could modify `NameAttribute` to allow it to take bytes and encode bit strings as byte strings, but I'm not clear on whether that's safe. Can bit strings be non-byte divisible lengths?

**Comment by alex** [comment]
Why did we originally make the API text only? Are bitstrings allowed by RFC 5280?

**Comment by castillar** [comment]
Per 5280, the only values permitted to be type "BIT STRING" are signatureValue, UniqueIdentifier, and subjectPublicKey, although the RFC actually just says the value is determined by the type. For the record, I'm not holding up the attached cert as an example of a _good_ thing, just that it's one I ran across that gives pyca heartburn right now. :)

Looking at the cert structure itself, it looks like it's just that first block, the "SEC-830101-9V9" that's encoded as a bitstring; all the others are printablestring. It appears from [other discussions](http://openssl.6102.n7.nabble.com/invalid-x500UniqueIdentifier-bitstring-in-openssl-td4726.html) [on the OpenSSL mailer](http://openssl.6102.n7.nabble.com/build-CSR-with-x500UniqueIdentifier-td43600.html) that X.500 identifiers are generally encoded as a bitstring, since they contain a GUID-like identifier that serves to differentiate otherwise identical objects. RFC5280 doesn't seem to have anything to say either way about that type of identifier in Subject or Issuer.

**Comment by alex** [comment]
Ugh, I didn't realize `AttributeValue` was an `ANY`, I assumed it was a `DirectoryString`.

**Comment by reaperhulk** [comment]
`NameAttribute` was an attempt to simplify `AttributeTypeAndValue`. Maybe it needs to get more complex and allow encoding of the type instead of assuming the python type of the value is sufficiently expressive.

```python
class NameAttributeType(enum.Enum):
    DIRECTORYSTRING = 0
    BITSTRING = 1


class NameAttribute(object):
    def __init__(self, oid, value, type=NameAttributeType.DIRECTORYSTRING):
        self._oid = oid
        self._type = type
        self._value = value
```

Of course this still doesn't allow the user to pick their ASN.1 encoding type. Instead, cryptography will do something backend specific (in the case of the default above in OpenSSL we'd encode it all utf8string). So it makes it nearly as complex as just constructing your own ASN.1 DER but without the actual power. I don't really like that.

We could also choose to special case the uniqueIdentifier OID like we have for countryName (where we explicitly check to ensure it's a 2 byte string). In this case we could explicitly allow bytes iff it's uniqueIdentifier, but that feels pretty confusing.

**Comment by reaperhulk** [comment]
I'm not sure how to implement encoding for this. We use `X509_NAME_ENTRY_create_by_OBJ` right now to generate our name entries when encoding and it can't properly handle x500UniqueIdentifier. I'm reluctant to support parsing and not encoding so we need a way to encode (which may be possible via some other OpenSSL knobs?) before we can move forward.

**Comment by reaperhulk** [comment]
Closing this one in favor of #3542 where we've had a bit more recent conversation. This might get done for the twenty first release. Current rough plan is for #3896 to merge, then I'll take over #3547 and the API will look something like:

```python
NameAttribute(SubjectOID.UNIQUE_IDENTIFIER, BitString(b"bytes", bit_length=32))
```

#3896 would also allow us to potentially have an API that looks more like:

```python
NameAttribute(SubjectOID.UNIQUE_IDENTIFIER, b"bytes", type=ASN1Type.BIT_STRING)
```

but I'm reluctant to go down that path since a byte string doesn't allow bit lengths that aren't modulo 8.
