### ISSUE TITLE
Linkcheck build doesn't run on jenkins

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#3220]
https://jenkins.cryptography.io/job/cryptography-docs-linkcheck/2308/console

**Comment by reaperhulk** [comment]
Locally I can make this fail whenever tox has to create a new virtualenv. It fails on that run, then succeeds subsequently. `docs-linkcheck inst` vs `docs-linkcheck inst-nodeps` in the output

**Comment by alex** [comment]
@reaperhulk that's consistent with what I'm seeing locally. A quick glance at the `tox` source doesn't make it obvious why that'd occur, but it was rather perfunctory

**Comment by reaperhulk** [comment]
Okay, looking into it this is the command that fails inside the tox venv:

`pip install /path/to/.tox/dist/cryptography-1.6.dev1.zip[test]`

When we try again it installs sans deps, which succeeds:

`pip install -U --no-deps /path/to.tox/dist/cryptography-1.6.dev1.zip[test]`

Which never installs the vectors (which are what failed in the first place). So it's just coincidence that it works by calling it twice.

None of this is the root cause, but maybe it will help the next person who wants to dig.
