### ISSUE TITLE
Proposal: Add alternative to Fernet that provides resilient storage

### ISSUE THREAD

**Issue by BjarniRunar** [pyca/cryptography#3285]
Hello! Thank you for cryptography!

I don't know if this is the right place to post this sort of thing, so feel free to close this if you'd rather your bug tracker wasn't cluttered up by random feature requests.

I was reworking the long-term storage crypto for Mailpile recently, and ended up *not* using the cryptography Fernet construct. I wanted to tell you why and propose a new feature which would have covered the use-case I have in mind.

In short, I didn't use Fernet, because Fernet builds upon AES-CBC and will as a result irrevocably lose entire files if a bit near the start gets flipped. For long-term storage I consider that to be a problem; security is important but if it reduces the long-term reliability of storage then it may not be a worthwhile trade-off. Far more users experience data loss and malfunctioning devices than are victims of hostile intrusions and theft. Consider crappy USB sticks, worn out SSDs, etc. etc.

I ended up rolling my own replacement storage format based on AES-CTR and an external MAC.

Would the cryptography project be interested in providing an alternative to Fernet which uses malleable crypto (AES-CTR or AES-GCM, or whatever you feel is appropriate)?  Ideally combined with error correction codes so the container can not only provide superior security, but also superior durability over unencrypted storage?

**Comment by reaperhulk** [comment]
We have a strong desire for more high level cryptographic constructs, but we have some pretty strict requirements around them. We need them to be well-defined with an official spec and test vectors at minimum, but ideally we don't want to invent them.

Your needs in this area are very specific so it would be challenging to compose a recipe that meets your requirements while still being generically useful. We've been talking about specifying a seekable authenticated encryption recipe for awhile, but that would be insufficient without an optional error correction layer (which would be tricky to implement safely and starts becoming the sort of problem you want a Real Cryptographer™ to heavily review).

So I guess this is a long-winded way of saying that we would like a recipe to fit your needs, but it's a non-trivial problem. I'm opposed to accepting any recipe that allows malleability (since it is generically an undesirable property), so the way forward is unfortunately the hard way.

**Comment by alex** [comment]
Personally I think this is overly niche to be included in cryptography itself.

**Comment by BjarniRunar** [comment]
I think it's a bit weird that providing a way to encrypt data for long term storage, that doesn't increase the odds of data loss, would be considered niche. Isn't that one of the main use-cases of crypto, to take data and encrypt it so you can safely store it (possibly for quite a long time) on someone else's computer (e.g. S3 or some other cloud)? How is that niche?

Crypto folks care deeply about some very obscure and rare attacks, but bitflips and data corruption, which are far more common for most users are somehow out of scope? Oh well. As you can imagine, I disagree with that.

But I think I already made my point and I don't have the resources to actually contribute code to this just yet - so thanks for your responses and your time! :-)
