### ISSUE TITLE
Receive error:/usr/bin/ld: duplicate expression `*' in version information while using my own openssl on ubuntu 14.04

### ISSUE THREAD

**Issue by hexucheng** [pyca/cryptography#3301]
I generate openssl.ld like this:
    
    OPENSSL_1.1.0C_CUSTOM {
        global:
            *;
    };

and execute commands to build openssl 1.1.0c as follows:

sudo ./config -Wl,--version-script=openssl.ld -Wl,-Bsymbolic-functions -fPIC shared
sudo make

but it interrupted by error:

/usr/bin/ld: duplicate expression `*' in version information

can someone tell me why ?

**Comment by reaperhulk** [comment]
For OpenSSL 1.1.0 you can get away without a version-script since the soversion is different than your distro. Just remove that. You should be very cautious when building your own OpenSSL though. For instance, it is unwise to actually install it into /usr/local where other applications may inadvertently pick it up. Instead you should be setting a prefix and openssldir.
