### ISSUE TITLE
Document openssl_version_number

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#3315]
https://cryptography.io/en/latest/hazmat/backends/openssl/

**Comment by DelboyJay** [comment]
Hi Alex, small thing and I could be wrong, but I think the function name is openssl_version_text. cryptography.hazmat.backends.openssl.backend.openssl_version_text() seems to work and returns "OpenSSL 1.0.2j  26 Sep 2016" for me. I have just downloaded cryptography V1.7 and run the command.
Thanks for the heads-up on this one. :-)

**Comment by reaperhulk** [comment]
Documenting this is fine, but it's a bad method for doing any sort of programmatic checks since it's just a string. I'll add `openssl_version_number` to return the integer release as well.

As an aside, this method is the first thing I ever contributed to cryptography! PR #48, the first of 1130 (and counting).
