### ISSUE TITLE
AES-CFB8: integer 3696558080 does not fit '32-bit int'

### ISSUE THREAD

**Issue by tokeefe** [pyca/cryptography#3324]
When I try to encrypt a very large file using AES-CFB8, I get the following error

```python
integer 3696558080 does not fit '32-bit int'
```

I'm using Python 2.7.12 64-bit (Miniconda 3.19.0) on CentOS 6.5 64-bit. Please refer to the following example code:

```python
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

s = <something big>
key = os.urandom(32)
init_vector = os.urandom(16)
backend = default_backend()
cipher = Cipher(algorithms.AES(key), modes.CFB8(init_vector), backend=backend)
encryptor = cipher.encryptor()
ct = encryptor.update(s) + encryptor.finalize()
```

**Comment by reaperhulk** [comment]
The underlying function here takes an `int` for length, which is why you're seeing the error. Any call to update with > 2 ** 32 bytes will cause this. Practically speaking calling `update` with `n` bytes of data means you'll need to have `n * 3` bytes of memory available, so I would strongly recommend splitting your calls to update (since this is a file you can could read it in chunks, encrypt in chunks, and write in chunks to another file).

We could try to make this a friendlier error, but I'm somewhat reluctant to do a length check on every update call.

**Comment by tokeefe** [comment]
Splitting calls to `update` was exactly what I needed. Sorry for the non-issue.
