### ISSUE TITLE
Apache subinterpreter Cryptography_pem_password_cb error 

### ISSUE THREAD

**Issue by ajmaddaford** [pyca/cryptography#3377]
After deploying https://github.com/ONSdigital/eq-survey-runner to AWS ElasticBeanstalk we started getting the error `extern "Python": function Cryptography_pem_password_cb() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0` on one of the instances. We terminated the instance but have the full logs.

We were running cffi 1.9.1 and cryptography 1.7.1 on 64bit Amazon Linux 2016.09 v2.3.1 running Python 3.4 with libffi-devel x86_64 3.0.13-16.5.amzn1 and OpenSSL 1.0.1k-fips 8 Jan 2015. 

We have re-added the Apache `WSGIApplicationGroup %{GLOBAL}` config fix for now, but can spin up a developer environment without it for further testing.

**Comment by reaperhulk** [comment]
Thanks for the report. It's possible we're somehow misusing this callback, otherwise we may have to hoist this last one into C as well.

**Comment by collisdigital** [comment]
Thanks @reaperhulk the work-around in Apache isn't great as it has a massive performance impact, essentially forces Apache to be single-threaded so we're really keen to resolve this one. If there's anything we can do to help just shout.

**Comment by tiran** [comment]
*sigh* I was worried that we might be running into some trouble with the last remaining CFFI callback. Why is cffi so strict about subinterpreters?

**Comment by reaperhulk** [comment]
I talked with Armin a bit at PyCon ZA about the general subinterpreter problem and he thought it was possible we were doing something wrong. I can't remember the details now though. @collisdigital we'll probably need you to test any potential fix we come up with -- is that something you can do this week?

**Comment by collisdigital** [comment]
Hi @reaperhulk we can try any fixes you have but unfortunately due to the nature of the problem; being multi-threading related; means that it inconsistently fails as we assume it is a timing issue. It's can actually go for days, weeks without occurring and then suddenly fails on startup 10 times in a row before vanishing again. So... we can deploy a fix but can't be sure it worked if nothing fails; helpful I know! Unless you have any ideas about how we could trigger this problem more consistently?

**Comment by reaperhulk** [comment]
Nope 😢, that's pretty much exactly why writing the fix is such a problem too.
