### ISSUE TITLE
Provide GCM tag value during finalization step when decrypting

### ISSUE THREAD

**Issue by GaretJax** [pyca/cryptography#3380]
Currently the GCM cipher mode requires the tag value to be passed in to the constructor when decrypting, but its value is not used until the finalization step. This is true for both the openssl and the commoncrypto backends.

In my use case, the data is structured as in `(iv, ciphertext, tag)`, which allows to treat the encrypted payload as a stream of data. The current API design prevents to decrypt the data by linearly reading from the input and requires it to be buffered in order to first get the tag from the end.

While I know that the decrypted output shall not be used before the finalization step, it is also true that allowing the tag to be passed in during the finalization step allows to avoid having to buffer the whole payload twice.

API wise, it would make sense to allow the tag to be passed to the `finalize` method. Currently, `InvalidTag` errors are raised only during the `finalize` call, so the main user-impacting changes would be the argument validation not occurring during initialization and decryptor construction, namely:
- https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/primitives/ciphers/modes.py#L166-L170
- https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/primitives/ciphers/modes.py#L175-L176
- https://github.com/pyca/cryptography/blob/a5865d9b630df7586785b683ed145b977ad7e0c4/src/cryptography/hazmat/primitives/ciphers/base.py#L109-L113

**Comment by reaperhulk** [comment]
If we want to add this capability while maintaining API compatibility we'll want to keep validation in the GCM constructor probably because current users would expect to catch the exception there. We'd just also allow `None`. However, right now the AEADCipherContext interface defines finalize as taking no arguments, so we'd need to alter that to take a tag with default `None`. Additionally, in at least the OpenSSL backend the concrete implementation of `CipherContext` and `AEADCipherContext` are the same class, so we'd probably need to split those apart.

It doesn't seem unreasonable to support this use case, but whoever decides to implement it will have a bit more work than it appears at first glance.

**Comment by phi-gamma** [comment]
Please have a look at #3421. Instead of adding an optional argument to
``finalize()`` I went with an explicit alternative ``finalize_with_tag()`` which
is only available for authenticated ciphers.

It’d be great if we could have this as it would match the options of other
crypto libraries.
