### ISSUE TITLE
EC Private Keys Are Incompatible With iOS/OS X Security APIs (support SECG serialization)

### ISSUE THREAD

**Issue by dimitribouniol** [pyca/cryptography#3487]
We are currently generating a `secp521r1` key as follows:
```python
private_key = ec.generate_private_key(ec.SECP521R1(), default_backend())
serialized_private = private_key.private_bytes(
    encoding=DER,
    format=TraditionalOpenSSL,
    encryption_algorithm=NoEncryption()
)
```

This turns up the following DER file:

```hex
3081DB02 01010441 1343B3C8 94ABD7D3 B2CD80C9 872667BB 45406FC4 E342CDAC
543C99AE 51382765 990DF5EF 1A0436BD 771E8F45 9B8DAE82 EBC101A7 DA084666
F1E718D2 F3F5722F A1A00706 052B8104 0023A181 89038186 000401B9 CB8E7F9F
C698CCAF 5E37A0A3 FF418566 6ABD9F9B ACF2B7F5 5F8785AD C3EA9848 FE29FD33
BC1DB969 158BC3AA 0F684AED BF542D19 B3BCB040 7EAAAD04 2ECA9B50 0109AC9E
F94383C3 CE2CCAFB 1F85289C C2C3153F 76018012 EC7B0E0E 8F29A375 01A3557B
EF5E77E0 24CC2A64 31506CAB E215A833 2E437348 64380564 98A8444A C5B6
```

From this, we get the following [ASN.1 tree](https://lapo.it/asn1js/#3081DB02010104411343B3C894ABD7D3B2CD80C9872667BB45406FC4E342CDAC543C99AE51382765990DF5EF1A0436BD771E8F459B8DAE82EBC101A7DA084666F1E718D2F3F5722FA1A00706052B81040023A18189038186000401B9CB8E7F9FC698CCAF5E37A0A3FF4185666ABD9F9BACF2B7F55F8785ADC3EA9848FE29FD33BC1DB969158BC3AA0F684AEDBF542D19B3BCB0407EAAAD042ECA9B500109AC9EF94383C3CE2CCAFB1F85289CC2C3153F76018012EC7B0E0E8F29A37501A3557BEF5E77E024CC2A6431506CABE215A8332E4373486438056498A8444AC5B6):

```asn1
SEQUENCE (4 elem)
    INTEGER 1
    OCTET STRING (65 byte) 13 43 B3 C8 94 AB D7 D3… (PRIVATE KEY)
    [0] (1 elem)
        OBJECT IDENTIFIER 1.3.132.0.35
    [1] (1 elem)
        BIT STRING (1064 bit) 00 04 01 B9 CB 8E 7F 9F... (PUBLIC KEY)
```

The problem begins when I extract these two octet strings and present them to the Security APIs on OS X and iOS. These APIs expect the raw octet strings as a concatenation of the public, then the private key, with no extraneous markers. However, it seems like these public and private keys are slightly malformed; the public key is prefixed with an extraneous `0x00`, while the private key is missing a byte (every one I've generated so far that has the missing byte has that byte set to `0x01`, but I can only guess what this value should be when the byte is missing… See (page 12 of SEC2)[http://www.secg.org/sec2-v2.pdf] for why I assume the leading digit might be a `0x01`).

From my (very limited) understanding of how SEC1 private keys are expected to be encoded, I would imagine that the private key must be 66 bytes long for 521-bit keys (521 bits == 65.125 bytes), while the public key must be 133 bytes long for 521-bit keys (same 66 bytes for x and y, plus a leading `0x04`).

This causes problems I can fix on the client side, but I'd obviously rather not need to loosely accept malformed keys if I don't need to. Is this something that falls under the domain of cryptography, or is it strictly an OpenSSL bug?

Maybe this is related? https://www.mail-archive.com/openssl-dev@openssl.org/msg37790.html

**Comment by h3smith** [comment]
The way iOS implements it in the keychain is, eh. Checkout https://github.com/DigitalLeaves/CryptoExportImportManager to import/export keys correctly.

**Comment by dimitribouniol** [comment]
Unfortunately, CryptoExportImportManager doesn't help when the goal is to import EC private keys, and doesn't change the fact that the keys do *look* malformed when compared to the spec.

**Comment by reaperhulk** [comment]
We output exactly what OpenSSL generates, but I'm not sure there's actually a bug here. The "traditional OpenSSL encoding" you've chosen is not a standardized spec and is just whatever representation OpenSSL felt like creating. Since OpenSSL is ubiquitous this makes it a de facto spec, but it's not necessarily documented or easily interoperable.

Private keys (and public keys) are at most the same number of bits as the order of the curve, but since they are not required to be the same.

You might try seeing if conversion to integer (via `private_numbers`) and then explicitly encoding them to octet string yourself (via `int.to_bytes` or cryptography's `utils.int_to_bytes` if you're on py2) is an easier path.

**Comment by dimitribouniol** [comment]
Thank you for clarifying what is happening under the hood. We will see where we can get using `private_numbers` :)

That said, since some APIs do specifically request SEC1 formatted EC keys, could `SEC1` be perhaps added (alongside `TraditionalOpenSSL` and `PKCS8`) as an explicit format that conforms to the [SECG](http://www.secg.org/sec1-v2.pdf) spec?

After inquiring about how to correctly deal with these keys on [Stack Exchange](http://crypto.stackexchange.com/a/45270/45632), it would seem that the only mismatch is a leading padding of `00` to match the private key's expected length, which is stated to be:
> The component privateKey is the private key defined to be the octet string of length `⌈log2 n/8⌉` (where n is the order of the curve) obtained from the unsigned integer via the encoding of Section 2.3.7. (Page 109)

For a 521-bit key, it seems this would be `⌈521/8⌉` = `⌈65.125⌉` = `66` bytes, so simply padding the left side with `00` as necessary should suffice to meet the spec and make most non-OpenSSL APIs happy :)

**Comment by reaperhulk** [comment]
A `SECG` serialization type would be fine by me in principle!

**Comment by reaperhulk** [comment]
Would you happen to have any links to documentation from Apple re: how to load EC keys?

**Comment by davidben** [comment]
The "traditional OpenSSL" format is the SECG format. They just had a bug and serialized the private key wrong. https://github.com/openssl/openssl/commit/30cd4ff294252c4b6a4b69cbef6a5b4117705d22

That fix is in 1.0.2b and 1.1.0.

(Though it looks like 1.0.2 is missing https://github.com/openssl/openssl/commit/fe56d8e8a3665dc7e6784e0c170f790e6df8153f, so it's still sized wrong for curves where the prime and order have different bit lengths. But their bit lengths are the same for all commonly-used and most uncommonly-used curves, including secp521r1.)

**Comment by dimitribouniol** [comment]
@reaperhulk Sorry for the lack of correspondence. Here is some Security.framework code that loads the key from a byte string (wrapped in `NSData`):
```objc
NSError *keyError = nil;
NSDictionary *params = @{
                         (id)kSecAttrKeyType: (id)kSecAttrKeyTypeECSECPrimeRandom,
                         (id)kSecAttrKeyClass: keyClass,
                         (id)kSecAttrKeySizeInBits: keySizeInBits,
                         };
    
SecKeyRef key = SecKeyCreateWithData((__bridge CFDataRef)asn1Data, (__bridge CFDictionaryRef)params, (CFErrorRef *)(__bridge void *)keyError);
```

[Apple's documentation](https://developer.apple.com/documentation/security/1643701-seckeycreatewithdata?language=objc) is unfortunately limited in this regard, though the updated documentation is a bit more helpful:
#### `<Security.framework/SecKey.h>`
```
/*!
    @function SecKeyCreateWithData
    @abstract Create a SecKey from a well-defined external representation.
    @param keyData CFData representing the key. The format of the data depends on the type of key being created.
    @param attributes Dictionary containing attributes describing the key to be imported. The keys in this dictionary
    are kSecAttr* constants from SecItem.h.  Mandatory attributes are:
     * kSecAttrKeyType
     * kSecAttrKeyClass
    @param error On error, will be populated with an error object describing the failure.
    See "Security Error Codes" (SecBase.h).
    @result A SecKey object representing the key, or NULL on failure.
    @discussion This function does not add keys to any keychain, but the SecKey object it returns can be added
    to keychain using the SecItemAdd function.
    The requested data format depend on the type of key (kSecAttrKeyType) being created:
     * kSecAttrKeyTypeRSA               PKCS#1 format, public key can be also in x509 public key format
     * kSecAttrKeyTypeECSECPrimeRandom  ANSI X9.63 format (04 || X || Y [ || K])
 */
```
(Needless to say, previous versions were not as helpful in specifying that `SEC1` format was actually `ANSI X9.63 format (04 || X || Y [ || K])`...)

**Comment by reaperhulk** [comment]
Okay, between OpenSSL's serialization being SECG and the SecKey documentation noting that it supports standard uncompressed point serialization (which we support in 2.5 via UncompressedPoint and in earlier versions via the now deprecated encode_point) I think this should all work now.

**Comment by owlstead** [comment]
Note that the initial description of the "bug" is rather incorrect. Of course, the private key must be 66 bytes as indeed ceil(521 / 8) = 66. Since I2OSP needs to be used to generate it, any leading 00 bytes must be present. The first byte can only have value 00 or 01 as 521 % 8 = 1, i.e. only one bit can be set or the private value is larger than the key size, and that's of course impossible. Fixing this bug means that you don't just correct one byte: there is a 1 in 512 chance that two bytes are missing (times 256 for 3 bytes missing etc). Hopefully this got fixed correctly.

As for the public key: the first byte set to `00` simply indicates that no bits should be pruned from the bit string that follows. If the value that is encoded consists of bytes (e.g. an uncompressed point) then this byte should always be set to `00`. In other words: the public key is correct as the `00` byte is **not** part of the public key value. Of course, the parser that generated that output should not print out the `00` as if it was part of the value. 1064 bits is 133 bytes - 1 + 66 + 66 - so yeah, all data seems to be present. Apparently the public key does use I2OSP for the X and Y values, so the function must be present.

**Comment by Craz1k0ek** [comment]
For those interested, this is some code that makes it possible:

    import base64
    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives.asymmetric import ec
    
    
    def pub_serialization_x963(pub: ec.EllipticCurvePublicKey) -> bytes:
        prefix = bytes.fromhex('04')    # Prefix used in X9.63 standard.
        
        x = pub.public_numbers().x
        x = x.to_bytes((x.bit_length() + 7) // 8, 'big')
        
        y = pub.public_numbers().y
        y = y.to_bytes((y.bit_length() + 7) // 8, 'big')
        
        return prefix + x + y
    
    
    def pk_serialization_x963(pk: ec.EllipticCurvePrivateKey) -> bytes:
        pub = pub_serialization_x963(pk.public_key())
        
        k = pk.private_numbers().private_value
        k = k.to_bytes((k.bit_length() + 7) // 8, 'big')
        return pub + k
    
    
    pk = ec.generate_private_key(ec.SECP256R1(), default_backend())
    
    x963_pk = pk_serialization_x963(pk)
    x963_pub = pub_serialization_x963(pk.public_key())
    
    print(base64.b64encode(x963_pk).decode())
    print(base64.b64encode(x963_pub).decode())

**Comment by reaperhulk** [comment]
You can do the public key component of this serialization using:

```
pk.public_key().public_bytes(
    serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint
)
```

We don't have a method of serializing just the private value without your workaround though.

**Comment by davidben** [comment]
The code sample in https://github.com/pyca/cryptography/issues/3487#issuecomment-571173267 is incorrect and will fail probability depending on the curve. It has the same bug as in this issue (the private key needs be padded up to the group order) plus a new one (x and y coordinates of the public key need to be padded up to field size). This is especially problematic when concatenating because, without the padding, the encoding is ambiguous.

Extracting private keys as Python integers is also not constant-time. See #4235.

**Comment by Craz1k0ek** [comment]
I would like to point out that the field size will be calculated correctly, as the `to_bytes` function will automatically prepend zeroes when required. 

As for your private key issue, it's still an open issue, therefor making this the best shot for exporting it in X9.63 format I guess? I however have made some minor changes in the meantime. I will update in a bit.

**Comment by davidben** [comment]
At the time I made the comment, the length passed to `to_bytes` as computed as `(x.bit_length() + 7) // 8`, etc., which is not the field size. Glad to see you've since fixed it, though note that the public key coordinates are field elements, while the private key is a scalar (number modulo the group order). These are *not* the same modulus.

[Hasse's theorem](https://en.wikipedia.org/wiki/Hasse%27s_theorem_on_elliptic_curves) implies they are close, but that bound doesn't quite guarantee the same bit or byte length. I vaguely recall there being some uncommon named curves where the byte lengths indeed differ, but I'm not sure which one off-hand or whether cryptography.io supports any of them.

Looks like `key_size` will give you the size of the scalar. I don't see a corresponding constant for the field size, but better to use the provided point encode and decode functions anyway.
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.key_size
