### ISSUE TITLE
RFC 5649 support

### ISSUE THREAD

**Issue by PeterHamilton** [pyca/cryptography#3791]
RFC 3394 (AES Key Wrap) was added a while back. I'd like to request support for RFC 5649 (AES Key Wrap with Padding), since it builds off of RFC 3394. It looks like OpenSSL handled this back in 2015:

https://rt.openssl.org/Ticket/Display.html?id=3675&user=guest&pass=guest

Is this feasible for cryptography in the not-too-distant future?

Thanks,
Peter

**Comment by reaperhulk** [comment]
Our AES KW implementation actually doesn't use OpenSSL due to historical bugs in implementation (although now that we support 1.0.1+ only we could probably drop that code). That said, adding support this should be straight forward. Out of curiosity, can you share your use case?

**Comment by PeterHamilton** [comment]
Huh, I thought the AES and cipher functionality was backed in general by the OpenSSL backend. My mistake.

I'm working on adding key wrapping and key derivation support to PyKMIP and one of my requirements includes support for RFC 5649, given its improved flexibility with key sizes. RFC 3394 works as a stopgap for now, but I figured I'd ask to see if you were willing to add 5649.

**Comment by reaperhulk** [comment]
Sorry, my previous statement was somewhat confusing. We do use the AES functionality from OpenSSL, we just don't use its AES keywrap APIs (we compose our own out of the AES primitive). At any rate, that's not hugely relevant in this case. I'll go ahead and tentatively put this in the next release milestone.

**Comment by PeterHamilton** [comment]
Ok, that makes sense regarding OpenSSL. Thanks for considering the feature.

**Comment by reaperhulk** [comment]
It looks like RFC 5649 support was added in OpenSSL 1.1.0. Since we now ship manylinux1 wheels in addition to our mac and windows wheels we could just use that implementation (all our wheels are 1.1.0), but it does mean users on non-manylinux1 compatible distributions or alternative OSes will not be able to use it. Alternately we could implement it ourselves. I'll think a bit more on that, but we'll definitely need to add NIST CAVP's keywrap test vectors (the `KWP` files in http://csrc.nist.gov/groups/STM/cavp/documents/mac/kwtestvectors.zip are AESKW with padding)
