### ISSUE TITLE
Making passing a backend optional

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3881]
We should make backends optional since 99.99% of the time the user wants the default.

**Comment by FranklinYu** [comment]
Any progress? How about beginning with making the backend parameter optional?

**Comment by Angelin01** [comment]
I agree with Franklin here. I have been using the library in recent projects and it's quite good, but could use a few usability updates. Finally starting the process of deprecating backend arguments would be a step in the right direction.

As a note: it's been more than 2 years since this issue was opened with no updates aside from the reference in Franklin's closed issue. Time to take a look at it again?

**Comment by reaperhulk** [comment]
Well, this is done now 😄
