### ISSUE TITLE
Jython support ?

### ISSUE THREAD

**Issue by Voronenko** [pyca/cryptography#3926]
Any plans to officially support jython?

In hazmat namespace there are few functions that make use of so libraries.
At a present moment that prevents some packages, that reference cryptography from normal work without patching the hazmat primitives.

**Comment by reaperhulk** [comment]
cryptography depends extensively on a shared object built by cffi against OpenSSL. Jython support would be dependent on cffi supporting Jython. I'd suggest filing an issue there, although that is going to be a very large amount of work that (I believe) is unlikely to be undertaken by the current maintainers.

If and when cffi gets Jython support we can revisit it for this project. Sorry 😞

**Comment by Voronenko** [comment]
It depends, in reality.

Can't be  Cryptography_check_pkcs7_padding alternatively implemented in py?  I think so - there is no magic there.

Can lib.Cryptography_constant_time_bytes_eq use alternative implementation ?  I think , it can - there is nothing extra complicated to bind "so" to it as well.

In a result , scope of functionality that really depends on "cffi so" can be limited to critical things only.

**Comment by reaperhulk** [comment]
There are indeed a few extra shared objects, but those items are implemented in C precisely because the goal is to implement them in constant time to avoid timing attacks. Alternative implementations in pure Python would be vulnerable and thus not acceptable substitutes.

It seems unlikely that anyone would import cryptography and use the padding check, but not also use a symmetric primitive. Have you encountered this?

`Cryptography_constant_time_bytes_eq` could actually be replaced with `hmac.compare_digest` for Python 2.7.7+ and Python 3.3+ (and alternate implementations that comply with that API), which would potentially be something worth doing in a future where we can actually drop the alternate code path (e.g. dropping < 2.7.7 support)

**Comment by Voronenko** [comment]
For unlikely - there are always chances.

For example,  re-implementing two above functions unlocks azure python SDK blob operations. it is the only part of SDK that refers to hazmat namespaces so far.
