### ISSUE TITLE
Need PKCS1 + OAEP

### ISSUE THREAD

**Issue by nagylzs** [pyca/cryptography#3938]
I have to do assymetric encryption for a server that accepts PKCS1 + OAEP only. More specifically, I'm moving code from PHP to Python, and this is the exact call that I'm not able to convert from PHP to Python:

`
openssl_public_encrypt($input, $output, $public_key, OPENSSL_PKCS1_OAEP_PADDING))
`

The problem is that PKCS1 + OAEP is not supported. The documentation is clear about that:

https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.padding.OAEP

So it cannot be used with RSA signing. But I need this badly. Is it just some missing glue code in the cryptography package? Apparently, openssl does support the PKCS1 + OAEP combination, and it is also available in PHP. Can somebody please tell me if it would be possible to add PKCS1 + OAEP to cryptography? Or is there another package that I could use for this?

**Comment by reaperhulk** [comment]
I believe you have gotten several concepts confused due to the unfortunate naming OpenSSL uses for some functions/constants and PHP's choice to directly expose that to consumers.

First, `OPENSSL_PKCS1_OAEP_PADDING` is PHP's alias to `RSA_PKCS1_OAEP_PADDING` in OpenSSL. This is just OAEP padding, but because a later PKCS#1 specification is where OAEP is specified OpenSSL calls it "PKCS1_OAEP". That is not to be confused with PKCS1 padding (aka PKCS#1 v1.5).

Second, OAEP is indeed only for encryption, but `openssl_public_encrypt` also only encrypts. In OpenSSL's terminology `public_encrypt` is RSA encryption, `private_decrypt` is RSA decryption, `private_encrypt` is RSA signing, and `public_decrypt` is RSA signature verification.

So, the call you listed above can be replicated by loading an RSA public key and calling `encrypt` with the `OAEP` object. OAEP has both a primary hash function and a mask generating function (MGF1) that also takes a hash, so you'll need to look at what PHP uses for defaults there though.

**Comment by nagylzs** [comment]
Well, that is so confusing, but good to know. Thank you for the explanation.

**Comment by micfan** [comment]
sorry, I stile how to implement the PHP function `openssl_public_encrypt($input, $output, $public_key, OPENSSL_PKCS1_OAEP_PADDING))` in`cryptography`. Would you please provide a small git snippets demo？Thanks...

**Comment by reaperhulk** [comment]
Load your private key and call the `encrypt` method using `OAEP` as padding. You can find all of this information in our docs: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#encryption

**Comment by micfan** [comment]
@reaperhulk Thanks for you kind answer. I had rought wrong function in the previous question... I'm wondering to implement PHP function in http://php.net/manual/en/function.openssl-public-decrypt.php

 `openssl_public_decrypt ( string $data , string &$decrypted , mixed $key [, int $padding = OPENSSL_PKCS1_PADDING ] ) : bool`

The coresponde OpenSSL cli is like

``` bash
openssl  genrsa  -out key.pem 1024
openssl  rsa -in key.pem  -pubout  -out  pub.pem
openssl pkcs8 -topk8 -inform PEM -in key.pem -out priv.pem -nocrypt

echo -n 'hello world' > 1.txt
openssl rsautl -sign -in 1.txt -inkey priv.pem -out 1.bin
# here extract the original message from the cipher_text, and output into STDOUT 
openssl rsautl -verify -inkey pub.pem -in 1.bin -pubin
```

Could you share a sunshine?

**Comment by reaperhulk** [comment]
`openssl_public_decrypt` is actually verifying a signature. Load the public key and call `verify` (as seen in the docs). The specific padding you'll need to work out yourself.

**Comment by micfan** [comment]
`class cryptography.hazmat.primitives.asymmetric.rsa.RSAPublicKey.verify(signature, data, padding, algorithm)`

For `verify()` calling, how to fullfill the `data` argument?

**Comment by nagylzs** [comment]
The data argument is the data that was originally signed. As reaperhulk explained https://github.com/pyca/cryptography/issues/3938#issuecomment-332412558 the `openssl_public_decrypt` function is not actually decrypting anything. It verifies a digital signature. It's counterpart is `openssl_private_encrypt`, which calculates a signature for (the very same) data.

**Comment by micfan** [comment]
I need more researching on this PHP function.
