### ISSUE TITLE
FIPS certification?

### ISSUE THREAD

**Issue by sriluvan** [pyca/cryptography#4024]
Hello - 

My early apologies if any of this sounds unacceptable to this open source community. Posting this question because the question of FIPS certification for Python libraries has been raised by our compliance office and wanted to find out if there is any such move taken by the open source community.

What is the official position on FIPS certification for Python Cryptography? I see some anti-FIPS position discussed in here - http://pyvideo.org/pycon-us-2014/the-state-of-crypto-in-python.html, however, are there any guarantees for secure implementation as there isn't independent certification/verification? 

Thanks.

**Comment by alex** [comment]
Points, in order of relevance to you:

a) cryptography is outside the accreditation boundary for FIPS because we do not implement FIPS algorithms ourselves
b) If you link cryptography against a FIPS OpenSSL, you are FIPS compliant
c) FIPS is a bad crypto standard and I strongly encourage anyone who has the option to avoid it.

**Comment by sriluvan** [comment]
Thanks.
