### ISSUE TITLE
Problematic type for emailAddress in CSR

### ISSUE THREAD

**Issue by actics** [pyca/cryptography#4034]
Hello.
We generate CSR with cryptography, and after update from 2.0.3 to 2.1.3 we catch exception from openssl:
```
[actics@e7470 trash]$ openssl ca -days 365 -in request.csr -out certificate.cer -config openssl.cnf -batch
Using configuration from openssl.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'example.com'

emailAddress type needs to be of type IA5STRING
```
I found commit with problem changes: 72c92f5ed1
In my case, I was able to fix it with add private argument to x509.NameAttribute, but i don't like to use private objects :) 
```x509.NameAttribute(x509.NameOID.EMAIL_ADDRESS, emailAddress, _type=_ASN1Type.IA5String)```
Am I doing something wrong or is it a bug?
Thank you

**Comment by reaperhulk** [comment]
Thanks for the report. That is definitely the correct workaround for now despite being private.

It appears that since we weren't explicitly setting a type (just the default UTF8 mask) OpenSSL was automatically choosing ia5string (correct per RFC 5280). In the new system we do explicitly set a default type and it is wrong. I'll put up a PR to fix this soon.

**Comment by actics** [comment]
Thank you
