### ISSUE TITLE
Variable Tag Length on AESGCM

### ISSUE THREAD

**Issue by Krolken** [pyca/cryptography#4111]
Is there a special reason the tag length is fixed to 16 bytes in the AESGCM class in cryptography.hazmat.primitives.ciphers.aead.AESGCM

I am working with encrypting and decrypting data from electricity meters that use the AESGCM with 12 bytes auth tag. Now I am solving it with subclassing the AESGCM class but seems like an easy fix just to accept a tag_length argument as in the AESCCM class.

I would be happy to submit a pull request but want to hear if there is special reasons why it is fixed.

**Comment by alex** [comment]
Hmm, I'm interested in hearing @reaperhulk's take. My perspective is that the AEAD APIs should try to limit configuration options; this use case can be addressed by using the `Cipher(AES(), GCM())` API. (Of course, if we wanted to deprecate the `Cipher()` version of `GCM()`, then moving `tag_length` to the AEAD woudl make sense).

**Comment by Krolken** [comment]
OK. I also need to support the cases when just encrypting and just authenticating in the future.

**Comment by reaperhulk** [comment]
Yeah, the design of the AEAD APIs was to provide one-shot encryption/decryption while limiting the configuration options and ways to screw up.

GCM is used with a variety of configurations that don't quite fit the AEAD API, but I think the streaming API we already have can cover all those use cases. Your particular needs (including future needs) should be served by https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.modes.GCM

Maybe we should link to that from the AEAD page so users who need authentication only, truncated tags, etc know there's a more flexible/dangerous API available?

**Comment by Krolken** [comment]
OK. Then I'll focus on the cipher implementation.

I think a link in the docs would be nice. I realized that I had been on that page before when I read it but the AEAD API seems so much nicer :)

Maybe I'll make a wrapper for all my meter cryptography use cases in a separate project to keep it all nicely together while using the low level functions in cryptography.

Thanks for the input.

**Comment by Krolken** [comment]
Just a small question. You write:

> If you are encrypting data that can fit into memory you should strongly consider using AESGCM instead of this.

how is this solved using the AESGCM class?

**Comment by reaperhulk** [comment]
The cipher classes are a streaming API so when decrypting a GCM payload you can call update and receive decrypted bytes *before* the data has been authenticated (which only happens when you finalize since until then we can't know if the tag matches). The AESGCM class avoids this pitfall by requiring all data be present before decrypting (since you can only call `decrypt`). The upside of this is that it can never expose unauthenticated data, but the downside is that it is unsuitable for encryption of large volumes of data (anything more than you'd be comfortable keeping in RAM).

The AESGCM class also simplifies tag management by concatenating the tag to the end of the bytestream, whereas the low level APIs require you to distribute the tag yourself.

**Comment by Krolken** [comment]
OK. Thanks for the explanation. I interpreted it as the using Ciphers class when data could fit in memory would be less secure since you are recommending the other class, but it is just for convenience then, (and more secure in the way that you can't make many mistakes.)

Thank you so much for the input. I'll close the issue and start coding :)
