### ISSUE TITLE
[Feature request] X448

### ISSUE THREAD

**Issue by maqp** [pyca/cryptography#4136]
OpenSSL [now](https://github.com/openssl/openssl/issues/1398) supports X448 key exchange for TLS. Please add bindings for it.

**Comment by reaperhulk** [comment]
@maqp just to make sure I understand the request, do you want to see X448 key exchange support like we added X25519?

**Comment by maqp** [comment]
@reaperhulk: Yes, a hazmat module is all I'm requesting.

**Comment by reaperhulk** [comment]
Okay, this will be possible once 1.1.1 ships, although we'll need to decide what the serialization model looks like. We may also want to revisit PKCS8 support for X25519. Previously OpenSSL was using non-standard OIDs (because the standards post-dated OpenSSL's implementation) and I have no idea if that's been fixed/normalized in some fashion.
