### ISSUE TITLE
[feature request] include reason in InvalidToken from Fernet.decrypt

### ISSUE THREAD

**Issue by samuelcolvin** [pyca/cryptography#4353]
It would be extremely useful if I could check why a token failed decryption, particularly when it's expired.

Options:
* subclass `InvalidToken` as `ExpiredInvalidToken`
* add a simple message to `InvalidToken`, eg. `raise InvalidToken('token has expired')`

The first option is more canonical, but the second option would make it easier to summarise what's happened in other failure modes.

If I submitted a PR for one of these would you accept it?

**Comment by alex** [comment]
Nope, it's intentional that we do not distinguish between the error types.

Distinguishing error types at the application layer has been a source of numerous vulnerabilities in applications (error message side channel), so we intentionally don't do that.

For expiration specifically there are other APIs for querying on whether a token is expired, but nothing else will be distinguished.

**Comment by reaperhulk** [comment]
If your system already needs to treat expired different from invalid then you'll need custom logic regardless. Your control flow will either be on the proposed exception change or on `if fernet_obj. extract_timestamp(token) <= datetime.datetime.timestamp(datetime.datetime.now())`. I would agree it's a problem to implement the timestamp extraction yourself, but we've added `extract_timestamp` for this situation (https://cryptography.io/en/latest/fernet/#cryptography.fernet.Fernet.extract_timestamp). It will be in the next version, which will be released this week.

**Comment by samuelcolvin** [comment]
ok thanks, I'll use `extract_timestamp`.

Thanks for cryptography. It's great.

**Comment by reaperhulk** [comment]
cryptography 2.3 is now out btw so that method is available 😄
