### ISSUE TITLE
Allow key material to use bytearray instead of bytes

### ISSUE THREAD

**Issue by earonesty** [pyca/cryptography#4409]
Currently, this library requires key material to be "immutable" `bytes` type for most functions.  This means that it is, by design, difficult to clear the key material from RAM after it is used.  memset can be used on immutable `bytes` sequences to clear it... but this is fraught with potential issues.

It would be both fairly trivial and a big improvement for all private and symmetric keys to be the `bytearray` type.   Currently keys are left in RAM.   Using a `bytearray` allows keys to be cleaned up, removed from caches, etc.

**Comment by reaperhulk** [comment]
Sorry for the slow response. We agree that allowing bytearrays as well as bytestrings is the right move. There are a lot of call sites that check for bytes (or six.binary_type) so we'll need to update all of those and decide if we want to add tests that use bytearrays in at least some places.

**Comment by reaperhulk** [comment]
Just as an update here, in addition to the byte checks we need to fix we'll also need to call `ffi.from_buffer` on the bytearrays before passing them to the C layer. As of cffi 1.8 you can also call that function on byte strings, which would greatly simplify supporting this, although we'd need to move our minimum pypy to 5.4 for that.

Since

**Comment by reaperhulk** [comment]
and as of #4621 we allow this
