### ISSUE TITLE
Request: example of how to form S/MIME signature for email

### ISSUE THREAD

**Issue by tuck1s** [pyca/cryptography#4488]
It would be very useful to have a code snippet showing how to form  a PKCS7 signature suitable for inclusion into an S/MIME mail `multipart/signed` (preferred) or `application/x-pkcs7-mime; smime-type=signed-data`

The old M2Crypto library has a similar example here: http://proj.badc.rl.ac.uk/svn/ndg-security/branches/Dependencies/m2crypto/doc/howto.smime.html

**Comment by reaperhulk** [comment]
At the moment we have no higher level interfaces for creating a PKCS7 signature. https://github.com/pyca/cryptography/issues/1621 and https://github.com/pyca/cryptography/issues/3983 are the tracking bugs for this. I'm going to go ahead and close this since we're tracking this feature request already, but thank you for the suggestion!
