### ISSUE TITLE
Document why under Linux you use GRND_NONBLOCK

### ISSUE THREAD

**Issue by socketpair** [pyca/cryptography#4590]
I wonder why not to use BLOCKING read from `getrandom()` ?

IMHO, hanging is much more preferable than failing. I mean application that use Cryptography.

Anyway, it would be better to give possibility to change that behavior at runtime (using global variable ? Environment var ?).

**Comment by alex** [comment]
I don't think there's a good reason to use this, and we should drop it.

**Comment by socketpair** [comment]
@alex drop what exactly ? blocking mode or that syscall ? by what reason ?

**Comment by alex** [comment]
Drop the `NONBLOCK` flag. The only case it'd have an impact is early boot, so all it is is cruft for 99.9% of everyone.

We do explicitly handle the case where we'd blocked, but it basically puts the process into a broken state where it can never get randomness; I think attempting to block until the kernel CSPRNG is better, since that's recoverable.

**Comment by socketpair** [comment]
I suggest just use blocking mode. For those who have problems with that, I recommend to use https://wiki.archlinux.org/index.php/Haveged or virtual HWRNG for virtual machines, or enable getting entropy from Inte's HWRNG, or just run rngd with /dev/urandom as source of entropy.
