### ISSUE TITLE
Intermittent ECDSA DSS signature failures

### ISSUE THREAD

**Issue by jschlyter** [pyca/cryptography#4752]
Environments:
 - macOS 10.14.3, Python 3.7.2 with Cryptography 2.5, OpenSSL 1.1.1a  20 Nov 2018. 
 - Ubuntu Linux 18.04, Python 3.6.7 with Cryptography 2.5, OpenSSL 1.1.1a  20 Nov 2018. 

I'm having issues using cryptography to create ECDSA DSS signatures. A very small number of signatures (about 0.4-0.5%) does not verify. Please see my [example code](https://gist.github.com/jschlyter/a8b8ce2b75f4f9f25dc720ca1105fa80). Example code based on code from @rohe and used in [cryptojwt](https://github.com/openid/JWTConnect-Python-CryptoJWT).

**Comment by reaperhulk** [comment]
Splitting a signature in that fashion is *extremely* unwise. There is no guarantee that `r` and `s` are the exact same length. For example:

```python
from cryptography.hazmat.backends.openssl.backend import backend
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import hashes

def sig():
    key = ec.generate_private_key(ec.SECP256R1(), backend)
    sig = key.sign(b"hello", ec.ECDSA(hashes.SHA256()))
    return len(sig)

for _ in range(10):
    print(sig())
```
Will print something like:
```
72
71
72
71
70
72
70
71
71
71
```
Since the code you've provided incorrectly assumes that the lengths must be equal (https://gist.github.com/jschlyter/a8b8ce2b75f4f9f25dc720ca1105fa80#file-sigfail-py-L20) it will be wrong whenever they are not.

Since JWS (🤮) provides the signature as `r||s` big endian concatenated you'll need to make sure you pad the encoding to the size of the order of the curve. cryptography provides that with the horrendously named `key_size` attribute. You can see a good example of this via PyJWT: https://github.com/jpadilla/pyjwt/blob/d25c92ca5e9980ca7bc8b31420bf36e3f4a9e3f0/jwt/utils.py#L94-L100
