### ISSUE TITLE
Need support for ECC Brainpool and Koblitz curves. 

### ISSUE THREAD

**Issue by deepakbairy** [pyca/cryptography#4767]
New curve support required:
Brainpool160
 Brainpool192
 Brainpool224
 Brainpool320
 Secp160k1
 Secp192k1
 Secp224k1

**Comment by reaperhulk** [comment]
What is the use case for the curves you list as "new curve support required"?

**Comment by deepakbairy** [comment]
I use these curves for IOT security. Currently I am using this python cryptography module for loading ecc keys. SECP or NIST_P curves are working perfectly, but I need few more curves in brain pool and koblitz.

**Comment by reaperhulk** [comment]
Could you give us some more details? What spec or product is utilizing these curves? And for what? ECDH?

**Comment by deepakbairy** [comment]
I am using a hardware module where I am provisioning keys for the above mentioned curves. These keys are used during ECDH.

**Comment by alex** [comment]
_Why_ did you select these curves though? Is there some external specification or interoeprability requirement to use them?

**Comment by deepakbairy** [comment]
I am trying all the ECC curves on the hardware module. Where All other curves like NIST_P256, 384, 521, Brainpool 256, Koblitz 256 are working. Missing curves are listed in the requirement. 
 
https://datatracker.ietf.org/doc/rfc5639/?include_text=1 
refer section 5 table 1 for brain pool curves.

**Comment by reaperhulk** [comment]
The brainpool (and koblitz) curves are not widely used nor significantly better than our existing curves and we have no plans to expand support for them outside of specific use cases. The set of brainpool curves we currently support is only exposed specifically to support German smart meter requirements. Similarly, we expose `secp256k1` specifically because of its importance in the cryptocurrency ecosystem.

For security purposes in environments without legacy interoperability requirements X25519, X448, Ed25519, and Ed448 are strongly preferred over older curves anyway.

Any additional curve support we choose to add is predicated on the existence of specifications that require those curves.

**Comment by alex** [comment]
It's also worth mentioning that most of the curves you listed are <128 bit security.

**Comment by deepakbairy** [comment]
I have updated cryptography\hazmat\primitives\asymmetric\ec.py file with adding curves. Brainpool160, Brainpool192, Brainpool224, Brainpool320 and Secp192k1 started working.
I would like to contribute upadted contents to cryptography. Is it possible to add that ?

**Comment by reaperhulk** [comment]
We are not going to expose additional curves without a specific reason. The curves you are proposing have (to my knowledge) no real world usage and many of them additionally have low order, making them unsafe in many situations.

If there are specifications that utilize these curves for real applications please provide links to them and we can review it.

**Comment by alex** [comment]
No answer here. If we get a response we'll reopen.
