### ISSUE TITLE
"Trojan:Win32/Skeeyah.l" detect from cryptography

### ISSUE THREAD

**Issue by Data-Diver** [pyca/cryptography#4823]
I'm using windows server 2016 and running Windows Defender service.
I try to install cryptography using pip.
but Windows Defender delete "cffi\_cffi_backend.cp36-win_amd64.pyd" everytime.
Dedenfer's deleting reason is "Trojan:Win32/Skeeyah.l" detect from cryptography sources.

cryptography is included malware? is really safe?

_Originally posted by @Data-Diver in https://github.com/pyca/cryptography/issues/3703#issuecomment-476481476_

**Comment by reaperhulk** [comment]
That is actually a native library compiled for the `cffi` package and not `cryptography`, although we depend on `cffi` so that's why it's installing during your `pip` command. That file is definitely not malware and is a critical component of the library. Windows Defender is evidently returning a false positive. I'd suggest reporting this to Microsoft, although I'm not sure how.

**Comment by Data-Diver** [comment]
I understood that this problem is not caused by cryptography.
I will send report to Microsoft.below url.
https://www.microsoft.com/en-us/wdsi/filesubmission

Thanks quick reply. 
hmm:(
