### ISSUE TITLE
AES-CBC gives different results on Mac OS X than in Windows

### ISSUE THREAD

**Issue by ohadbenita** [pyca/cryptography#4964]
* DONE - Upgrade to the latest version of ``setuptools`` and ``pip``
* DONE - Make sure you're on a supported version of OpenSSL
* DONE - Try with the latest version of ``cryptography``

Package versions:

``cryptography==2.7``
``cffi==1.12.3``
``pip==19.2.1``
``setuptools==41.0.1``

Cryptography installed in virtualenv: ``pip install cryptography``
Clear steps for reproduction requires Mac and the execution of the code from [here](https://stackoverflow.com/questions/57375945/aes-encryption-in-python-different-results-when-using-pycryptodome-and-cryptog)

Please note that the **same** code produces different version in Mac and Windows.
I've double-checked and it uses the same dependencies for the packages above.
If any further info is needed I'll be glad to add it.

**Comment by reaperhulk** [comment]
We’ll need to see sample code to reproduce this.

**Comment by reaperhulk** [comment]
Oops I see there was a SO link I missed.

**Comment by reaperhulk** [comment]
Okay, while that code isn't executable (we don't have your test runner, it's extracted partially from a class, there are test mocks that appear to use base64 encoded values as an IV...?) I can see at least one issue. AES.block_size is the block size in *bits* for cryptography (documented [here](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.BlockCipherAlgorithm)). So your `aes_pad` function is wrong because it's assuming a size in bytes. That padding algorithm also doesn't pad at all if the data encrypted is an exact multiple of the block size. This is unwise since it allows trivial truncation attacks. It seems likely this was just a mistake in implementing [PKCS7](https://cryptography.io/en/latest/hazmat/primitives/padding/) padding, which cryptography has support for natively.

I'm not sure why you're seeing different output between mac and windows, but if you fix your other issues and provide a directly executable example I can look into that a bit more.

**Comment by ohadbenita** [comment]
Thanks for your detailed answer.

You are **absolutely** right, the issue was about the AES block size. Might be good to document it in the example given [here](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/)
