### ISSUE TITLE
[Feature request] Human-readable representations of certificates and other objects

### ISSUE THREAD

**Issue by patrakov** [pyca/cryptography#5009]
I have recently tried to port a codebase that I would rather not name from `M2Crypto` to the current recommended OpenSSL binding, `cryptography`. However, I could not find how to get a human-readable representation of an X509 certificate (equivalent of `openssl x509 -noout -text` output), without going through `hazmat`, `ffi`, and dealing with `BIO`s directly, which is not something that would pass a review. So, I had to add a dependency on `pyOpenSSL` to the project, which is not ideal.

I had to write this code:

```python
    def getCertAsText(cert):
        sslcert_wrap = OpenSSL.crypto.X509.from_cryptography(cert)
        sslcert_dump = OpenSSL.crypto.dump_certificate(
                OpenSSL.crypto.FILETYPE_TEXT, sslcert_wrap)
        return sslcert_dump.decode('utf-8', errors='replace')
```

Given that `cryptography` is not going to support backends other than OpenSSL, I think it would be reasonable to provide an official equivalent of this function in `cryptography`, as well as the possibility to get such text representations for other crypto objects supported by the library.

**Comment by patrakov** [comment]
If there is a consensus that this functionality is indeed acceptable in `cryptography`, I would be willing to contribute a patch.

**Comment by reaperhulk** [comment]
Any textual interface we provide becomes something that needs to provide stability across any version of OpenSSL used or else compatibility problems arise. Is there some reason you can't utilize  the existing X509 parsing we have available to build a textual representation that works for you? If that *does* work, then do you believe a textual repr using those APIs that is available via a single function call be useful to a broader set of people?

**Comment by patrakov** [comment]
I don't care about the representation being stable across OpenSSL versions (and it actually isn't stable, e.g. there are whitespace differences even in the Subject line), because it is for display purposes (including debug purposes) only.

Regarding the question about utilizing the existing X509 parsing and building some textual representation from that, I (as a user) am afraid that there are too many corner cases, and I would need to write too much (dangerous, hazardous) code to build even an approximate equivalent of what OpenSSL provides. Delegating the task of building the comprehensive textual representation of the certificate to OpenSSL authors, who know better, instead of duplicating their work, looks like the right idea to me.

The third question is mooted by the negative answer to the second one.

**Comment by reaperhulk** [comment]
Yes, OpenSSL has not made it stable, but that is precisely my point. When we expose interfaces like this users naturally assume they're stable and then become frustrated when (over the course of years) they prove not to be. This is especially frustrating in a situation like this where you can pin `cryptography`, but an upgraded underlying OpenSSL results in different output.

This is not a mere hypothetical -- we've had years of complaints and bug reports filed by pyOpenSSL users due to this. As such, I'm opposed to exposing OpenSSL's textual serialization APIs. If a textual repr is desirable then we should build a stable one.

I'm going to go ahead and close this issue for now, but I'm happy to discuss an approach to iteratively build a stable output in a PR that starts on it.
