### ISSUE TITLE
generation of the .so files

### ISSUE THREAD

**Issue by sathishdeven** [pyca/cryptography#5012]
Hi Team, As everyone I too face issue with the cryptography library compiled in a different OS, and running that in Lambda. I tried downloading the source code of the Cryptography and then use it as a source file of my package. And i now got the Error **No module named 'cryptography.hazmat.bindings._constant_time'** it seems there are some files like **_constant_time.so** and other '.so files' that are created on the fly. Would like to know how and from where these file are generated. Can I place these file manually generated from a EC2. Will the program work when deployed in as a lambda.

**Comment by alex** [comment]
cryptography contains python extensions that need to be compiled, you cannot simply copy the source code.

The recommended workflow for developing lambdas, as far as I know, is to `pip install cryptography` either into a virtualenv or with `--target` on an Amazon Linux instance and copy the resulting installation directory

**Comment by mattsb42-aws** [comment]
Hi @sathishdeven,

This is a very common issue I have seen people run into. @alex hit the problem on the nose; the hard part of the solution is making sure that you are building on a platform that is *close enough* to the Lambda runtime to work.

There are a variety of different ways that you can approach this.

The simplest one-off approach is to do what @alex suggested and package up your Lambda zip on an Amazon Linux system.

Getting a bit more complex (but hopefully easier to repeat), I and others have made a variety of different attempts over the years at finding a good solution to this.

### Accretion

My latest attempt (still in a bit of flux) is Accretion: a set of tools that aim to make building and deploying Lambda Layers in multiple regions as simple as possible. This project has not been getting much of my attention recently, but if there is interest from people other than me I'm happy to change that. :)
https://accretion.readthedocs.io/en/latest/src/overview.html
https://accretion.readthedocs.io/en/latest/src/cli.html

### Docker

Another option is to use a tool like the AWS Lambda Container Image Converter to take a dockerfile that builds all of your needed components and creates a zip file that you can upload to Lambda to create a Layer.
https://github.com/awslabs/aws-lambda-container-image-converter

### CodeBuild

An earlier attempt of mine (predating Layers) was to use CodeBuild to build a zip that contains `cryptography`. This works, but it involves additional work that you will need to do in order to get the zip into a usable state.
https://github.com/mattsb42/codebuild-python-cryptography-custom-openssl


### Other

I'm sure there are other approaches, but these are the ones I'm familiar with offhand.

**Comment by reaperhulk** [comment]
Last I checked manylinux1 wheels were compatible with Amazon Linux so you *should* be able to use the precompiled data there. You'll still have to unpack the wheel and putting it in the right place for lambda of course.
