### ISSUE TITLE
Support AF_ALG in-kernel cryptography

### ISSUE THREAD

**Issue by socketpair** [pyca/cryptography#5060]
https://www.pythonsheets.com/notes/python-socket.html

```
$ python3 aes-gcm.py
total cost time: 15.317010641098022. [AF_ALG]
total cost time: 50.256704807281494. [cryptography]
```

Thanks to Python3.6 `socket.sendmsg_afalg()` function.

**Comment by reaperhulk** [comment]
I'm reluctant to add branches to do this in a library meant for general purpose cryptography. When AF_ALG makes sense and when it doesn't (and whether you're on a platform that even supports it since it's Linux-specific) makes the decision highly dependent on the application. Hypothetically this would be the sort of thing we'd handle with a `backend` but since we've never had a good way to implement multiple backends I think we may have to leave this out of scope of the project.
