### ISSUE TITLE
Cannot build wheel on Redhat 5.6 due to 'unrecognized command'

### ISSUE THREAD

**Issue by sinmaker** [pyca/cryptography#5088]
I try to build wheel of cryptography-2.8 on Redhat 5.6 i686 and it fails due to:
`cc1: error: unrecognized command line option "-Wno-error=sign-conversion"`

Versions I use:
Red Hat Enterprise Linux Server release 5.6 (Tikanga)
gcc 4.1.2
Python 2.7.8
pip 19.0.1
setuptools 40.6.3
cffi 2.19

When I try to run `python setup.py bdist_wheel` I get the following error:

> root@host-ci033 (Redhat 5.6) ➜  cryptography-2.8 python setup.py bdist_wheel
> running bdist_wheel
> running build
> running build_py
> running egg_info
> writing requirements to src/cryptography.egg-info/requires.txt
> writing src/cryptography.egg-info/PKG-INFO
> writing top-level names to src/cryptography.egg-info/top_level.txt
> writing dependency_links to src/cryptography.egg-info/dependency_links.txt
> reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> no previously-included directories found matching 'docs/_build'
> warning: no previously-included files found matching 'vectors'
> warning: no previously-included files matching '*' found under directory 'vectors'
> warning: no previously-included files found matching 'azure-pipelines.yml'
> warning: no previously-included files found matching '.azure-pipelines'
> warning: no previously-included files found matching '.travis.yml'
> warning: no previously-included files found matching '.travis'
> warning: no previously-included files matching '*' found under directory '.azure-pipelines'
> warning: no previously-included files matching '*' found under directory '.travis'
> warning: no previously-included files found matching 'release.py'
> warning: no previously-included files found matching '.coveragerc'
> warning: no previously-included files found matching 'codecov.yml'
> warning: no previously-included files found matching 'dev-requirements.txt'
> warning: no previously-included files found matching 'rtd-requirements.txt'
> warning: no previously-included files found matching 'tox.ini'
> writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
> running build_ext
> generating cffi module 'build/temp.linux-i686-2.7/_padding.c'
> already up-to-date
> generating cffi module 'build/temp.linux-i686-2.7/_constant_time.c'
> already up-to-date
> generating cffi module 'build/temp.linux-i686-2.7/_openssl.c'
> already up-to-date
> building '_openssl' extension
> gcc -pthread -fno-strict-aliasing -I/root/python/include -I/root/python/include/gnutls -I/root/python/include/graphviz -I/root/python/include/libexslt -I/root/python/include/libxml2 -I/root/python/include/libxslt -I/root/python/include/ncurses -I/root/python/include/openssl -I/root/python/include/readline -I/root/python/include/sasl -I/root/python/lib/libffi-3.2.1/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/python/include/python2.7 -c build/temp.linux-i686-2.7/_openssl.c -o build/temp.linux-i686-2.7/build/temp.linux-i686-2.7/_openssl.o -Wconversion -Wno-error=sign-conversion
> cc1: error: unrecognized command line option "-Wno-error=sign-conversion"
> error: command 'gcc' failed with exit status 1

Probably the flag `-Wno-error=sign-conversion` is not supported on old gcc versions like the Redhat 5.6 has.

**Comment by alex** [comment]
You'll need to build with a newer compiler then. We cannot support antique compilers like what RHEL ships with. If you'd like someone to be responsible for this, you should complain to RHEL support.

**Comment by sinmaker** [comment]
RHEL 5 is still used and supported until November 30, 2020 (https://access.redhat.com/support/policy/updates/errata)
and its gcc cannot be upgraded.

Another possible solution is that you upload to pypi the `manylinux1_i686.whl` versions like you used to until cryptography version 2.6.1

**Comment by alex** [comment]
RHEL is a commercial product you are paying for, and we are an open source
project. We will not support extremely legacy tools.

**Comment by reaperhulk** [comment]
We have limited time resources available and we've chosen, based on usage and difficulty of maintenance, to allocate our supported platforms accordingly. However, the scripts and dockerfiles we wrote can be used by you to build newer wheels for your own use. If you need RHEL5 x86 support I’d recommend building it via that path.

**Comment by wiggin15** [comment]
@alex RHEL 5 is, unfortunately, still used in enterprise environments that also want to use your open source project. We understand that it's low priority and that you have limited resources but there is a case to at least try to support it. We use many other C-extension packages on this system and we don't encounter a lot of problems.

Any chance to see if we can avoid the "sign-conversion" warning so we don't need the flag?

**Comment by wiggin15** [comment]
The comment above the flag `-Wno-error=sign-conversion` says this:

```
    We set -Wconversion args here so that we only do Wconversion checks on the
    code we're compiling and not on cffi itself (as passing -Wconversion in
    CFLAGS would do). We set no error on sign conversion because some
    function signatures in OpenSSL have changed from long -> unsigned long
    in the past. Since that isn't a precision issue we don't care.
    When we drop support for CRYPTOGRAPHY_OPENSSL_LESS_THAN_110 we can
    revisit this.
```

It's not clear exactly which function signatures changed, but we could not find any problem in both older and newer versions of OpenSSL. Cryptography compiles properly _without_ the flag `-Wno-error=sign-conversion` in the following configurations:

* (RHEL 5) gcc 4.1.2, openssl 0.9.8e
* (RHEL 6) gcc 4.4.5, openssl 1.0.0
* (RHEL 7) gcc 4.8.2, openssl 1.0.1e
* (RHEL 8) gcc 8.2.1, openssl 1.1.1

Will you be willing to consider a PR that removes the flag?

**Comment by reaperhulk** [comment]
I appreciate you trying to look into this, but it doesn't actually compile properly if you pass the full set of flags we actually use. Some explanation is in order:

We pass `-Werror` to our entire build in CI (with a few additional global flags) via `CFLAGS`. You can see this in two places (https://github.com/pyca/cryptography/blob/master/azure-pipelines.yml#L60 and https://github.com/pyca/cryptography/blob/master/.travis/run.sh#L12). We want `-Wconversion` because it explicitly captures a bug we've seen in the past where we improperly defined a return value that was too narrow and combined with `-Werror` any warning becomes an error that stops the build. Unfortunately, there is a class of errors that `-Wconversion` enables that we don't care about: sign conversions! So we need to couple it with `-Wno-error=sign-conversion` because there are dozens of warnings that would become errors otherwise. You can see these if you `pip install -v .`.

We also can't pass `-Wconversion` as a global flag because it would cause failures when compiling `cffi` in our infrastructure, and we can't pass `-Wno-error=sign-conversion` as a global because we had issues with downstream consumers (like distros) having failing builds.

This means that removal of the `-Wno-error=sign-conversion` flag would cause an immediate failure in our CI on both macOS and Linux and removal of both that and `-Wconversion` would risk introducing a class of bug we currently prevent. The reasons why we have these signature mismatches are varied, but some are due to the way cffi does its wrapped functions, some are changed signed -> unsigned over the course of 20+ years of OpenSSL, and some are because we choose to expose bitfields (like that returned by `SSL_ctrl`) as positive integers rather than signed ones.

Regarding the final reason...whether or not that was a good choice, it's the API we're stuck with for compatibility reasons (and was partially dictated by originally building these bindings to help make `pyOpenSSL` be a pure Python project while maintaining proper compatibility on that side).

All of this is a long-winded way of saying we're not likely to take a patch to remove this.

Incidentally, the time spent verifying this and writing it up is exactly what we mean when we say we have limited resources and that this sort of issue is best handled by building these wheels yourself. Our entire infrastructure (https://github.com/pyca/infra/tree/master/cryptography-manylinux, https://github.com/pyca/cryptography/blob/master/.azure-pipelines/wheel-builder.yml#L77-L145) is open source and it's easy to see how to build the container and a valid i686 manylinux1 image that would work without issues for your own purposes. We would even have kept building them except in our switch to azure pipelines we lost the ability to run i686 containers! Keeping ancient systems running is a burden on the open source community in many ways that are not always obvious.

I hope the tooling we've provided can give you an easy path to building your own wheels until you can migrate off RHEL5. We spent an inordinate amount of time building that infrastructure precisely to stave off these sorts of conversations in past years, but we can't afford to keep dragging the past along with us forever. Good luck!

**Comment by wiggin15** [comment]
Thank you for the detailed and respectful answer.

If the `-Werror`/`-Wno-error` flags are only used for CI to detect problematic warnings, and have no effect when building the distributions or elsewhere, maybe we can check the global environment variables to add or not add the flags in `build_openssl.py`? Something like `if "-Werror" in os.environ.get("CFLAGS", "")`?
