### ISSUE TITLE
NotImplementedError for unnamed curves

### ISSUE THREAD

**Issue by King-Konsto** [pyca/cryptography#5105]
Would it be possible to remove the NotImplementedError from the following lines:
https://github.com/pyca/cryptography/blob/9c759d08870d972f1d84e8543130bfb26be4e442/src/cryptography/hazmat/backends/openssl/ec.py#L28-L57
When trying to get the public key bytes from a signature that has been created with an unnamed curve I always run into this error:
`NotImplementedError: ECDSA keys with unnamed curves are unsupported at this time`
I would be happy if I could get the public key bytes for that signature without running into that error.

**Comment by reaperhulk** [comment]
That exception is raised to prevent loading of these keys (and the accompanying issues that can come from trying to use them elsewhere in our API) so bypassing the check is, unfortunately, problematic. If you have a need to get these bytes I'd suggest monkey patching the check and then calling `public_bytes` on the resulting object. That will likely work since the underlying library does (foolishly) support unnamed curves. Given the danger (and general lack of utility) with unnamed curves we're unlikely to directly support them.
