### ISSUE TITLE
Support larger lock sizes for `PKCS#7` and `ANSI X9.23`

### ISSUE THREAD

**Issue by Legorooj** [pyca/cryptography#5108]
Could you support more block sizes in the `PKCS#7` and `ANSI-X9.23` symmetric padding schemes? This would fix a major pain I have in some file encryption software - I need block sizes of `4096` bytes (`32768` bits) for my program. I am currently overriding it with the code below, but can't see any reason *not* to support larger block sizes.

```python
from cryptography.hazmat.primitives.padding import _PKCS7PaddingContext, _PKCS7UnpaddingContext


def _byte_padding_check(block_size):
    if not (0 <= block_size <= 32768):
        raise ValueError("block_size must be in range(0, 2041).")

    if block_size % 8 != 0:
        raise ValueError("block_size must be a multiple of 8.")


class PKCS7(object):
    def __init__(self, block_size):
        _byte_padding_check(block_size)
        self.block_size = block_size

    def padder(self):
        return _PKCS7PaddingContext(self.block_size)

    def unpadder(self):
        return _PKCS7UnpaddingContext(self.block_size)
```
This code has been tested and it works.

**Comment by reaperhulk** [comment]
PKCS7 can't be defined for block sizes > 2040 bits because it is defined `n` bytes of padding where each byte is the ordinal value of `n`. Since you can only represent 0-255 with a single byte that is the maximum possible. Similarly, ANSI X9.23 defines padding with the ordinal value of the last byte representing the length of the padding in bytes. This, again, can only be 255 bytes maximum. Sorry!

**Comment by Legorooj** [comment]
Damn. Thanks anyway!
