### ISSUE TITLE
Doc mistake in example.

### ISSUE THREAD

**Issue by Olegandr** [pyca/cryptography#5127]
Example for extentions [here](https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate.extensions) contains errors:

` <Extension(oid=<ObjectIdentifier(oid=2.5.29.15, name=keyUsage)>, critical=True, value=<KeyUsage(digital_signature=False, content_commitment=False, key_encipherment=False, data_encipherment=False, key_agreement=False, key_cert_sign=True, crl_sign=True, encipher_only=None, decipher_only=None)>`

Last two parameters should also be False, as per documentation. Otherwise certificate creation fails.

**Comment by reaperhulk** [comment]
This is perhaps a bit confusing but is not a bug in the docs. The `__repr__` shown there says None because in this case `encipher_only` and `decipher_only` have no meaning when `key_agreement` is not `True`. We represent this in the repr by saying `None`, but `None` is not allowed in the `__init__` of the class itself.

Since this is confusing and also causes a bug to manifest if you attempt to use this structure in certificate creation we should probably revisit this (and likely enforce boolean as well).

**Comment by Olegandr** [comment]
If the example is failing to build, then this example is wrong in my book, so please correct for the benefit of those who will try to use it in future.
