### ISSUE TITLE
Appending and ecrypting a file with AES CTR

### ISSUE THREAD

**Issue by arshad01** [pyca/cryptography#5254]
Hello All,

This is not an issue but request for help.

I need some help and advice regarding encrypting a file and appending to it. Basically my application receives data in chunks which I have to encrypt and write to a file. So with each data chunk received, I encrypt it and append to the file. I chose AES CTR as the encryption algo. Since the file is encrypted, I need to seek to end of file and update the AES encryptor. To get the counter to point to correct block value I am using something like below:

```
last_block_offset = 16 * (filesize // 16)  # the offset of the last block, 16 is AES block length
encryptor.update(b'\x00' * last_block_offset)  # adjust the counter
encryptor.write(data)
```

This works fine for small files but as the file size increase and last_block_offset becomes bigger, the encryptor.update(b'\x00' * last_block_offset) takes longer time and more space to run.

Is there any other way to update the counter without needing to encrypt all the zero bytes?

Any idea or help is very much appreciated.

Thanks

**Comment by reaperhulk** [comment]
The issue tracker isn't really a good place for getting support like this -- stackoverflow.com is more appropriate since other users can help you.

That said, to do what you want you shouldn't keep an `encryptor` instance at all. You should instead compute the block offset and therefore the nonce you pass to the CTR instance. e.g. if you  have a `(key, nonce)` pair where `nonce` is `b"\x00" * 16` then if you needed to seek to a specific block you could simply treat the nonce as a 128-bit integer, add the number of blocks, convert the integer to a byte string (I believe OpenSSL uses little endian here but you can experiment to confirm), and pass that byte string as your new nonce.

By doing it this way you can seek to an arbitrary block offset with no encryption overhead at all. The swift project (openstack object storage) does this and you can see a sample implementatio here: https://github.com/openstack/swift/blob/ae36030278b244148363d4a1c6ed0c7fc7cb5204/swift/common/middleware/crypto/crypto_utils.py#L76-L84

**Comment by alex** [comment]
We'd be remiss if we didn't note that a big problem with this encryption scheme is that you don't have any integrity checks (e.g. hmac), so someone can mutate the file under your feet and cause havoc.

**Comment by arshad01** [comment]
> 
> 
> The issue tracker isn't really a good place for getting support like this -- stackoverflow.com is more appropriate since other users can help you.
> 
> That said, to do what you want you shouldn't keep an `encryptor` instance at all. You should instead compute the block offset and therefore the nonce you pass to the CTR instance. e.g. if you have a `(key, nonce)` pair where `nonce` is 0 (16 NULL bytes) then if you needed to seek to a specific block you could simply treat the nonce as a 128-bit integer, add the number of blocks, convert the integer to a byte string (I believe OpenSSL uses little endian here but you can experiment to confirm), and pass that byte string as your new nonce.
> 
> By doing it this way you can seek to an arbitrary block offset with no encryption overhead at all. The swift project (openstack object storage) does this exact operation and you can see a sample implementation here: https://github.com/openstack/swift/blob/ae36030278b244148363d4a1c6ed0c7fc7cb5204/swift/common/middleware/crypto/crypto_utils.py#L76-L84

Thanks very much for your reply and I apologize for using this forum for my question. Your suggestion and link exactly address my issue. :)

**Comment by arshad01** [comment]
> 
> 
> We'd be remiss if we didn't note that a big problem with this encryption scheme is that you don't have any integrity checks (e.g. hmac), so someone can mutate the file under your feet and cause havoc.

Yes, your are absolutely right. In my application, file signature is calculated separately.
