### ISSUE TITLE
ECDSA signatures variable r and s length

### ISSUE THREAD

**Issue by merlokk** [pyca/cryptography#5275]
I see strange behavior of ECDSA signatures.

ECDSA signature is a TLV tree with `r` and `s`. When `r`s or `s`s high-order bit in the `1` state - needs to add external 0x00 byte to the sequence. Without this byte - signature is wrong.
attached piece of code sometimes raise an error, sometimes no...

looks like somewhere inside `r` and `s` is converted to signed number and all the problems because of that(

Or maybe it not wrong? and always needs to add 0x00?

here colab notebook:
https://colab.research.google.com/drive/1u8Wo_E5VgIA3jQIPvZh0W_oM_WvwTFvA?usp=sharing

raw code:
```
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import utils


private_key = ec.generate_private_key(ec.SECP256R1(), default_backend())
data = b"Sign me please"
signature = private_key.sign(data,ec.ECDSA(hashes.SHA256()))

rlen = signature[3]
r = signature[4:4+rlen]
s = signature[3 + rlen + 3:]
if len(r) == 0x21 and r[0] == 0x00:
    r = r[1:]
if len(s) == 0x21 and s[0] == 0x00:
    s = s[1:]
signature2 = b"\x30\x44\x02\x20" + r + b"\x02\x20" + s

pub = private_key.public_key()

#OK
pub.verify(signature, data, ec.ECDSA(hashes.SHA256()))
#sometimes ERROR sometimes OK
pub.verify(signature2, data, ec.ECDSA(hashes.SHA256()))

print("------------------- OK ---------------------")
```

**Comment by merlokk** [comment]
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.6/dist-packages (from cryptography) (1.14.0)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from cryptography) (1.12.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi!=1.11.3,>=1.8->cryptography) (2.20)

cryptography-2.9.2

**Comment by markokr** [comment]
I think ASN.1 does not have "unsigned" type, thus to encode positive int with high bit, you always need to add \0.

**Comment by merlokk** [comment]
and looks like i have found another surprise(

for curve `ansix9p521r1`
`002a3a04091d97b2a49c969f0adfc33564e1be8090b6e80442f4b4bedb860eb640c95efb52cf25fadaa423c188489b84b518ff371ca2d355978cffb7f53ad08ddb67` is not valid too...

it need `2a3a04091d97b2a49c969f0adfc33564e1be8090b6e80442f4b4bedb860eb640c95efb52cf25fadaa423c188489b84b518ff371ca2d355978cffb7f53ad08ddb67` because `2a & 0x80 == 0`

**Comment by reaperhulk** [comment]
The signature is an ASN.1 sequence containing two integers (r, s) as defined inn RFC 3279:
```
      Dss-Sig-Value  ::=  SEQUENCE  {
              r       INTEGER,
              s       INTEGER  }
```

In ASN.1 an integer is negative if the MSB is 1, so to represent a positive integer where the MSB would be 1 you need to precede it with a null byte to be canonically DER. However, due to various other libraries not necessarily doing a good job of this most implementations are pretty tolerant of unneeded `00` prefixes and sometimes even tolerant of failing to add the prefix when needed.

If you're interested in the nuances of how OpenSSL handles this you should check out the source code for this encoding, but `cryptography` simply inherits whatever quirks OpenSSL has chosen to allow.
