### ISSUE TITLE
How to set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2

### ISSUE THREAD

**Issue by betterprogram** [pyca/cryptography#5586]
I ran into the following error message, even after an upgrade of OpenSSL.
"RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2."
The same error occurred in many occasions, e.g. running  $ python -m OpenSSL.debug
Since upgrading OpenSSL did not change the linkage, I was wondering what would be the best approach to resolve this issue.
Or, how (and where) I can set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2?
Anyone?

**Comment by alex** [comment]
You set the environment variable in your OS's environment, e.g. in `bash` it'd be: `env CRYPTOGRAPHY_ALLOW_OPENSSL_102=1 python -m OpenSSL.debug`.

**Comment by betterprogram** [comment]
The RuntimeError persists while running $ python -m OpenSSL.debug
However, it resulted  "/usr/bin/python: No module named OpenSSL"  after running 
env CRYPTOGRAPHY_ALLOW_OPENSSL_102=1 python -m OpenSSL.debug
in bash. I must miss something but what is it?

**Comment by reaperhulk** [comment]
There are several issues here. Upgrading OpenSSL is non-trivial and unless you know how to properly direct your linker and set pathing it generally requires upgrading your distribution. Your second problem is that  you are apparently trying to import pyOpenSSL things (which is not cryptography, although pyOpenSSL itself depends on cryptography) and the module is not found in your python environment. We can't provide support for issues like this since they are Python environment/development issues and not problems with our libraries.
