### ISSUE TITLE
Question about different OpenSSL version between cryptography and CPython

### ISSUE THREAD

**Issue by kulikjak** [pyca/cryptography#5695]
Hi, I have a question.

Should I be worried about the fact that while new cryptography is linked against OpenSSL 1.1, our Python runtime uses OpenSSL 1.0.2 (for it's `ssl` standard module)? I mean, these two versions are not binary compatible, but share for example function names.

My guess is that I should be worried, but I was not able to break anything (with internal test suites) and found no mention anywhere online that this can be an issue, so maybe I am missing something?

Thanks!

**Comment by alex** [comment]
It's fine for cryptography to link against a different version of OpenSSL itself. The symbols in the cryptography wheel are not exposed, so they don't interefere with the ssl module.

**Comment by reaperhulk** [comment]
The answer to that becomes very complex very quickly due to the vagaries of dynamic linkers and how Python loads native modules. The symbol tables are separate between Python and the modules (modules are loaded RTLD_LOCAL), but shared by other modules that may also use openssl. So you are likely fine but if you import another module expecting something else you could cause problems. You’ll know when you segfault. Alternately you could build your own static wheels and ensure that can’t happen of course.

**Comment by kulikjak** [comment]
I see, that means that my use case is ok until I load another module (like `pycurl`) which uses OpenSSL version different from cryptography.

Good to know, thanks!
