### ISSUE TITLE
Please support Rust 1.41.1

### ISSUE THREAD

**Issue by zeha** [pyca/cryptography#5769]
Hi,

please support building cryptography with Rust 1.41.1. Debian stable ("buster") has no later version available.
We rebuild all Python libraries instead of using binary wheels for a few reasons.
Backporting Rust 1.45 or newer would be a lot of work.

Thanks for your consideration.

**Comment by alex** [comment]
The minimum version of Rust we support is dictated by pyo3, so we're not in a position to move to a lower version (and we can't support a lower version of pyo3 because we need the abi3 support that's only present in the most recent versions).

Your best bet will be to either build on debian bullseye (which I realize isn't stable yet) or to use a rust from upstream (via rustup).
