### ISSUE TITLE
Missing Extended Keys Usages Microsoft Smartcard Logon & KDCAuth

### ISSUE THREAD

**Issue by commonism** [pyca/cryptography#5892]
I've come across [ExtendedKeyUsages](https://www.pki.dfn.de/fileadmin/PKI/anleitungen/DFN-PKI-Zertifikatprofile_Global.pdf) with are unknown to cryptography:

Microsoft Smartcard Logon 1.3.6.1.4.1.311.20.2.2
KDCAuth 1.3.6.1.5.2.3.5
(Rhode & Schwarz) TrustedDisk 1.3.6.1.4.1.30205.13.1.1

Is there any interest in getting Smartcard Logon & KDCAuth added?

**Comment by reaperhulk** [comment]
EKUs can contain arbitrary OIDs, so in general we've chosen to only list the ones specified directly in relevant RFCs. I am a bit reluctant to add more since then we need to come up with a measurement of notability. KDCAuth isn't part of the PEN arc so maybe that one is worth adding, but Microsoft is also an important company. @commonism is this just a presentational issue for you or is cryptography failing to properly parse the OID value?

**Comment by mathiasertl** [comment]
Just one datapoint, but Smartcard Logon & KDCAuth were already requested by another indirect cryptography user: mathiasertl/django-ca#46.

**Comment by reaperhulk** [comment]
For that use case it appears that there's just a desire for a pre-existing OID object so that users don't have to construct it themselves? I'm okay with adding prominent ones on a case-by-case basis as long as we can have docs that describe what their use is.

**Comment by reaperhulk** [comment]
If anyone wants to send a PR for this I'm happy to review.

**Comment by mathiasertl** [comment]
Would do, for attributes I would propose:

* `SMARTCARD_LOGON` (don't use company name?)
* `KERBEROS_KEY_DISTRIBUTION_CENTER`  - what KDC actually stands for: https://docs.microsoft.com/en-us/windows-server/security/kerberos/kerberos-authentication-overview
* `TRUSTED_DISK` - again no company name?
