### ISSUE TITLE
Cryptography compilation (offline)

### ISSUE THREAD

**Issue by Kempfu** [pyca/cryptography#5912]
Hello!

I'm having trouble compiling cryptography 3.4.6 on a rhel 7.9.
Furthermore, I have to do it offline for security reasons...

This is what I get:
[cryptography.txt](https://github.com/pyca/cryptography/files/6124594/cryptography.txt)

So deciphering the output, I managed to infer that it needs to download pyo3.
Is it possible to put it inside the archive so that it doesn't try to download it?

Any help would be appreciated.

**Comment by alex** [comment]
It's definitely possible to pre-download these things, as Fedora does precisely that in their builds. I've asked @tiran if he can share how he does this.

**Comment by Kempfu** [comment]
> It's definitely possible to pre-download these things, as Fedora does precisely that in their builds. I've asked @tiran if he can share how he does this.

Thanks, that would be greatly appreciated.

**Comment by tiran** [comment]
The Rust toolchain on RHEL 7 is too old to compile cryptography. IIRC https://www.softwarecollections.org/en/scls/rhscl/rust-toolset-7/ is 1.31. You need at least 1.41 to compile cryptography. First you have to install Rust from a different source.

Then you need to vendor the crates, copy the vendor file to your build machine, and finally provide a patched ``.cargo/config`` to use the vendored crates. You can find my script and instructions in the Fedora dist-git https://src.fedoraproject.org/rpms/python-cryptography/tree/rawhide. RHEL 9 alpha uses the same spec file.

On RHEL 7 is likely missing other stuff. For example it's probably missing cargo RPM macros.

**Comment by tiran** [comment]
> It's definitely possible to pre-download these things, as Fedora does precisely that in their builds. I've asked @tiran if he can share how he does this.

Fedora has dedicated RPMs for crates, e.g. there is a [rust-pyo3 dist-git](https://src.fedoraproject.org/rpms/rust-pyo3/blob/rawhide/f/rust-pyo3.spec) that provides 20 separate [RPMs](https://koji.fedoraproject.org/koji/buildinfo?buildID=1709409) for all features. Most of the stuff is auto-generated.

RHEL on the other hand does not ship Rust crates. Therefore RHEL 9 packages vendor crates. The Fedora dist-git and spec files includes both variants. There is an ongoing effort to unify Fedora, CentOS stream, and RHEL package definitions.

**Comment by tinywrkb** [comment]
For what is worth, I'm building Cryptography without networking as part of Flatpak packaging (Linux) and it surprisingly went pretty smooth.  
I'm just running the usual `python setup.py build` and `python setup.py install --skip-build`. I have all the Python dependencies already installed and the Rust dependencies sources in CARGO_HOME.  
I haven't bothered with packaging PyO3 as I already have Maturin packaged, and it includes PyO3.  
I'm surprised because I didn't find a way to propagate `--offline` argument from setuptools-rust to Cargo like it's possible with Maturin using the `--cargo-extra-args=` option.  
So it seems that it's enough just to the Rust dependencies sources in CARGO_HOME and offline build will work correctly.

@Kempfu your log shows that you're missing pyo3.
