### ISSUE TITLE
Remove dependency on Rust

### ISSUE THREAD

**Issue by radiantone** [pyca/cryptography#6026]
Rust is a non-standard component of all major operating systems and thus any dependency on it renders most upstream dependencies on pyca completely broken. pyca is not able to succesfully install this dependency during its own install. It breaks everything.

Please fix.

**Comment by reaperhulk** [comment]
As discussed extensively in #5771 we are very happy to discuss productive ways in which we can make this easier on users (and some of those efforts have included lowering minimum supported rust version, helping some distributions package rust better, starting conversations around expanding rust triples to better accommodate alternate libc, creating new wheel specs to improve the number of users who can use our prebuilt binaries, and more), but we are not planning to remove one of the best tools available for increasing the security of the software we deliver to end users. 

I am going to close this issue since it has been discussed and we've decided against it, but if you have actionable suggestions on how we can make this transition better please open a new one.

**Comment by radiantone** [comment]
If thats true then why was the original thread locked for comments?

**Comment by reaperhulk** [comment]
It was locked due to a vocal minority uninterested in identifying productive ways to improve the transition making it impossible to converse. Several additional issues did spawn from early in that discussion that resulted in improvements/changes in our messaging, versioning, error handling, et cetera. As I previously mentioned, we are very interested in actionable suggestions, but have no intent to re-litigate the choice itself.

**Comment by radiantone** [comment]
I'm not sure if the committers here understand that in enterprise environments, servers are controlled centrally and software packages have to be whitelisted and for big companies and govt this is a non-trivial process. Just "install rust" is not acceptable solution and in most cases not even possible. In 99.999% of secure (or sensitive) server environments having a compiler of any sorts is "impossible". So while some dev on the team might be amorous with Rust as it is trendy, no user of this package has ever asked for this to be used and it offers zero benefit to users. So probably what I expect to happen is the repo will be forked and put back and everyone will migrate to the supported forked version that doesn't require a rust compiler. It's much simpler to do that than debate peoples favorite languages forever.

**Comment by tiran** [comment]
Thanks for bringing up this concern, @radiantone.

We are very aware of the situation for enterprise customers. Some of us work for companies that provide support for enterprise and government sector.

For example I'm employed Red Hat. At Red Hat I'm the official package maintainer of PyCA cryptography for Red Hat Enterprise Linux, CentOS Stream, and Fedora Linux. PyCA cryptography with Rust support is already available for CentOS 9 Streams and RHEL 9 Beta. You can find the RPM spec file for C9S and RHEL 9 at https://gitlab.com/redhat/centos-stream/rpms/python-cryptography . I'm also in the process of packaging PyCA cryptography for RHEL 8.5. The heated discussion around Rust in cryptography has been read by engineers and managers internally. I have gotten lots of positive feedback and encouragement from upper management and our security & crypto team.

**Comment by alex** [comment]
The two primary maintainers of this package work for the US government and a company with more than 100k employees, so I'm pretty sure we do understand how large organizations work.

If you can't have a compiler to build things, you weren't able to use this package in the first place. This package has required a C compiler to build from the very first release.

Assuming you are just mis-stating things, and you can in fact have a compiler at build time for packages, then the requirement to have `rustc` is no different from a requirement to have `gcc`: it's required at build time, not runtime.
