### ISSUE TITLE
Safely encrypt medium to big sized files with cryptography efficiently.

### ISSUE THREAD

**Issue by dcordb** [pyca/cryptography#6178]
Thanks for this amazing library.

I'm trying to encrypt data from 512 MiB to 1 GiB using Fernet and I've found that it takes a lot of memory to encrypt 512 MiB, for instance:

```python
from cryptography.fernet import Fernet
import os

data = os.urandom(512 * 2**20) # 512 MiB
f = Fernet(Fernet.generate_key())
enc = f.encrypt(data)
```
I monitored the execution of the above code with `htop` and on my computer it reaches 2.5 GiB and peaks at ~3 GiB of memory.

Also other libraries, for example pycryptodome, don't take that much memory to encrypt the same data:

```python
from Crypto.Cipher import AES
import os

data = os.urandom(512 * 2**20) # 512 MiB
key = os.urandom(16)
cipher = AES.new(key, AES.MODE_EAX)
enc = cipher.encrypt(data)
```

On my machine this peaks at ~1.5 GiB.

Is there a (safe) way to use symmetric encryption ciphers at `cryptography.hazmat.primitives.ciphers` so that I can do this without taking so much memory?

**Comment by dcordb** [comment]
In [cryptography documentation](https://cryptography.io/en/latest/fernet/#limitations) it is stated that Fernet is ideal for data that fits in memory (in this case it does). I didn't looked at the code but I would expect that the time and memory complexity would be something like `O(len(data))`. I know python memory management might be a key factor here too.

**Comment by reaperhulk** [comment]
Memory consumption gets this high because you must have a Python bytestring, the C layer must build an equally large ciphertext buffer, and then that buffer must be copied back into Python. If memory consumption is an overriding concern you need to use the low level incremental CipherContext APIs. These allow more efficient memory usage through the [update_into](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/?highlight=Update_into#cryptography.hazmat.primitives.ciphers.CipherContext.update_into) API as well.

However, these APIs, due to their incremental nature, cannot provide ciphertext integrity the same way Fernet does. Instead, if you use them (with `GCM`) you are responsible for ensuring you never use decrypted bytes until you verify the tag.
