### ISSUE TITLE
pypy3.7 windows wheels

### ISSUE THREAD

**Issue by graingert** [pyca/cryptography#6179]
I'm looking to enable pypy3.7 windows CI builds for a number of projects including celery, and not needing to compile cryptography would help a lot

see also

> I would suggest to hold off on macOS and Windows at least until the next release. There is a [bug in macOS](https://foss.heptapod.net/pypy/pypy/-/issues/3405), and PyPy only provides a 32-bit windows version until the next release. People who  want PyPy on macOS can get it (and I assume cryptography) via conda or homebrew.

_Originally posted by @mattip in https://github.com/pyca/cryptography/issues/5806#issuecomment-783395151_

**Comment by mattip** [comment]
The "next release" has been released, the macOS issue has been fixed, and PyPy provides a 64-bit windows version so it seems this is no longer blocked by PyPy. The [wheel building stage in the github workflow](https://github.com/pyca/cryptography/blob/main/.github/workflows/wheel-builder.yml#L120) would need to change since PyPy still does not support a limited API.

**Comment by graingert** [comment]
Don't pypy do hpy for everything now?

**Comment by mattip** [comment]
No, HPy is only in alpha-release stage, and cryptography, as far as I know, uses CFFI not the Python C-API. But even for CFFI, PyPy does not define a usable limited API.

**Comment by reaperhulk** [comment]
pypy 3.7 wheels for macOS and windows have been uploaded and are part of our wheel builder process now.
