### ISSUE TITLE
Lambda Layer 3.8 giving cryptography errors

### ISSUE THREAD

**Issue by exsc185** [pyca/cryptography#6481]
Error on Lambda - 
"errorMessage": "Unable to import module 'lambda_function': cannot import name 'asn1' from 'cryptography.hazmat.bindings._rust' (unknown location)",

Lambda Handler code - (nothing much , just checking the import)
import pysftp as sftp

def lambda_handler(event, context):
   
    return {
        'statusCode': 200,
        'body': json.dumps('Hello from Lambda!')
    }

* Versions of Python, 3.8
bcrypt==3.2.0
cffi==1.15.0
cryptography==35.0.0
paramiko==2.8.0
pyasn1==0.4.8
pycparser==2.20
PyNaCl==1.4.0
pyOpenSSL==21.0.0
pysftp==0.2.9
six==1.16.0
* How you installed ``cryptography`` - pip3 install pysftp - which included cryptography
* Clear steps for reproducing your bug - create virtual environment with python 3.8, upgrade to latest pip 21.3.1, pip3 install pysftp, export the site-packages as lambda layer

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

**Comment by dimitrykhan** [comment]
I am getting same issue. My lambda platform is 3.9. The deployable zip file follows the recommended structure (attached screenshot of the content of the zip)
![image](https://user-images.githubusercontent.com/93273352/142411506-e4c36470-cbfe-470b-8121-d133089be8bb.png)

**Comment by reaperhulk** [comment]
cryptography is a compiled module. Your screenshot shows you are copying windows binaries and expecting them to work on lambda (which is linux).  My last comment includes a link to AWS's documentation that includes this information:

```
If your deployment package contains native libraries, you can build the deployment package with AWS Serverless Application Model (AWS SAM). You can use the AWS SAM CLI sam build command with the --use-container to create your deployment package. This option builds a deployment package inside a Docker image that is compatible with the Lambda execution environment
```

Frankly I'm not sure that this is the right advice, but ultimately we can't support AWS lambda deployments. Amazon needs to do so. I'm locking this because "me too" issues are not useful when we have pointed to resources for users to determine the proper packaging methodology for their environment.

Just for future people so they don't need to scroll up: https://cryptography.io/en/latest/faq/#i-m-getting-errors-installing-or-importing-cryptography-on-aws-lambda
