### ISSUE TITLE
Question about IV/nonce sizing

### ISSUE THREAD

**Issue by ArchGryphon9362** [pyca/cryptography#6546]
> This is a question about AESGCM (if you want slightly more context you can look at closed issue #6543

Hey, I saw that changing the size of the nonce byte array changed the encrypted output (despite no data changing anywhere else). Does this mean that the nonce size must be agreed upon before communication, or is it somehow transported in something like the tag? Like the protocol I'm using includes the nonce during the communication, but only as an integer of a crpyot counter, after which you're meant to generate a 4 long byte array so that you essentially get that same number in a 4 byte array in big endian layout. (the problem is that I want to use a 12 byte long nonce now, but I am unsure if it'll work as well, and I didn't have time to test yet)

**Comment by reaperhulk** [comment]
Nonce size doesn't change encryption with AES-GCM; some AE schemes do alter with size though. Having it alter with size is a good thing because otherwise you open yourself up to potential truncation attacks if you don't out-of-band communicate the expected tag size.

That said, this issue tracker isn't really the correct venue for general cryptographic questions of this nature. I'd suggest the security or cryptography StackExchange sites.

**Comment by ArchGryphon9362** [comment]
Ah ok, thanks!
