### ISSUE TITLE
Make CSR Extension parsing strict again

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#6602]
This means reverting most of 
https://github.com/pyca/cryptography/commit/4da2a68118840a6aeb7cdaa9bd880fb5c908a809 (and changing the test case to fail).

To be done 6-12 months after our 36 release.

**Comment by alex** [comment]
(Putting in this release so we remember to look to see if it's been long enough, or to remember to put it in the 38th release milestone)

**Comment by danilobellini** [comment]
Shouldn't there be a parameter switch in the related functions? Any certificate generator/emitter and server using those non-strict certificates should be fixed ASAP, but some of the already generated certificates will probably be there for a long time. I can no longer open a CA root certificate (one considered valid until Jan 2031) using cryptography, because of what had been described on #6368, and the alternatives are (1) use some other tool to load the certificates, or (2) bypass all client-side security when something relies on a certificate that sets explicitly a flag to its default value. The client side software can't change a certificate it doesn't control (from the server side), and sometimes all we want is to ensure that some communication is secure (for integrity or privacy), but most people are probably going to follow the second path (it's not hard to imagine people arguing like "This is crashing because of a misconfigured HTTPS upstream? Accept the certificate without checking it or use HTTP instead!").

So far, I'm following the path (1) by using OpenSSL directly (in a subprocess) for an [AIA chasing](https://github.com/danilobellini/aia) process that grabs data from some government and financial market sites that happens to keep broken chain certificates (one open public example is the [Febraban's holiday list page](https://feriadosbancarios.febraban.org.br/), I don't use it but, as of today, its certificate has a broken chain). I might be missing something, but I found no way to use Python's `cryptography` for this use case, so I'm just arguing that there should always be a switch to make the relaxed behavior possible for clients. Is a single extra extension field "repeating a default value" so bad that makes the certificates equivalent to the lack of a certificate? If not, there should be a way for the client to use that "not so good" certificate.

**Comment by alex** [comment]
This workaround applies only to CSRs, there's no reason for a CSR to ever be long lived, so these should all exit the ecosystem in good order. We have not applied this leniancy to certificates or other long-lived types.

**Comment by reaperhulk** [comment]
Ping @tiran -- how long has the fix for the certmonger bug seen in #6370 been deployed now? We're planning to revert this change for the next release (in a few months).

**Comment by alex** [comment]
Confirmed with Christian in person that we're good to revert this.
