### ISSUE TITLE
x509 AuthorityKeyIdentifier and SubjectKeyIdentifier have inconsistent APIs

### ISSUE THREAD

**Issue by harmin-parra** [pyca/cryptography#6805]
We should re-open tickets [#5848](https://github.com/pyca/cryptography/issues/5848) and [#5849](https://github.com/pyca/cryptography/pull/5849)

I would like to get the SubjectKeyIdentifier in hexadecimal (HEX) format instead of having a digest.

What is the purpose of the merge of ticket [#5849](https://github.com/pyca/cryptography/pull/5849) ?
```
    @property
    def digest(self) -> bytes:
        return self._digest

    @property
    def key_identifier(self) -> bytes:
        return self._digest
```

Making **key_identifier** identical to **digest** doesn't make sense.

**key_identifier** should return the HEX format of the SKI

**Comment by alex** [comment]
These tickets are closed because we completed the task there -- they were concerned with consistency in attribute naming and now `key_identifier` is available on both AKI and SKI because it's a good description of what the value is.

If you want the hex value, you easily convert the `bytes` to it, for example by `aki.key_identifier.hex()`.

In general we don't provide methods that do trivial encodings, because there's a million of them.

**Comment by harmin-parra** [comment]
OK, thanks for the tip.
indeed **hex()** does what I wanted.
