### ISSUE TITLE
Combining AEAD modes with ciphers

### ISSUE THREAD

**Issue by dkg** [pyca/cryptography#6903]
The cryptography interface currently supports AEAD modes only when specifically combined with certain ciphers (AESCCM, AESGCM, etc).

The next revision of OpenPGP [is considering whether to treat AEAD modes orthogonally to block ciphers](https://gitlab.com/openpgp-wg/rfc4880bis/-/issues/94).  If it does treat them orthogonally, then any python-based implementation is likely to want to apply generic AEAD modes to arbitrary block cipher choices, not just in the current tight coupling.  Alternately, such an implementation would be limited to indicating support for only the block ciphers that happen to be supported by all supported AEAD modes (basically, only AES variants).

This is a feature request asking for cryptography to consider implementing (or to rule out) an interface that allows the user to combine a generic AEAD mode with a generic block cipher.  This would probably still all be within hazmat, and it might use the RustCrypto frameworks (which appear to support that at least for the `eax` crate at the moment).

**Comment by reaperhulk** [comment]
We could create an AEAD class that allowed users to pass a block cipher, but there are several potential limitations based on our underlying OpenSSL dep (which we do intend to keep for cryptographic use):
* OpenSSL only supports four 128-bit block ciphers (AES, Camellia, SM4, and ARIA). Of those, cryptography only exposes AES, SM4, and Camellia.
* OpenSSL's support for the cross product is not great. A cursory check using `EVP_getcipherbyname` (which is possibly incomplete because some things are now only accessible through `EVP_CIPHER_fetch`) suggests that GCM support is not available for Camellia (although, weirdly, it definitely is inside the TLS machinery) or SM4, but is present for ARIA and AES. Additionally, OCB is only available to AES, and CCM is supported by ARIA and AES.
* EAX mode is unsupported.

Given these limitations I'm not sure if there's a great deal of value in building this interface, although we probably would still do so if OpenPGP chooses this path.

I'll also note that I am personally biased towards not providing large numbers of options of 128-bit block ciphers as users are ill-equipped to make decisions about them and the right answer is almost always AES. That said, I understand my position is not necessarily shared by the authors of the OpenPGP spec.

**Comment by dkg** [comment]
fwiw, i actually agree with you that the right answer is almost always AES and i don't much like the idea of encouraging uninteroperable symmetric ciphers.  (fwiw, i would personally prefer to not even have multiple AEAD modes in the next revision of OpenPGP, but that's not the consensus of the design team)

OpenPGP has historically accepted a wide range of ciphers in principle, but in practice there was one common MTI (mandatory-to-implement) ciphersuite that all implementations are expected to support.  For RFC 4880 in 2007, that was 3DES with OpenPGP's idiosyncratic CFB mode.  For the upcoming revision, that's looking like it'll be AES-128 with OCB, but of course the WG may change that.

Thanks for doing the digging inside OpenSSL -- every time i start looking into it, i remember how confused i am by its API and implementation choices, so it's good to have some more-expert confirmation of what i think i found.

Is your expectation for EAX that you won't support it at all within `cryptography` unless OpenSSL grows support for it?  or would you be able to pick up the mode from RustCrypto's `eax` crate somehow?

**Comment by alex** [comment]
Thus far all of our cryptography primitives come from OpenSSL, and our Rust code is focused on parsing. Thus far it's been our plan to keep this separation, as "knowing where your crypto comes from" matters a lot under various auditing regimes (ugh, FIPS). It also keeps our internals simpler, as we can consistently dispatch to OpenSSL, rather than needing to check whether a given algorithm combination comes from OpenSSL or Rust.

**Comment by alex** [comment]
Based on the discussion and limitations of openssl I'm going to close this out for now, as we don't want to revisit our decision around RustCrypto ATM.
