### ISSUE TITLE
ppc64le wheel

### ISSUE THREAD

**Issue by mayurwaghmode** [pyca/cryptography#7010]
Is there any planning to provide the wheels for ppc64le architecture? As they have to build at run-time it is taking much time, which is not acceptable for our use case.  Is it possible to use qemu-user-static in the existing workflow to build the wheels for ppc64le architecture?
Here is the guide for achieving the cross-compilation using GitHub actions and qemu user static - https://sneha-kanekar.medium.com/cross-compiling-using-github-actions-and-qemu-6ade001ee9fd
Here we have built the ppc64le specific wheels for Cryptography - https://github.com/ppc64le-development/cryptography-ppc64le

**Comment by reaperhulk** [comment]
By policy we do not supply wheels for architectures we don’t run directly in CI. We also run an extremely large CI matrix and have spent an almost embarrassing quantity of time both keeping it reliable and performant, which unfortunately precludes running CI within qemu.

Adding additional CI providers carries practical cost to us from a maintenance and reliability perspective so we’d be reluctant to expand our support beyond the GH Actions and CircleCI we already use, but to my knowledge this point is moot since the only CI provider that provides a decent user experience alongside native ppc64le is Travis, which we’re no longer willing to deal with.

I realize this answer is unsatisfying, but ultimately we’re effectively a two person project and we have to triage our effort. If and when ppc64le sees enough use to gain CI support in a major provider we’ll likely revisit this decision.

**Comment by alex** [comment]
Closing based on all the factors @reaperhulk described. If the facts change any PPC64LE CI becomes available (and performant) we'll reconsider.
