### ISSUE TITLE
Verifying signature without passing salt length

### ISSUE THREAD

**Issue by alittwin** [pyca/cryptography#7064]
Hi,

in Openssl there is a way to verify the signature without passing salt length:

openssl pkeyutl -verify -inkey key.pem -keyform PEM -in hash.bin -pkeyopt rsa_padding_mode:pss -pkeyopt digest:sha384 -sigfile signature.bin

Is it possible to do it in Cryptography? Or is there a possibility for it to be implemented?

Best regards,
Adrian

**Comment by reaperhulk** [comment]
There is no mechanism for doing this in cryptography at this time. I believe OpenSSL can detect the salt length via `RSA_PSS_SALTLEN_AUTO`. We could hypothetically add that feature, but we need a few things for that:

1) Let's make sure we have a concrete use case. I suspect this isn't hard here (I want to verify a signature where the salt length is unknown?)
2) A new constant alongside `PSS.MAX_LENGTH`.

We may also want to consider whether we want to add DIGEST_LENGTH since PSS salt == digest length is a very common pattern (and OpenSSL also supports a `RSA_PSS_SALTLEN_DIGEST`, although we wouldn't need it).
