### ISSUE TITLE
rsa.generate_private_key() does not have special error handling with fips openssl 1.1.1

### ISSUE THREAD

**Issue by alimousavifar** [pyca/cryptography#7214]
The fips openssl 1.1.1 (openssl 1.1.1-1ubuntu2.fips.2.1~18.04.15.1) does not support some functions of python3 cryptography 2.1.4 and 3.3.2-1. 

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools`` 

```
ubuntu@ip-10-93-2-63:/opt/safeview/service/test/nosetests$ pip3 freeze | grep "rsa\|crypto\|cffi"
asn1crypto==0.24.0
cffi==1.11.5
cryptography==2.1.4
rsa==3.4.2
```
setuptools is not installed. 

```
$pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

* How you installed ``cryptography``:
Cryptography==2.1.4 was installed via $dpkg i 
As part of the testing, we also installed  Cryptography 3.3.2-1 via 
```
 sudo dpkg -i ~/python3-cryptography_3.3.2-1_amd64.deb
(Reading database ... 284246 files and directories currently installed.)
Preparing to unpack .../python3-cryptography_3.3.2-1_amd64.deb ...
Unpacking python3-cryptography (3.3.2-1) over (2.1.4-1ubuntu1.4) ...
Setting up python3-cryptography (3.3.2-1) ...

```
The list of installed packages after python3-cryptography installation:
```
$ dpkg -l | grep "cryptography\|openssl"
ii openssl 1.1.1-1ubuntu2.fips.2.1~18.04.15.1 amd64 Secure Sockets Layer toolkit - cryptographic utility
ii python3-cryptography 3.3.2-1 amd64 Python library exposing cryptographic recipes and primitives (Python 3)
ii python3-openssl 17.5.0-1ubuntu1 all Python 3 wrapper around the OpenSSL library
```

* Clear steps for reproducing your bug

```
Python 3.6.9 (default, Mar 15 2022, 13:55:28)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.backends import default_backend
>>> from cryptography.hazmat.primitives.asymmetric import rsa
>>>
>>> key_bits=1024
>>> rsa.generate_private_key(public_exponent=65537, key_size=key_bits, backend=default_backend())
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 128, in generate_private_key
 return backend.generate_rsa_private_key(public_exponent, key_size)
 File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 587, in generate_rsa_private_key
 self.openssl_assert(res == 1)
 File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 245, in openssl_assert
 return binding._openssl_assert(self._lib, ok, errors=errors)
 File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 88, in _openssl_assert
 errors_with_text,
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=755388524, lib=45, func=101, reason=108, reason_text=b'error:2D06506C:FIPS routines:func(101):reason(108)')])
```

**Comment by reaperhulk** [comment]
`cryptography` supports FIPS as best effort, but does not attempt to catch all possible errors. This means while we expect `cryptography` to work, we do not promise it won't raise ugly errors when doing something disallowed. This is a pragmatic choice because FIPS errors are generally vendor specific patches rather than anything from upstream OpenSSL itself. In 3.0 this becomes potentially less true, but most/all FIPS OpenSSL in distributions at the moment are 1.0.2 or 1.1.1.

Additionally, the versions of cryptography you're installing appear to come from your distribution, which we do not support. It's almost certain that this same error occurs when compiling using the latest `cryptography` (37.0.2 as of this comment), but since it's a vendor specific patch to raise a FIPS error on insufficient key size we error in this fashion. 

This error message would be a bit more understandable if Ubuntu went to the effort of having a more readable reason text rather than "error:2D06506C:FIPS routines:func(101):reason(108)"
