### ISSUE TITLE
ERROR: Failed building wheel for cryptography

### ISSUE THREAD

**Issue by trankhanhhiep123** [pyca/cryptography#7284]
i'm installing routersploit but it needs to install cryptography package but it has a lot of errors i tried to find a way to fix it but couldn't do it help me as fast as possible machine :32bit termux:armv8l
![Screenshot_20220528-165403_Termux](https://user-images.githubusercontent.com/67538943/170823585-66865d3a-8575-4ec8-b4f0-1131dff7c9bd.jpg)
![Screenshot_20220528-182359_Termux](https://user-images.githubusercontent.com/67538943/170823587-591e7e47-51ab-4a55-bd9f-3f08f7b3885a.jpg)

**Comment by alex** [comment]
I'm not familiar with termux, but https://github.com/pyca/cryptography/issues/6679 contains information on how someone else resolved this.

**Comment by reaperhulk** [comment]
Something about the termux environment results in rust being unable to determine the proper build triple. Setting `CARGO_BUILD_TARGET=aarch64-linux-android` in your environment for aarch64 or `CARGO_BUILD_TARGET=arm-linux-androideabi` for 32-bit arm will hopefully work, but we strongly encourage people to report this upstream so that these environments autodetect properly.
