### ISSUE TITLE
How can I get the same Cipher Text every time when I encrypt from same key and value

### ISSUE THREAD

**Issue by hamzah-sajid-code** [pyca/cryptography#7518]
How can I get the same Cipher Text every time when I encrypt from same key and value? I am using fernet.

**Comment by reaperhulk** [comment]
Fernet uses randomized IVs per encryption precisely to avoid having deterministic encryption which is commonly undesirable since it discloses information about the plaintext and violates a cryptographic property frequently known as IND-CPA, indistinguishability under chosen plaintext attacks.

If you need deterministic encryption for whatever reason then Fernet is not the right choice, although I'd strongly suggest ensuring that's actually a property you want.
