### ISSUE TITLE
buildx and ppc64le wheel

### ISSUE THREAD

**Issue by lehrig** [pyca/cryptography#7723]
On ppc64le, we're discovering more and more python projects depending on cryptography (e.g., https://github.com/kserve/kserve/blob/master/python/third_party/repo.txt) - so I was hoping to revisit https://github.com/pyca/cryptography/issues/7010 here: can we help getting ppc64le support for this project?

Some thoughts:

1. Lots of other projects now combine docker's buildx and manylinux images to become more independent of linux distributions and processor architectures. At the same time, those projects lowered their maintenance efforts for supporting all of that. Here is an example: https://circleci.com/blog/building-docker-images-for-multiple-os-architectures/
2. As a base library, several 3rd party projects depend on cryptography. Not supporting specific architectures will also cause that those projects cannot support those architectures unless they use custom builds or move away from cryptography.
3. I know cryptography development resources are rare, however, my team would be willing to contribute for whatever is ppc64le related.

How does that sound? Anything we could provide to make this happen?

**Comment by reaperhulk** [comment]
in addition to #7010 (which still captures our concerns) we've also discussed this in #6086 and #5083.

We remain exceedingly uncomfortable with shipping binaries that we have not tested, so cross compilation isn't really a useful strategy for us. Broader ppc64le support would ideally come naturally from support for a CI provider that hasn't ignominiously imploded (ideally GHA or CircleCI, although alternatives could be considered if they have the right feature set). If those services had a (performant!) ppc64le builder available we would be very likely to release wheels.

**Comment by alex** [comment]
We now have an FAQ for this: https://cryptography.io/en/latest/faq/#will-you-upload-wheels-for-my-non-x86-non-arm64-cpu-architecture

To be exceedingly blunt: unless there is a CI provider with UX, capacity, and performance to let us run tests, this won't happen.

**Comment by lehrig** [comment]
Thanks for the feedback. I found out the following:

1. **Travis** works (but as noted in https://github.com/pyca/cryptography/issues/7010, it looks like this might cause too much overhead for this community)
2. **GHA** native builders will be available for ppc64le at some point but we are not there yet (it's still a few months out at a guess)
3. **circleci** is not targeted for ppc64le as of today

IMO waiting for GHA support will be the best solution in the long run.

The only thing I'd wish for meanwhile is to enable GHA-based ppc64le builds using docker buildx emulation, so we can bridge the time until GHA native builders become available.

**Comment by alex** [comment]
Is there any update on the availability of these ppc64le builders for GHA?

**Comment by lehrig** [comment]
To the best of my knowledge GHA is targeted for early 2nd half of 2023. I am pretty confident, it won't happen before June, so we're still blocked here...

**Comment by gerrith3** [comment]
Actually, you should be able to do a self-hosted GitHub runner to a VM at OSL now if you wanted to get something going.  The full GHA integration with local Power server builders in Azure or a service that a local runner can connect to may be a bit further out than that although we are working on it.

**Comment by alex** [comment]
Self-hosted runners are extremely painful to operate. We run for macOS arm64, so we're speaking from experience.

The software is finicky and seems to regularly die without logs. It doesn't come with any cross-build isolation (so it can't be run on PRs, making it painful to develop and test). There's no standard base image, it's just YOLO whatever's on the machine.

We pay this pain for macOS arm64 a) because its a widely used platform, b) because we don't actually need to trust the CI runner for builds, macOS is trivial to cross-compile. I'm open to counter-arguments, but that's a lot of pain for a platform as marginal as ppc.

**Comment by reaperhulk** [comment]
It's great that there are VMs out there, but as @alex said we'd really like to avoid running infrastructure (especially non-ephemeral). If the IBM folks have existing cloud infra, it'd be interesting to see whether something like https://github.com/apps/cirrus-runners can be built. Simple one click "self-hosted" runner installation for alternate platforms would go a long way here (including providing the ephemerality we want).

**Comment by reaperhulk** [comment]
It's great that there are VMs out there, but as @alex said we'd really like to avoid running infrastructure (especially non-ephemeral). If the IBM folks have existing cloud infra, it'd be interesting to see whether something like https://github.com/apps/cirrus-runners can be built. Simple one click "self-hosted" runner installation for alternate platforms would go a long way here (including providing the ephemerality we want).

**Comment by reaperhulk** [comment]
It's great that there are VMs out there, but as @alex said we'd really like to avoid running infrastructure (especially non-ephemeral). If the IBM folks have existing cloud infra, it'd be interesting to see whether something like https://github.com/apps/cirrus-runners can be built. Simple one click "self-hosted" runner installation for alternate platforms would go a long way here (including providing the ephemerality we want).

**Comment by reaperhulk** [comment]
It's great that there are VMs out there, but as @alex said we'd really like to avoid running infrastructure (especially non-ephemeral). If the IBM folks have existing cloud infra, it'd be interesting to see whether something like https://github.com/apps/cirrus-runners can be built. Simple one click "self-hosted" runner installation for alternate platforms would go a long way here (including providing the ephemerality we want).

**Comment by reaperhulk** [comment]
Sigh, GitHub issues quadrupled that comment, sorry.

**Comment by gerrith3** [comment]
So @reaperhulk I'm going to have to have my people look at that one.  That's a different model than I've been hoping for, and yes, self-hosted runners would be an interim solution.  I'm wondering though, your self-hosted runner for Mac isn't based on .NET, is it?  It seems like if not that would make it more fragile.  We just completed bringing .NET to the Power platform and thus a self-hosted runner would follow GitHub's pattern a bit better.  But I'm just guessing that it is not .NET based - it could be and then I would fear that we'd be similar which is not my goal.  :(

I really want the runner to be integrated more with our cloud back end, but we haven't figured out how to manage security and such.  Honestly we are still in the evaluation stage right now but we definitely want a better GitHub actions integration, we just aren't sure what the architecture will look like yet.  We'll see if the cirrus-runner model gets us something, but it looks like it is depending on the Cirrus proprietary service which is also a challenge to get integrated with.

Anyway, the ideal is a bit of a challenge because it seems that this is not a scenario that GitHub or MS have put a lot of thought into as yet (running on different architectures) and while there are a couple cases that have work arounds, true integration is going to be the challenge.

**Comment by reaperhulk** [comment]
I don't mean using Cirrus itself (which you clearly shouldn't), but rather that the UX should feel like that. Under the hood there's an API that registers VMs (running GH's default runner software) to orgs/repos. The GHA runner has a `--ephemeral` flag that makes it de-register itself after a single execution, at which point the orchestrator de-provisions the VM and spins up a new one.

This can be done entirely on demand (GHA has hooks for this) so your orchestrator can maintain a pool of "ready" VMs and then register them to a specific org/repo when a build job starts that requires the appropriate tags (with the user having, of course, installed your app so all the permissioning is set up).

Our M1 solution right now runs the native GH runner but is not ephemeral (although I have cobbled together *most* of a purely ephemeral solution using dynamically provisioned macOS VMs similar to what I just described above).

**Comment by reaperhulk** [comment]
https://github.com/actions/actions-runner-controller might be of interest to you as well. It provides a kubernetes-based controller for this sort of provisioning. I would imagine you could use it with ppc64le-based pods/nodes right now, although its architecture is built around having a separate k8s cluster per customer (since every self-hosted customer runs their own) and if you were to build a broader solution you'd want to pay attention to whether the security/isolation guarantees are appropriate for multi-tenancy.

**Comment by h-vetinari** [comment]
Not sure if this helps people here, but conda-forge does [ship](https://github.com/conda-forge/cryptography-feedstock) builds for ppc64le (and even though we don't have native hardware, we can and do run the test suite through emulation with QEMU).
```
conda install -c conda-forge cryptography
```

**Comment by gerrith3** [comment]
@alex apologies for the delay on this one - we are working on a github actions runner service for ppc64le and we were hoping to complete by end of year but we are still a few months out from that.  It's a little more complex that it appears at first blush but it is moving forward just for projects like this.

**Comment by alex** [comment]
Let us know when it's available and we'll take a look.
