### ISSUE TITLE
Is there an API to get the G point of the elliptic curve?

### ISSUE THREAD

**Issue by zer0hk** [pyca/cryptography#8370]
Is there an API to get the G point of the elliptic curve?

**Comment by reaperhulk** [comment]
We don’t have public APIs that return the generator at this time.

**Comment by alex** [comment]
There is not, what is your use case?

**Comment by reaperhulk** [comment]
You should do that via ECIES (which uses ECDH to derive a key suitable for symmetric encryption).

**Comment by zer0hk** [comment]
> You should do that via ECIES (which uses ECDH to derive a key suitable for symmetric encryption).

Thanks, ECIES is a good solution, but what I want to do is asymmetric encryption on elliptic curves. EC-ELGAMAL

**Comment by reaperhulk** [comment]
This project doesn't expose raw elliptic curve point multiplication so you won't be able to do EC-ElGamal. We've talked about potential APIs for this in the past, but no one has stepped up to do the design and implementation. Additionally, things like supporting arbitrary curves are an anti-goal since generic curve implementations are filled with endless side channels.

If you'd like to pursue this then we'd be happy to review proposals in a new issue/PR, but you may be better suited with a library that wants users to perform EC mult operations.
