### ISSUE TITLE
Ability to parse X509 v2 certificates?

### ISSUE THREAD

**Issue by aetherknight** [pyca/cryptography#8555]
The x509 module doesn't support parsing v2 certificates, only v1 and v3. It raises `InvalidVersion` if it is provided with a v2 certificate.

These certificates are rare, but we do encounter them. Would it be possible to support them?

**Comment by alex** [comment]
Can you provide an example v2 cert we could use in a test case?

**Comment by reaperhulk** [comment]
v2 certificates are usually an encoding mistake where they wanted v1 but encoded integer the value 1...which is v2. To my knowledge, in the wild v2 certificates are really only used for attribute certificates ([RFC 5755](https://datatracker.ietf.org/doc/html/rfc5755)) and OpenSSL doesn't directly support them yet (https://github.com/openssl/openssl/pull/15857 is an open PR for handling them).

Are you running into attribute certificates or just misencoded ones? The latter is not something we intend to support, but attribute certificates may be supported in the future (we're not opposed, the work just needs to be done).

**Comment by aetherknight** [comment]
My suspicion is that it is an encoding mistake.

Unfortunately I can't share the certificate -- it was a self-signed certificate our system stores for a customer's SAML Identity Provider.

We parse the certificate to extract some information from it, and we recently sought to switch that parsing code to `cryptography` to remove another dependency. However, one of our customers' certificates raises:

```
cryptography.x509.base.InvalidVersion: 1 is not a valid X509 version
```

For what it's worth, if I pass the certificate into `openssl x509` it parses without issue (note that I'm redacting most parameters), which is why I figured it would be worth opening a ticket:

```
openssl x509 -in cert.pem  -noout -text

Certificate:
    Data:
        Version: 2 (0x1)
        Serial Number: <redacted>
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: <redacted, self-signed>
        Validity
            Not Before: <redacted>
            Not After : <redacted>
        Subject: <redacted>
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    <redacted>
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         <redacted>
```

**Comment by reaperhulk** [comment]
Yeah OpenSSL will just generally parse anything. This has led to a lot of issues (like incorrect versions in certificates!) so we pretty aggressively adhere to the specifications. Even when we used OpenSSL to parse certificates (cryptography 3.4 and below) we rejected certs with invalid versions.

We could choose to lazily error on access instead of on parse, but that's not always an option (other forms of certificate errors are genuinely parse level errors in our stricter parser) and inconsistency in the way we handle things isn't ideal. Plus, it is wrong! 😄

My suggestion would be to retain your alternate dependency for now, but keep this in mind so that when cycling the key in the future you can get your customer to build a fully valid certificate that can be parsed by compliance enforcing parsers.

**Comment by uedvt359** [comment]
This is also an issue for CSRs. I've opened sister-bug https://github.com/pyca/cryptography/issues/8625 about this.
