### ISSUE TITLE
Add "DJB" algorithms

### ISSUE THREAD

**Issue by public** [pyca/cryptography#856]
We currently have pretty good support for NIST stuff but it would be nice to have some modern non-NIST algorithms too.

- [ ] Poly1305-AES
- [ ] Ed25519
- [ ] ChaCha20
- [ ] Curve25519

This would probably require a new (optional?) backend dependency.

**Comment by techtonik** [comment]
Here is Ed25519 in pure Python https://github.com/vbuterin/ed25519

**Comment by ronf** [comment]
Ed25519 is also available via libnacl, which is a thin Python wrapper around libsodium. More information is available at:

http://libnacl.readthedocs.org/en/latest/topics/raw_sign.html

I'm using it to support Ed25519 public keys in AsyncSSH. My use of that can be found here:

https://github.com/ronf/asyncssh/blob/master/asyncssh/ed25519.py

Via libnacl/libsodium, I have also been able to support Curve25519 based key exchange, the Chacha20 cipher, and the Poly1305 MAC algorithm, though I had to extend the libnacl wrapper and directly access libsodium to get at some of those.

**Comment by reaperhulk** [comment]
@ronf there's also pyca/pynacl, although I'm not super involved in that project so I can't tell you what the advantages or disadvantages of it vs libnacl are.

**Comment by ronf** [comment]
@reaperhulk Yes, and there's another thin wrapper around libsodium called pysodium at https://github.com/stef/pysodium. The main thing that attracted me to libnacl is that since it was already using ctypes to expose the libsodium APIs, it was very easy for me to add my own hooks into other APIs there that it didn't expose yet that weren't part of the standard "nacl" interface. I needed those to implement the variant of chacha20-poly1305 that is used in SSH. I didn't have to touch the crypto at all, but I did need to construct the messages slightly differently.

It looks like libsodium is also a ctypes wrapper, and I probably could have used that in a similar fashion to what I did with libnacl, but I don't remember seeing that when I first looked.

**Comment by shea256** [comment]
So a few of the common contributors to pyca projects have made this pure python implementation of ed25519: https://github.com/pyca/ed25519, and it looks like pynacl uses the c implementation.

I'm a bit confused, though. Does Cryptography currently have ed25519 integrated?

**Comment by reaperhulk** [comment]
No, the cryptography project itself does not support ed25519 at this time

**Comment by shea256** [comment]
OK thank you. Was this a conscious decision? Do you plan on adding support for it at some point?

**Comment by reaperhulk** [comment]
It's a natural result of the way our backends currently work. We don't have a good way of handling optional backends so we've limited our surface area to what we can accomplish using OpenSSL. Since OpenSSL doesn't have ed25519 (although it might in the future) we haven't supported thus far.

In the longer term we'd like to have a way to install optional backends that can replace or supplement the openssl and commoncrypto backends, but we're not there yet.

**Comment by shea256** [comment]
OK thank you. I'll check out pynacl then.

**Comment by reaperhulk** [comment]
We'll be adding quite a few of these in the near future with #2968 and ed25519 will likely come in a future OpenSSL. Closing in favor of the newer ticket.
