### ISSUE TITLE
[QoL]Add Defaults to Serialization Functions

### ISSUE THREAD

**Issue by EpicLiem** [pyca/cryptography#9182]
When using this library, I find it annoying how much I have to write in order to just serialize a key and certicates. 
# Examples:

## Example 1
```python
from cryptography.hazmat.primitives import hashes

from cryptography.hazmat.primitives.serialization import PrivateFormat,  pkcs12

encryption = (

    PrivateFormat.PKCS12.encryption_builder().

    kdf_rounds(50000).

    key_cert_algorithm(pkcs12.PBES.PBESv1SHA1And3KeyTripleDESCBC).

    hmac_hash(hashes.SHA1()).build(b"my password")

)

p12 = pkcs12.serialize_key_and_certificates(b"friendlyname", key, cert, None, encryption)
```
vs
```python
from cryptography.hazmat.primitives.serialization import pkcs12

p12 = pkcs12.serialize_key_and_certificates(b"friendlyname", key, cert)
```
##  Example 2:
```python
from cryptography.hazmat.primitives import serialization

private_bytes = private_key.private_bytes(encoding=serialization.Encoding.DER, format=serialization.PrivateFormat.PKCS8, encryption_algorithm=serialization.NoEncryption())
```
vs
```python
private_bytes = private_key.private_bytes()
```

There is no harm in setting a default, and I'd be happy to add them. If you're concerned about bad security practice, then a warning telling users that it's good practice to set a password can be added.

**Comment by reaperhulk** [comment]
In our hazmat layer we have made a design choice to require explicit over implicit so that, when reading the code in the future, the behavior is clear and auditable. Users can wrap these calls in patterns that allow them to reduce verbosity in their own codebase (and if they're doing this frequently they absolutely should!), but I'm not in favor of adding defaults to the APIs themselves.
