### ISSUE TITLE
Test against the LibreSSL fork of OpenSSL?

### ISSUE THREAD

**Issue by public** [pyca/cryptography#928]
http://www.libressl.org/

http://opensslrampage.org/

**Comment by Sp1l** [comment]
Just submitted https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=196827 to FreeBSD ports.
2. Removes EGD (Perl Entropy Gathering Daemon) support. This hasn't been needed on FreeBSD since FreeBSD 4.2
3. Disable compression conditionally using OPENSSL_NO_COMP
4. Check features, not version for x509_vfy
Seems to be working fine for me! Thanks to https://github.com/gentoo/libressl/tree/master/dev-python/cryptography

**Comment by reaperhulk** [comment]
We do this now.
