### ISSUE TITLE
pkcs7 with SHA1

### ISSUE THREAD

**Issue by frankenstein91** [pyca/cryptography#9401]
is there a way to continue using SHA1 in PKCS7 signatures?

I have seen it was removed

**Comment by alex** [comment]
No, SHA1 is insecure for all signature uses, and thus we do not support it.

**Comment by frankenstein91** [comment]
Do you know which was the last version that supported this feature? It would be better if it was hidden inside an "unsafe" flag. That way you could still use the current version to communicate with old applications.

See page 236 of https://download.consolut.com/direct/SAP_PrintDoku/en/BCSRVARL/BCSRVARL.PDF

**Comment by alex** [comment]
It was removed in 39.0, as documented in our change log
https://cryptography.io/en/latest/changelog/#v39-0-0

**Comment by nkutsche155** [comment]
I would also need MD5 and SHA1 functionality. Would be nice to have it as an option.

**Comment by alex** [comment]
This is not going to happen. cryptography is a library for implementing secure systems in Python, and MD5/SHA1 signatures simply cannot be used in a secure construction.

**Comment by frankenstein91** [comment]
I understand the objective of wanting to be a safe haven for Python developers. However, I find the decision to exclude older hashes questionable for two reasons. Reason one is that one cannot check old signatures anymore. Reason two is that developers have to switch to unmaintained versions if they depend on interoperability.
In my view, neither of these contributes to the goal of security.

**Comment by alex** [comment]
First, what we removed was the ability to create new X.509/PKCS#7/etc. objects signed with old hashes, we didn't remove verification because we don't have verification APIs for these types. Given that, I'm not sure I understand your framing at all.

That said, even if we had, what you present is one potential view. Another is that developers need to stop attempting to use insecure signature algorithms.
