### ISSUE TITLE
Provider Bindings

### ISSUE THREAD

**Issue by clundin25** [pyca/cryptography#9654]
Hello team!

I am working on writing an OpenSSL provider that implements signature operations. Given the deprecation of OpenSSL 1.1.1 and the increase in popularity of HSMs, I wanted to check what plans (if any) there are for exporting provider bindings.

I saw this issue from a few years ago, hinting that such a step might happen in the future https://github.com/pyca/cryptography/issues/4967.

I am still _very_ early in my implementation, but I was able to use SoftHSMv2 and my provider to do mTLS using the requests library using only the following functions:

```sh
➜ rg "OSSL[a-zA-Z_1]+" tests/test_mtls.py -o | uniq
OSSL_STORE_open
OSSL_STORE_load
OSSL_STORE_INFO_get1_PKEY
```

**Note**: This was using the `ssl` module, not cryptography.

I am still not sure if more of the API surface will be needed, but I wanted to understand if there are any future plans for this, or if anyone else has explored this area (Seems likely).

Thanks!

**Comment by alex** [comment]
We don't have any particular plans at the moment with respect to providers. I'm very loathe to expose an interface to end-users that could only ever be satisfied via an OpenSSL API, as it'd make it effectively impossible to stop using OpenSSL (even for something like BoringSSL).

If your ultimate goal is API compatibility with our signature APIs, you may be better off simply implementing the interfaces directly to talk to your HSM. See https://github.com/reaperhulk/vault-signing/ as an example of what that looks like.

**Comment by clundin25** [comment]
Thank you for this link @alex! This was a great resource for me to think through.  

My ultimate goal is that I want to use the `requests` library with a private key that I cannot access via a PEM file but via the Provider "URI" schema. From what I can tell the high level APIs in the Python ecosystem only support file based PEM private keys.

It's understandable that you would not want to expose these APIs. My thinking was that I could use the `cryptography` FFFI backend to the OpenSSL binary to setup my private key object. 

After further thinking, an alternative that comes to mind is introducing an API for adding a private key via it's URI in my provider. 

This creates a bit of a circular dependency in the provider code, but that seems fine since it's not really meant for generic use cases. Hopefully this also makes linking to the correct OpenSSL binaries easier, but I will have to think on this further.

Thank you for your help @alex. I will leave this open in case you have more thoughts but feel free to close this issue, I feel this problem has left the scope of this repository.

**Comment by alex** [comment]
So, this is really the most complicated use case: We don't have a TLS API, to get one of those you need to either use the stdlib ssl or pyOpenSSL. Doing any interop between us and the stdlib ssl like this isn't practical, since we're not guaranteed to be linked against the same openssl.

For pyOpenSSL, I can kind of imagine an API that's just "use this private key from a provider URI" on an `SSL` object, since that library is already tied to OpenSSL. (I'll also note that we hate pyOpenSSL as a result -- OpenSSL's APIs are bad, and being totally bound to them mean that we don't like it!)

FWIW, there's a very similar request, but framed differently, from another Googler a few months ago. Unfortunately I'm totally failing to find it in our tracker -- hopefully @reaperhulk knows where it is.

**Comment by clundin25** [comment]
Maybe https://github.com/pyca/cryptography/issues/7892? That was from my colleague.

That makes sense to me, getting something like this to work in the generic case is much more difficult.

You are right, making sure that the correct OpenSSL is being linked to is sort of messy. My interest in exposing these bindings in cryptography meant that I could use those APIs from the same binary cryptography was using. 

Even in if that is the case, our application must make sure that the stdlib and cryptography libraries are using the same downstream OpenSSL version, because the provider will be linking to either the stdlib's OpenSSL or the system OpenSSL.

**Comment by alex** [comment]
Yes, that's the one, thank you!

FWIW, it's not sufficient to just be running the same version, it really need to be from the same shared object (i.e., because both are dynamically linked to the same openssl). While it may work by happenstance in the case of it being the same version, but different shared objects, that cannot be relied upon.

**Comment by clundin25** [comment]
Yes it's brittle. In this case I ended up building the stdlib and cryptography with the same OpenSSL but even then it's not really the greatest solution.

I'm not sure if there is a better alternative, since we are stuck with Python and that providers need to be linked in dynamically.

I plan to start taking a look at using at BoringSSL, but that will mainly be focused on gRPC. It doesn't seem possible to switch to BoringSSL if we want to use the Python stack that we have, but maybe I am mistaken.
